### ISSUE TITLE
Cannot access Watch Later playlist used by official clients

### ISSUE THREAD

**Issue by f3r73ch** [anxdpanic/plugin.video.youtube#1017]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1.4
* Kodi Version: 21.1.0
* Kodi GUI Language: English ?
* Operating System: OSMC (2024.10-1)
* Operating System Language: English ?

------

### Expected Behavior

Please describe the behavior you are expecting.

Seeing the watch later list populated with the corresponding content.

------

### Current Behavior

What is the current behavior?
 
The **Watch later** list is empty.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Just choose watch later entry in the youtube addon

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[kodi.log.gz](https://github.com/user-attachments/files/18030622/kodi.log.gz)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Try with https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.5

If there is still a problem will need a debug log, not a regular log. https://kodi.wiki/view/Log_file/Easy

**Comment by f3r73ch** [comment]
Hi @MoojMidge 

Thank you for your help.


Version 7.1.1.5 didnt help, same behavior.

I've attached the log (now in debug level).

Thx

BR

[kodi.log.gz](https://github.com/user-attachments/files/18037818/kodi.log.gz)

**Comment by MoojMidge** [comment]
Can you try again with the log? Unfortunately it doesn't contain any useful information.

Need to enable debug logging prior to opening the Watch Later list in order to understand what is happening while it is being opened and what is causing it to not show anything.

**Comment by f3r73ch** [comment]
I believe I have the log enabled at the right level.

Im sending you a new capture. I can see the string = `info <general>: Log level changed to "trace"` , being written to the log file when I enable/disable the debug log level, through the gui (in settings > system > logging : Enable debug logging)

Did I miss anything ? 

Thank you 

BR, FG 
[kodi.log.gz](https://github.com/user-attachments/files/18039089/kodi.log.gz)

**Comment by MoojMidge** [comment]
Yes, that's better, but still not quite right because the Watch Later list had previously been opened prior to debug logging being enabled. Need to enable the debug logging prior to opening the Watch Later list for the first time.

I'll try to be a bit more specific:
1. Enable debug logging
2. Close Kodi
3. Open Kodi
4. Open YouTube addon
5. Open Watch Later list
6. Confirm it fails to load
7. Upload log at this point

**Comment by f3r73ch** [comment]
Hi 

I repeated your suggested steps, but the outcome seems to be the same (either the empty result when opening the WL entry through the GUI or the missing relevant information in the log, which I also find strange).

The log is attached though.

Thank you VM 

BR, FG 
[kodi.log.gz](https://github.com/user-attachments/files/18039560/kodi.log.gz)

**Comment by MoojMidge** [comment]
Oh I see what the issue with the logging is now. You have actually disabled debug logging in the GUI, but enabled it in your advancedsettings.xml.

For various reasons this addon only enables additional debug logging when debug logging is enabled in Kodi, but when this is done in the advancedsettings.xml it cannot be detected.

To workaround this you can enable debug logging just for this addon:
`YouTube > Settings > Advanced > Logging > Enable debug logging` (located at the bottom of the `Advanced` settings tab)

**Comment by f3r73ch** [comment]
Hi @MoojMidge 

Thank you for the help.

So, to be clear, all others logs, but the last one, were collected after enabling the log through the gui (just as you mention in your previous reply), but this last one I did edit the advancedsettings.xml as the log level (debug), set throught the gui, didnt hold across Kodi restarts (I ve restarted only Kodi and not the OS). 

I believe the only thing that is written to the log, even in debug level, are those couple of lines surrounding : 

`Path:   |/kodion/watch_later/list/|`

Should I enable "Enable component-specific logging" ? 

Im also finding strange how little is written to the log when I open the WL folder.

I dont know anymore. 

If you have any suggestion Id appreciate it.

Thx 

BR, FG

**Comment by MoojMidge** [comment]
Stick with it, the first few attempts were timing issues, and unfortunately in the last attempt the timing/sequence was right but the method for enabling logging was a problem.

I am not sure why the logging wont stay enabled, but lets skip that for now and do the following instead:
1. Enable `YouTube > Settings > Advanced > Logging > Enable debug logging`,
2. Restart Kodi
3. Open Watch Later
4. Upload the log after this

**Comment by f3r73ch** [comment]
Ok ,

Sending a new capture. (I entered and exited the WL folder multiple times while the log was set to debug)

Thx

BR, FG 
[kodi.log.gz](https://github.com/user-attachments/files/18041944/kodi.log.gz)

**Comment by MoojMidge** [comment]
Thanks for sticking with it. That contains the information needed.

Unfortunately what it also seems to indicate is that everything is working as normal, which means that you may not have anything in your local watch later database, if that was what you were using.

A few things to check:

1. Were you saving items to your watch later list in a YouTube playlist that could be opened in one of the official YouTube clients? If so the reason you are not seeing your watch later list is because no playlist is being used as your watch later list.
2. If you were not saving watch later items to a playlist, then you would have been using the local watch later databse. If this was showing items before and not now, it may mean that there has been some file system issues that has wiped the contents of this database.

Let me know which of the above applies to you.

**Comment by f3r73ch** [comment]
Hi @MoojMidge 

Thank you for the help.

There might be some misunderstanding on my side. Allow me to clarify.

1. I can, in a browser, let's say, see my WL list. I.e., I usually (while navigating, let's say on my laptop) save videos to the WL list). In a browser, on my pc, everything is right and dandy, but on my OSMC the WL folder contains no entries.
2. All other playlists on OSMC show up alright and with the right content, as well as the others, like the Liked/Disliked videos, etc.
3. I'm not using a specific playlist as my WL pl . (If that is what you meant). Indeed, for that purpose, all other playlists work fine. :-)

The WL is quite practical, and that was what I was expecting to see, i.e. being able to save a video in my browser, on my laptop, and later, I can see it on my media center (OSMC) by accessing the WL pl. 

Hope it clarifies.

Thx

BR, FG

**Comment by MoojMidge** [comment]
> The WL is quite practical, and that was what I was expecting to see, i.e. being able to save a video in my browser, on my laptop, and later, I can see it on my media center (OSMC) by accessing the WL pl.

Unfortunately YouTube no longer provides direct access to the same Watch Later playlist that you use when using an official client.

The workaround was to use a create a new playlist and use that as a custom Watch Later playlist, that could be accessed in this addon, and on official clients as well by adding videos to that playlist rather than just selecting Watch Later.

The second workaround was to use a local watch later database, but that can only be accessed via this addon.

There are other ways to identify the playlist that is used by official clients for the Watch Later list, but they are not straightforward and I'm not sure whether the methods work anymore.

**Comment by f3r73ch** [comment]
Sure @MoojMidge 

Thank you for all the help, and sorry for the confusion. 

Best Regards,

**Comment by fcharlier** [comment]
@f3r73ch as I was crawling the GH issues for the same issue as you, I found the [solution here](https://github.com/anxdpanic/plugin.video.youtube/issues/69#issuecomment-766843932)

The WL playlist ID is to be found in your Google takeout archive (just exporting Youtube playlists) in playlists.csv

**Comment by f3r73ch** [comment]
Hi @fcharlier 

Thank you for caring.

I already knew that solution, but in my case, at least, the WL ID is not exported through that method. 

BR, FG

**Comment by dreamlayers** [comment]
I'm still getting my Watch Later playlist id in playlists.csv when I export. It matches the old ID that I configured before at watch_later in access_manager.json. However, now I cannot view it anymore.

Weirdly, if I right click on a video and select "Watch Later", Kodi notifications first say "playlist not found" and then "added to playlist". Accessing YouTube via a web browser, I can see my Watch Later playlist and I see that the video was indeed added. So it seems the Watch Later playlist ID is correct, but that ID is blocked from being viewed.

**Comment by MoojMidge** [comment]
> However, now I cannot view it anymore.
> 
> Weirdly, if I right click on a video and select "Watch Later", Kodi notifications first say "playlist not found" and then "added to playlist".

If you provide a debug log then I can see whether anything can be done about this from the clients end
