### ISSUE TITLE
This video is unavailable

### ISSUE THREAD

**Issue by mr-pineapple-nz** [anxdpanic/plugin.video.youtube#1029]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.9.2
* Kodi Version: 21.1 Omega
* Kodi GUI Language: English
* Operating System: OSMC
* Operating System Language: English

------

### Expected Behavior

Video is played without any issue

------

### Current Behavior

Any video I try to play is failed with the message: This video is not available

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Select a personal playlist on my profile
2. play
3. 

------

### Log

https://paste.kodi.tv/ijadolaloy.kodi 

------

### Additional Information

Running on Raspberry pi4, OSMC 2024.10-1

------

**Comment by drakonash** [comment]
Hi,

Exact same issue for me.

### Context

Please provide any relevant information about your setup

    * Add-on Version: 7.0.9.2

    * Kodi Version: 21.1 Omega

    * Kodi GUI Language: French

    * Operating System: Libreelec

    * Operating System Language: French


### Expected Behavior

Video is played without any issue

### Current Behavior

Any video I try to play is failed with the message: This video is not available

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

    1. Select any video in youtube addon

    2. play

### Log

https://paste.kodi.tv/awiwusulan.kodi

### Additional Information

Running on Raspberry pi4, LibreELEC (Omega) 12.0.1

**Comment by MoojMidge** [comment]
Should already be fixed. Update to https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.6 and see how you go.
