### ISSUE TITLE
Issues with updating local and remote history

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#1033]
The only problem I have now is that it isn't updating my History on YouTube. I have "Use local playback history (watched, resume tracking)" and "Update playback history on YouTube" enabled under Advanced settings.

Also, if you have auto-play recommended. It appears to not include that in the local history.

_Originally posted by @jemiller00 in https://github.com/anxdpanic/plugin.video.youtube/issues/953#issuecomment-2549195539_

**Comment by MoojMidge** [comment]
Please provide a debug log (https://kodi.wiki/view/Log_file/Easy) where the local remote history is not updated:

1. Start a video manually
2. Wait 30s
3. Skip to the end
4. Allow the recomended next video to start automatically
5. Allow video to play for 30s
6. Stop playback
7. Open local history
8. Open remote history on YouTube website and check if it was updated.

**Comment by jemiller00** [comment]
[kodi.old.log](https://github.com/user-attachments/files/18217275/kodi.old.log)

Thanks for your help. Here is my log file. I didn't bother with the automatic play next video. I decided I don't want that enabled anyway. It's not storing manually selected videos on the YouTube website.

It seems like the settings in the UI don't match up with what's happening. Because I had the config HTTP server enabled and it was giving me an error, which you can see in the log about not being able to assign an address. I disabled that and rebooted multiple times and it is still giving me the error. As near as I can tell, that isn't actually causing a problem, but, it was displaying a temporary message on the screen about it.

I'm wondering if there is something similar going on with the setting for saving the history to YouTube.

**Comment by MoojMidge** [comment]
You aren't actually using the latest release. Update and the issue should be resolved.

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.6

As for the HTTP server error, you have configured it to listen on `192.168.1.137` which is not accessible. Try `127.0.0.1` or your actual local IP address.

**Comment by jemiller00** [comment]
Thanks, I will try the new version. I'm surprised there is already a new version. I just installed what I thought was the latest the other day. Maybe, I missed the latest one.

The issue with the HTTP error is that the HTTP server setting is off. Yes, it has a custom IP address in it, but, the server setting itself is disabled. So, it shouldn't be trying to bind to that address. The reason I entered that address is that as far as I could tell, it wasn't listening on all interfaces when the IP address was set to 0.0.0.0. I want to say I saw something somewhere that it was a bug that was fixed.

**Comment by MoojMidge** [comment]
> the HTTP server setting is off
> the server setting itself is disabled. So, it shouldn't be trying to bind to that address.

There is no setting to turn the HTTP server off, what setting are you referring to? The server is started and used if required, rather than being configurable, because if the server isn't available then various playback functions won't work as shown in your log.

> The reason I entered that address is that as far as I could tell, it wasn't listening on all interfaces when the IP address was set to 0.0.0.0.

Listening on `0.0.0.0` is not the same as making a request to `0.0.0.0`, which is not possible.

For reasons that I don't fully understand some systems don't have a functional loopback interface or otherwise respond to broadcasts using a connected physical interface with an external address in preference to a local address.

Is `192.168.1.137` your actual local address? If it is, then for some reason it can't be connected to using port `50152`.
