### ISSUE TITLE
History populated only after entire video has been watched

### ISSUE THREAD

**Issue by blackdaemon** [anxdpanic/plugin.video.youtube#119]
### What Problem Does This Solve? 

The history playlist is populated only after the entire video has been played 
(actually it's enough to fast forward to the end of the video and wait for it to finish)

------

### Suggest a Solution (optional)

I think it would be better if the add-to-history action was triggered at the very beginning of the video instead of at the end of it. Or after configured amount of play time.

History is useful for getting back to videos you watched recently or rather started watching and did not finish. 
It's not that useful to view list of videos you already finished watching.

------

**Comment by Rialtho-the-Magnificent** [comment]
since the solution to the buffering was solved and a pre-release now exists, I noticed that none of my viewed videos on OSMC show up in my history. Only videos watched on OSMC are being 'remembered' including the point up to where the video was watched if not completely watched. Selecting it again offers an option to either watch from the beginning or continue where the video was left.
