### ISSUE TITLE
Let user choose between various quality streams using Kodi's built-in stream selection UI

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#141]
### What Problem Does This Solve? 

Regularly, I find that this plugin on Kodi doesn't choose the 'best' stream for what my current use case may be.

"Play (Ask Quality)" is a workaround. At least for streams that use MPEG-DASH from YouTube (which by now should at least be 'most' as far as I understand their own client concept), it should be possible to pass all the various streams through to be user-selectable on the fly in Kodi.

------

### Suggest a Solution (optional)

I have dangerous half-knowledge of how this plugin works, so the following may be completely off the mark.

I seem to understand that the plugin creates a dynamic MPD from the stream descriptions it gets from YouTube and uses a local server to pass this MPD - containing one stream for audio and one for video, as chosen by the plugin - on to Kodi for playback.

Going from there, it doesn't seem too far off to generate an MPD containing all (or 'most') of the streams as provided by YouTube, and from there on Kodi (together with InputStreamAdaptive, if I understand things correctly) should already provide seemless and dynamic switching of streams.

------

**Comment by XxAcielxX** [comment]
There is an option in YouTube Add-on to ask for quality on playing of every videos. Or you can set the VP9 Codec with the desired resolution in InputStream_Adaptive Add-on.

I have done the latter option and all my videos play at max set desired (in my case 1080p) at 60fps when available.

**Comment by tylerswagar** [comment]
Lately I've only been able to get a maximum of one DASH format available through "ask for quality", in addition to the non-DASH 720p and 360p formats.  And sometimes it's not the one I want.  Sometimes I have to flip through different quality levels in the add-on settings to get 60 fps to show up.  It's especially hard to get 720p60 a lot of times.  Sometimes the closest I can do is 1080p60, but only if I go back and set the quality to adaptive.  Other times, having it in adaptive mode means my only option is 4k60, which would be overkill, so I have to lower it to 1080 or 720 and hope that helps.

I suspect it's an API issue related to the "no streams found" fix.  I know DASH is working because if I turn it off, I don't even get the one format, but it would be nice if I had more options like I did a couple versions ago.
