### ISSUE TITLE
Cannot open channel with playlist not found error

### ISSUE THREAD

**Issue by akb825** [anxdpanic/plugin.video.youtube#205]
### Context

* Add-on Version: 6.8.17
* Kodi Version: 19.1
* Kodi GUI Language: US English
* Operating System: Arch Linux
* Operating System Language: US English

------

### Expected Behavior

Accessing the [LoL Esports playlists](https://www.youtube.com/user/ShooterNoobx) channel through the subscription list displays the available playlists.

------

### Current Behavior

Accessing the [LoL Esports playlists](https://www.youtube.com/user/ShooterNoobx) channel fails with a playlist not found error.

------

### Steps to Reproduce

1. Subscribe to [LoL Esports playlists](https://www.youtube.com/user/ShooterNoobx).
2. Access the channel through the subscription list in Kodi.
3. Channel fails to open with playlist not found error.

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/7263918/kodi.log)

------

### Additional Information

The channel contains only playlists with no videos of its own. I suspect this is the cause of the error.

------

**Comment by jmbreuer** [comment]
I came across this / a similar issue with a currently empty channel. Being able to browse playlists and the 'Live' sections of an otherwise empty channel seems reasonable. The error message certainly is more confusing than an empty results list.

When I find the time I'll look into converting that particular error into an empty result list that would then still get the 'Live', 'Playlists' (and less usefully 'Search') meta-items.
