### ISSUE TITLE
Are SubTitles really working for everyone with Alpha 4?

### ISSUE THREAD

**Issue by jmh2002** [anxdpanic/plugin.video.youtube#226]
Are SubTitles really working for everyone with Alpha 4?

Tested with multiple different videos on Windows and LibreElec but they don't seem to work for me.
(they were working previously for me on earlier versions, I had them permanently enabled)

plugin.video.youtube-6.8.18.alpha4+matrix.1.zip
Kodi 19.1
English (and English SubTitles)

**Comment by ebym** [comment]
Nope, only working with 6.8.17 - on RPi4, LE10, Matrix 19.1.

**Comment by kedarz** [comment]
For me sutitles do not work at all with alpha4. What is more if I setup subtitles to start automatic i have only error without starting video. 
ERROR <general>: OpenStream - Unable to create subtitle parser
After reboot there is no message about error and video starts but without subtitles still

**Comment by RNavega** [comment]
Hi guys. Since it's working here on Kodi 18 (Leia) I think this might be related to Matrix and up.

Just so I can reproduce the problem, can you share one or more video links that you know aren't working?
The important part of the address is the "watch?v=[...]" which has the video ID, so we know we're comparing the same videos.

Another thing you can do after playing the video with subtitles activated and they don't work, is going to your Kodi cache folder and seeing if there's a subtitle file in there, and what its contents are.  
On Windows the path is `C:\Users\<YourUsername>\AppData\Roaming\Kodi\cache\plugin.video.youtube\`
This `cache` folder is in [different locations](https://kodi.wiki/view/Kodi_data_folder#Location) depending on your OS. You're looking for the `/cache/plugin.video.youtube/` folder after playing the video, to see if the add-on created a subtitle file. 

Subtitle files created by this add-on will be named like this: `video_id.language.srt`, something like `3eGP6im8AZA.en.srt`.

@kedarz can you please share your full Kodi log? You can find the log [in these locations](https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste), and then upload it to here and share the link to it: https://paste.kodi.tv/  
If it's refusing to play a video then that's more serious.

**Comment by anxdpanic** [comment]
I've just pushed a fix for subtitles, alpha5 is available from the usual places

**Comment by anxdpanic** [comment]
closing this in favor of #222
