### ISSUE TITLE
Can't play some age restricted videos

### ISSUE THREAD

**Issue by Doktor-X** [anxdpanic/plugin.video.youtube#228]
### Context

Please provide any relevant information about your setup

* Add-on Version:6.8.18 alpha1-alpha5
* Kodi Version:18.9
* Kodi GUI Language:Croatian
* Operating System:linux (CoreElec on s912 box)
* Operating System Language:English

------

### Expected Behavior

After addon auto updated to the alpha 4 of dev addon i cant no longer play age restricted content, downgrading to alpha 1 its all working fine

------

### Current Behavior

Alpha 1 can and Alpha 5 cant play age restricted content

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try play this random video 
2. https://youtu.be/pZ2bLSIcOms
3. Using any dev version after alpha 1

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
Thanks for the report.

Currently it works with some age-restricted content, and not others. For example, https://www.youtube.com/watch?v=HtVdAasjOgU works, and is also age-restricted. It is something to look into further.

**Comment by anxdpanic** [comment]
alpha6 is available from the usual places, this should resolve age-gated material that wasn't working

**Comment by jonisb** [comment]
Had a couple of videos I wasn't able to watch because of the age gate, with alpha6 now all seem to work beautifully, thanks for the continued support.

**Comment by joshg253** [comment]
Alpha6 fixed my current Age-restricted issues. I did have to sign out and re-auth via the two goog URLs (no big deal).
(previous buffering issues fixed by alpha2+haxxx also fixed in alpha6 without having to hax0r the two files again).

**Comment by Doktor-X** [comment]
Some videos have "video is unavailable" popup
https://youtu.be/3kYApjjugaM

**Comment by FaBjE** [comment]
I experience this issue too. After alpha 6 the error changed from the age-gate message to the video unavailable message.
On the last official .18 release it has changed to: "Sorry, something is wrong. This video may be inappropriate for some users. Sign in to your primary account to confirm your age."

I have done a fresh sign-in using the two device codes. My account is age-confirmed (using creditcard thanks to new EU regulations) and in the browser I can play the video without any error message.

Example:
https://www.youtube.com/watch?v=0YEZiDtnbdA

Debug log:
https://pastebin.com/muE82zEW

**Comment by Fludizz** [comment]
Just out of curiosity: Is it required to be logged in with an age-verified account for the plugin to play age-restricted video's?

This week, for the first time ever, I've gotten the popup stating I need to verify my age to play a video on Kodi _(I have not verified my age with Youtube because I do not trust Google with my creditcard information nor a copy of my ID)_. Previously it was able to play any Age Gated video's without issues.

I'm running plugin v6.8.18 - if it should play Age Gates video's no matter if the used account is age-verified: Let me know and I'll collect debugs for you.

**Comment by Fludizz** [comment]
Tried it while logged in to an age verified account - there is definitely something going wrong because it still gives the "_Sorry, something is wrong. This video may be inappropriate for some users. Sign in to your primary account to confirm your age._" message. Both video's can be played fine (after logging in) from the webbrowser.

Example video's:
https://www.youtube.com/watch?v=xym2R6_Qd7c
https://www.youtube.com/watch?v=oCyYJxuStVE

Debug log:
https://pastebin.com/KjybiGTD

**Comment by Doktor-X** [comment]
Just tride to send your links to kodi with yatse and videos PLAY fine without problem, i have logged in  with my age verify account to kodi addon

I think that you need to edit google account settings itself to get it working if you have Youtube branding account, someone else gave me that info but at moment, cant find info about that i'm not home

**Comment by Fludizz** [comment]
Not sure what has changed (at youtube) but I have retried the previously mentioned video's a few times over the last days without any luck. However, since today it no longer throws the error and it now plays them perfectly fine without issues.

**Comment by david-morris** [comment]
I'm still getting this problem with, for example, https://www.youtube.com/watch?v=6QFwo57WKwg

**Comment by Doktor-X** [comment]
> I'm still getting this problem with, for example, https://www.youtube.com/watch?v=6QFwo57WKwg

Corrently i'm using workaround (but its without sound). Im using app https://github.com/yausername/dvd
To find direct link to video file and then send it to kodi using yatse. It's not perfect since its only video without sound but........
