### ISSUE TITLE
Recommendations folder not showing up

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#275]
Add-on Version: 6.8.18+matrix.1
Kodi Version: 19.3
Kodi GUI Language: English
Operating System: Windows 10
Operating System Language: English

When I go to the add-on settings to have the recommended folder it doesn't appear

**Comment by menotuu** [comment]
Yes, that's true, it's been like that for a long time. But there is no statement on this or whether the bug is being worked on. A few references to suggested solutions have so far only been ignored. Too bad.

**Comment by anxdpanic** [comment]
I haven't ignored any suggestions, if you can point me to them I'd be happy to take a look.

I'll double check next chance I have, but I'm pretty sure it's not available from the api anymore and I just forgot to remove the setting. But again I'll double check when time allows.

**Comment by menotuu** [comment]
glad to hear from you!

this is what I mean: https://github.com/anxdpanic/plugin.video.youtube/issues/254

**Comment by anxdpanic** [comment]
Those are completely unrelated to recommendations, will reply there.

**Comment by menotuu** [comment]
okay than sorry. but newpipe and youtube vanced have working recommendations on android for example.
why are the recommendations not able to display?

**Comment by anxdpanic** [comment]
I will be looking into recommendations and some other things again in the future, since we're using the tv client api for playback now.
The Tubed add-on will probably be the better add-on of the two in the end. 

But I am currently working on Twitch add-on's API migration, which is priority since they turn the version of the api we are using off at the end of the month.

Recommendations don't work currently because the v3 DATA api no longer provides them iirc.
Like I mentioned though, the tv client api was recently added for playback (fix buffering issue), so there may be an opportunity to re-add it using that api until they kill it. And time is the issue right now.

**Comment by ghost** [comment]
It works now

**Comment by IvanSadovskyi** [comment]
> It works now

Not for me
