### ISSUE TITLE
Video not playing, nothing happens

### ISSUE THREAD

**Issue by TheNetworkIsDown** [anxdpanic/plugin.video.youtube#315]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: Kodi-19.4
* Kodi GUI Language: English
* Operating System: Libreelec
* Operating System Language: English

------

### Expected Behavior

The video should play. I'm starting it using Yatse.

------

### Current Behavior

The video doesn't play. The spinning wheel displays and then goes away and nothing happens.
This video isn't the only one. I'm not sure what is common about the videos that don't play.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Start Video NY9Wrpw3igs
2. Nothing happens
3. 

------

### Log

https://www.toptal.com/developers/hastebin/raw/asoxoxuhey

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by Killom** [comment]
Same issue here.

YouTube (6.8.18+matrix.1) on Matrix (Kodi-19.4) with Python 3.8.9

https://pastebin.com/DxLd1yas

video = tGIorMfERtQ

Had this issue happen several times in the past. Random videos. When starting them some days later, playback will work again. I think this will happen mostly on recently uploaded videos. But last info should be taken with a grain of salt. Not sure on this one.

If I'm understanding the log correctly, there is an issue with retrieving the video from Youtube. 

`ERROR <general>: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)`

Or, this could be due to an unspecified pixel format? Maybe the pixel format is missing, because file is incomplete?

`DEBUG <general>: ffmpeg[0x30fd878X]: [mov,mp4,m4a,3gp,3g2,mj2] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 1037 kb/s): unspecified pixel format`
