### ISSUE TITLE
Feat Request: Hide Short Videos

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#318]
Ability to hide those worthless social media shorts videos when viewing “My Subscriptions” would be an welcomed feature for usability. 

Assuming there’s no direct method to accomplish this, I suggest a setting to “Hide videos under X mins” e.g. 2 mins. 

As always, thanks for your hard work anxdpanic.

**Comment by netty0** [comment]
Yes please! Thank you 🙏

**Comment by RNavega** [comment]
lol I've been meaning to try the opposite: being able to play the shorts.  
For some reason, for me the shorts just don't work (Kodi stays with the busy spinning icon, playback doesn't start). Using 18 Leia.

Are these shorts playable for anyone else using this add-on?

_Note to self, the only way to detect if a video ID is a short is by using a HTTP HEAD_: https://stackoverflow.com/questions/71192605/how-do-i-get-youtube-shorts-from-youtube-api-data-v3

**Comment by probonopd** [comment]
Pleeeease add an option to fiter away "Shorts" videos. They are plain annoying.

They have "shorts" in their URL, like this:
https://www.youtube.com/shorts/H0wHK0_vY6Q

These "Shorts" are so annoying there are whole threads about them:
https://www.reddit.com/r/youtube/comments/loix4f/is_there_a_way_to_filter_out_shorts_videos/

`<rant mode>`
These "Shorts" are especially annoying on big screens, like TVs.
Almost braindead to show 9:16 videos on 16:9 screens.
In addition to that, the content of such videos is usually lower quality as well.
`</rant mode>`

**Comment by neo-neo1** [comment]
> Pleeeease add an option to fiter away "Shorts" videos. They are plain annoying.
> 
> They have "shorts" in their URL, like this: https://www.youtube.com/shorts/H0wHK0_vY6Q
> 
> These "Shorts" are so annoying there are whole threads about them: https://www.reddit.com/r/youtube/comments/loix4f/is_there_a_way_to_filter_out_shorts_videos/
> 
> But they are especially annoying on big screens, like TVs.

Amen brother, amen. The last thing I want to watch, especially on a big TV is god damn stupid shorts. Let us pray for this feature.

**Comment by probonopd** [comment]
Where in the code could one hook in a filter that would simply remove all videos that are shorter than 90 seconds from the list which gets displayed?

Is there a way to observe which functions are being called by Python as one uses the plugin (tracing)? So that one would know where one could best hook the filtering in...

**Comment by ThubLives** [comment]
Or filter out anything with ```#shorts``` in the description.  I'm not sure if that is part of how the shorts work, but it's been in the description of every YouTube Shorts video that I've seen.

**Comment by RNavega** [comment]
> Is there a way to observe which functions are being called by Python as one uses the plugin (tracing)? So that one would know where one could best hook the filtering in...

The way I usually debug a Kodi plugin is trying as far as possible just by reading the code and doing text searches (names of functions, variables, classes etc.), right here on Github.  
Then if you still have doubts, going to the code and adding print calls like [xbmc.log](https://xbmc.github.io/docs.kodi.tv/master/kodi-base/d6/db2/group__python__xbmc.html#ga3cd3eff2195727144ad6fbabd4744961), Python's [traceback.print_stack()](https://docs.python.org/3/library/traceback.html#traceback.print_stack) etc. 

Anyway, I did some investigation.  
When this plugin requests a list of videos, be it from a text search, channel, playlist etc, it calls function `v3._process_list_response`:
https://github.com/anxdpanic/plugin.video.youtube/blob/36e037518bbb14a06a4928c9dd5b77baaa70c3d3/resources/lib/youtube_plugin/youtube/helper/v3.py#L17

That function creates `VideoItem` type objects, and fills them with metadata in the `utils.update_video_infos` function:
https://github.com/anxdpanic/plugin.video.youtube/blob/374bf2ab66cf01746076e1cc17311e148fba46e8/resources/lib/youtube_plugin/youtube/helper/utils.py#L239

It's in that `update_video_infos` function where several requests are made (using the `ResourceManager.get_videos` function) to get extended `videoResource` data from the Youtube API (or from your local device cache, if they're already loaded). In this data there comes the duration of the video.  

So at any point after that `update_video_infos` call is made inside `_process_list_response` ([in this line here](https://github.com/anxdpanic/plugin.video.youtube/blob/36e037518bbb14a06a4928c9dd5b77baaa70c3d3/resources/lib/youtube_plugin/youtube/helper/v3.py#L273)), you could rebuild the `result` list where any item of type `VideoItem` must have more than X seconds of duration (queried with either the `VideoItem.get_duration()` method, or the `._duration` attribute for speed).  
This "X" time tolerance and the filtering itself can be a couple of new settings to be added to the settings.

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by anxdpanic** [comment]
I've pushed an alpha with the new setting, also pushed to the testing repositories

**Comment by anxdpanic** [comment]
>Get started with YouTube Shorts
YouTube Shorts is a way for anyone to connect with a new audience using just a smartphone and the Shorts camera in the YouTube app. YouTube’s Shorts creation tools makes it easy to create short-form videos that are up to **60 seconds** long with our multi-segment camera.

I limited it to 60 seconds or less since shorts are maximum 60 seconds according to the YouTube doc.

**Comment by probonopd** [comment]
Thanks @anxdpanic for implementing this very useful feature :+1: 

Got a crash, think we need to use `if hasattr(item, "_duration")` somewhat like this:

```
    if context.get_settings().hide_short_videos():
        shorts_filtered = []
        for item in result:
            if hasattr(item, "_duration"):
                if item._duration > 0 and item.get_duration() <= 61:
                    continue
                shorts_filtered += [item]
        result = shorts_filtered
```

Note:
* `if hasattr(item, "_duration")` removes the crash for me
* I use 61 seconds because somewhere I read that sometimes YouTube reports 1 second more
* I also check for `item._duration > 0` because Live videos have duration `-1` and we don't want to filter those out

__...but:__

* This seems to work for channels (the videos in a channel are filtered) but it does not seem to have any impact of the videos in **"My Subscriptions"**
* The filtering seems to happen after results have already been paginated, which means that the number of videos per page will differ depending on how many videos were filtered out. Ideally the filtering would happen before pagination

**Comment by probonopd** [comment]
According to my quick poll on Twitter, it seems like almost no one likes YouTube Shorts:

![image](https://user-images.githubusercontent.com/2480569/197251491-8c732803-4f58-4a19-bb39-4f831ecabd01.png)

https://twitter.com/probonopd/status/1582801071101030400

**Comment by anxdpanic** [comment]
pushed a fixup for that and live videos

**Comment by anxdpanic** [comment]
>"My Subscriptions"
The filtering seems to happen after results have already been paginated, which means that the number of videos per page will differ depending on how many videos were filtered out. Ideally the filtering would happen before pagination.

Ideally, that happens to require heavier quota use and likely a bunch more code I don't personally have the time for. Hopefully others continue to contribute and can help though.

**Comment by probonopd** [comment]
Thanks @anxdpanic, but those issues remain:
* This seems to work for channels (the videos in a channel are filtered) but it does not seem to have any impact of the videos in **"My Subscriptions"** (this is the main use case for me)
* The filtering seems to happen after results have already been paginated, which means that the number of videos per page will differ depending on how many videos were filtered out. Ideally the filtering would happen before pagination (I personally can live with this - you explained this above)

**Comment by anxdpanic** [comment]
I can look at my subscriptions, completely missed that, sorry. Hopefully this weekend. pre-pagination will have to wait though.

**Comment by ThubLives** [comment]
Is video length the best to identify these?  The ```#shorts``` hashtag in the description is helpful, but it seems not to be systemic &ndash; it turns out they are manually added by the channel owner to help engage the Algorithm &ndash; however I would have thought that the URL would be a more reliable way to filter these.

My concern is that this will filter out a lot of other content.  I'm not interested in filtering out short videos, but rather videos uploaded under the YouTube Shorts program, which is aimed at a different audience.  There is plenty of content that happens to be short in length, but does not otherwise follow the format that is so reviled.

I wish I could commit some time to looking into this.  I hope I can find some time in the next week or so.

**Comment by probonopd** [comment]
For me personally, I'd be totally happy with filtering out anything under 61 seconds. It would filter out all that "channel advertising" type of low value videos.

But I can see that people would want to filter out all content in portrait mode, because it is just silly on a big screen TV.

> videos uploaded under the YouTube Shorts program

YouTube even conveniently marks those with an icon:

![image](https://user-images.githubusercontent.com/2480569/197264730-8a16ed5b-0bc9-4c63-bf1d-965cfd2aa525.png)

So maybe there is some metadata that could be used to filter those out.

**Comment by ThubLives** [comment]
> For me personally, I'd be totally happy with filtering out anything under 61 seconds. It would filter out all that "channel advertising" type of low value videos.
> 
> But I can see that people would want to filter out all content in portrait mode, because it is just silly on a big screen TV.

I think it's a good idea to keep features like this few and focused such that they will be useful to the most users.  As such, I think a time-based filter is too broad.  Yes, I agree that it will filter out channel intro videos, but I think that is a relatively small percentage of what will be inadvertently filtered out.  The typical channel doesn't upload new intros more than once per year, but short, supplemental videos or community updates (which can be time sensitive if it is a call for community interaction) can be quite frequent for some YouTubers, and I frankly applaud those who resist turning them into &num;shorts.

I'm obviously also thinking of my own use of the platform, but if I follow channels that happen to have some shorter videos, then I either don't get to use the "hide YouTube Shorts" feature because too much gets caught in the filter or have to keep switching back and forth to make sure I'm not missing anything.  I just think it's a good idea to keep bespoke filters like this as focused as possible on a single purpose.

**Comment by probonopd** [comment]
Actually, it would be best to have to separate filtering options now that filtering is being added:
* Filter videos under X seconds, with X being configurable (1 minute, 2 minutes, 5 minutes, 10 minutes, 30 minutes)
* Filter videos uploaded under the "YouTube Shorts" program (as indicated by YouTube with that icon)

**Comment by RNavega** [comment]
> Filter videos uploaded under the "YouTube Shorts" program (as indicated by YouTube with that icon)

@probonopd it'd be great if there was a way to do that, but at the moment the API doesn't provide some piece of info on whether the video is a short.   
The icons only appear on the website bc they're served already there, on the page HTML.
That stackoverflow link I posted before says that the only way to check if a video ID is from the shorts program, is by doing a HTTP HEAD with it in a specific way and seeing if it redirects. But that would mean one request per ID, very inefficient. 

So maybe this could be added as a warning: in case you try to play a shorts video it'd ask you "are ya sure?"

**Comment by probonopd** [comment]
> So maybe this could be added as a warning: in case you try to play a shorts video it'd ask you "are ya sure?"

That'd defeat the purpose, I think. Anyway, I'm happy with filtering based on duration.

**Comment by anxdpanic** [comment]
As @RNavega mentioned, there is currently no reasonable way to determine the difference between a short and a movie/k-pop teaser for example. Which is why I labelled the setting, `Hide short videos` not `Hide YouTube Shorts`. 

I did push a fix to the test repositories for `My Subscriptions` though 👍

**Comment by probonopd** [comment]
> I did push a fix to the test repositories for My Subscriptions though +1

Works for me. So happy! Thank you very much :1st_place_medal:

**Comment by probonopd** [comment]
Something went wrong with the alpha3 release:

```
Removing resources/lib/youtube_plugin/kodion/utils/view_manager.py
error: patch failed: addon.xml:1
error: addon.xml: patch does not apply
Error: Process completed with exit code 1.
```

**Comment by upbox-org** [comment]
> As @RNavega mentioned, there is currently no reasonable way to determine the difference between a short and a movie/k-pop teaser for example. Which is why I labelled the setting, `Hide short videos` not `Hide YouTube Shorts`.
> 
> I did push a fix to the test repositories for `My Subscriptions` though 👍

Alpha3 works fine for me. 
Subs feed is filtered too now.   
Thank you!

**Comment by probonopd** [comment]
Where did you get it from? I am looking for the matrix version specifically.

**Comment by upbox-org** [comment]
> Where did you get it from? I am looking for the matrix version specifically.

From the test repo for matrix. 
https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation
Direct download: https://panicked.xyz/repositories/matrix/repository.yt.testing_unofficial-2.0.2+matrix.1.zip

**Comment by probonopd** [comment]
So, http://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/kodi/youtube/python3/unofficial_testing/zips/plugin.video.youtube/ - thanks for the hint.

Works for me, love it :+1:

**Comment by nubjub** [comment]
Thank you, thank you, thank you.
