### ISSUE TITLE
full list of available resolutions on play

### ISSUE THREAD

**Issue by SntNick** [anxdpanic/plugin.video.youtube#328]
Hi all,

I can't config the plugin to show full list of resolutions :-( Specifically above 720p I can see only one resolution set in MPEG-DASH-Video quality.
For example, if I set MPEG-DASH-Video quality to 1080p or Adaptive the list of available resolutions will be "1080p, 720p, ...."
if I set MPEG-DASH-Video quality to 1440p the list of available resolutions will be "1440p, 720p, ...."
if I set MPEG-DASH-Video quality to 2160p the list of available resolutions will be "2160p, 720p, ...."
It there any way to get the list of available resolutions as I see it using YT web interface "2160p, 1440p, 1080p, 720p, ...."?

Regards,
Niko

**Comment by anxdpanic** [comment]
I don't have the ability to detect what hardware is capable of which codec at which resolution. So at this time no, sorry.

**Comment by SntNick** [comment]
No need to detect HW/codecs, just give all the options YouTube shows when opened from a browser.

**Comment by MoojMidge** [comment]
This is now implemented since #506 if `Settings > MPEG-DASH > Stream selection` is set to `Quality selection` or `Auto + Quality selection`.

The full list of resolutions are available to view and change via the `OSD > Settings > Video settings > Video stream` dialog. It uses automatic stream selection by default, and the others can be selected manually, in a similar way to the official Youtube clients.
