### ISSUE TITLE
Wrong framerate (only through MPEG-DASH)

### ISSUE THREAD

**Issue by lennartgoosens** [anxdpanic/plugin.video.youtube#336]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.20
* Kodi Versions: 18.9.0 (LibreELEC) / 19.4.0 (Windows)
* Kodi GUI Language: English
* Operating Systems: LibreELEC 9.2.6 on Intel x86-64 / Windows 10 Pro version 1909 (build 18363.1556) on Intel x86-64
* Operating System Language: English (LibreELEC) / Dutch (Windows)

------

### Expected Behavior

Video is started in the right frame rate right away.

(And depending on settings, Kodi can then correctly adjust the refresh rate from the start.)

------

### Current Behavior

Video is started in [frame rate 1] (WRONG), then after 5 seconds switches to [frame rate 2] (RIGHT).

- 23.976 fps (WRONG) -> 24.000 fps (RIGHT)
- 29.970 fps (WRONG) -> 30.000 fps (RIGHT)
- 59.940 fps (WRONG) -> 60.000 fps (RIGHT)

But, NO sudden switch for video that is either *actually* in one of those fractional frame rates, or 25fps and 50fps. (My wild guess: could this be due to some rounding error, as the NTSC and non-NTSC frame rates are so close?)

------

For the sake of completeness, how Kodi reacts to this change in frame rate:
1) it causes the picture to go blank for a moment

and if the option "Adjust display refresh rate" is enabled in Kodi Settings > Player (I have it on "On start"):

2) it also causes the display to go blank (for far longer at least on my TV) and readjust to a new refresh rate (often after it had just gone blank adjusting to the wrong refresh rate five seconds before), and
3) usually but not always, it causes the audio to be temporarily interrupted as well.

------

As a PARTIAL WORKAROUND, turning that option off at least stops (2) and (3) from occurring, but the picture still flickers. Also, turning this off can only be done globally AFAIK, and means looking at judder in half the video's from any source/add-on. So bye bye Vsync...! :(

------

### Steps to Reproduce

1. Play either a 24fps, 30fps or 60fps video through MPEG-DASH:
- 30fps: https://www.youtube.com/watch?v=PjOE6qlZ3rU
- 30fps: https://www.youtube.com/watch?v=dYpu3qW2UdQ
- 24fps judder test: https://www.youtube.com/watch?v=eQ9pk2SgY9s
- 30fps judder test: https://www.youtube.com/watch?v=yUeJ3rjDztQ
- 60fps judder test: https://www.youtube.com/watch?v=WrS2HBLScbc

Press O for Player process info ASAP, after 5 seconds the framerate unexpectedly switches (for instance) from 29.970 fps (WRONG) to 30.000 fps (RIGHT).

2. Play the same video without MPEG-DASH enabled; 

Press O for Player process info ASAP, the framerate is and remains (for instance) 30.000 fps (RIGHT).

3. (OPTIONAL)
Play any of these UNAFFECTED videos through MPEG-DASH:
- 23.976fps judder test: https://www.youtube.com/watch?v=FLkHN0Pgq50
- 29.970fps judder test: https://www.youtube.com/watch?v=SG2oKibyrT0
- 59.940fps judder test: https://www.youtube.com/watch?v=WnGYBUuTsPg
- 25fps judder test: https://www.youtube.com/watch?v=kpod7SaeZcU
- 50fps judder test: https://www.youtube.com/watch?v=t8Rtwr70HOc

Press O for Player process info ASAP, the framerate is and remains (for instance) 25.000 fps (RIGHT).

------

### Log

Log of playing the first video in the list above:
https://paste.kodi.tv/ewedojumud.kodi

What jumps out to me (almost exactly 5 seconds apart):

line 1354:
2022-10-19 23:54:10.299 T:13900   DEBUG <general>: ActiveAE::SyncStream - average error of -57.821371, start adjusting
line 1355:
2022-10-19 23:54:10.299 T:13900   DEBUG <general>: ActiveAE::SyncStream - average error -27.844047 below threshold of 30.000000

line 1394:
2022-10-19 23:54:15.095 T:19232   DEBUG <general>: CVideoPlayerVideo::CalcFrameRate framerate was:29.970030 calculated:30.000000
line 1395:
2022-10-19 23:54:15.126 T:19232   DEBUG <general>: CRenderManager::Configure - change configuration. 1920x1080. display: 1920x1080. framerate: 30.00.

------

### Additional Information

- I have downloaded the source material of the first video in the list using an online tool, to verify the actual framerate. Both the WEBM/VP9 and MP4/H.264 files are all 30.000 fps, and playing them from file does not trigger the issue.
- Switching between VP9 or H.264 in the "MPEG-DASH" tab makes no difference.
- I've played with every setting in the "MPEG-DASH" tab and under "Configure InputStream Adaptive" until my fingers got sore, nothing makes a difference.
- Switching between hardware and software decoders in Kodi makes no difference.

Thank you for making this add-on, I wouldn't want go back to a time without it! :) Anything to help you squash a bug. (Or the folks at Inputstream Adaptive if the issue is in their code.)

------

**Comment by toupeira** [comment]
Seeing the exact same behaviour with Kodi 20.1.

I found [this related inputstream.adaptive issue](https://github.com/xbmc/inputstream.adaptive/issues/843) which sounds like it's talking about the same thing too, unfortunately it got closed without a clear conclusion. It might be a problem with "manifest" files (are these a thing with YouTube?), or a problem in Kodi itself.

**Comment by toupeira** [comment]
After digging through the code I found [these lines in `video_info.py`](https://github.com/anxdpanic/plugin.video.youtube/blob/f97ffbeba79459259eba01c9b8b6a12506cce0e3/resources/lib/youtube_plugin/youtube/helper/video_info.py#L1196-L1200) which remap some frame rates "to a more common representation to lessen the chance of double refresh changes".

So apparently this was added specifically to work around this issue, but if I remove the scaling like so (just guessing, more cleanup might be needed):

```diff
--- video_info.py.old	2023-04-23 01:29:18.659334874 +0200
+++ video_info.py	2023-04-23 01:29:20.595369727 +0200
@@ -1181,12 +1181,10 @@
             # map frame rates to a more common representation to lessen the chance of double refresh changes
             # sometimes 30 fps is 30 fps, more commonly it is 29.97 fps (same for all mapped frame rates)
             frame_rate = None
-            fps_scale_map = {24: 1001, 30: 1001, 60: 1001}
             if 'fps' in stream_map:
                 fps = int(stream_map.get('fps'))
                 data[key][i]['fps'] = fps
-                scale = fps_scale_map.get(fps, 1000)
-                frame_rate = '%d/%d' % (fps * 1000, scale)
+                frame_rate = fps
 
             data[key][i]['frameRate'] = frame_rate
 ```

...the problem seems to be actually fixed! Videos start with the correct frame rate from the beginning, and there's no blanking/frame rate change/refresh rate change after a few seconds.

Now I wonder if this workaround was originally needed because YouTube sometimes reported incorrect frame rates, and either this was fixed completely on their side, or only for videos uploaded after a certain date.

Either way, I'll keep this fix locally and will report back if I encounter any breakage.

Relevant commits:
- https://github.com/anxdpanic/plugin.video.youtube/commit/ec4f8478f6b574484ada517ce5e74cb9957e4d25
- https://github.com/anxdpanic/plugin.video.youtube/commit/14af80235fa120150f8f47c484e34190c79291dd

**Comment by toupeira** [comment]
Oh, I was wrong: My diff above only fixes videos with integer frame rates, but now affects fractional frame rates (like some of the sample videos in the issue description labeled "unaffected"). So looks like the remapping is still needed and we're back to square one. Sorry for the noise! :see_no_evil:

**Comment by fedprod** [comment]
The refresh rates are not wrong and also not a rounding error, thats how the old Anologue NTSC/PAL/SECAM Standards worked with the signal synching in old cathode ray tubes and every digital LED/LCD/etc Discplay device support the old polling rates just fine without juddering. **That result** is a result of the video stream not beeing cast correctly or in the correct format from youtube itself **OR** even more bothersome, input adaptive tweening dropped frames which is sometimes especially jarring, so that is the main reason I personally never using that option myself ^^"

**Comment by Tomte-Fan** [comment]
I'm seeing this issue as well even with 7.0 alpha 3, it's quite annoying as I use a projector and changing framerate is slow, almost always getting a black screen about 5s into a video and the projector takes about 3-4s to switch.

**Comment by anxdpanic** [comment]
This is because YouTube only provides `30` for all ~30fps content. So even if a video is `29.97fps`, all I get is `30`. So we make the best guess, and only right half the time. Can't do much about this atm.

**Comment by Tomte-Fan** [comment]
Ok, maybe change the default since it seems to me that it does a switch in 9/10 videos I play.

**Comment by FunctionalHacker** [comment]
Would it be feasible to create a configuration option to switch the default between integer and fractional frame rates? It looks like the vast majority of videos I watch are in integer frame rates and are affected by this. 

Having an option would at least provide users a way to get the best match possible to the content they consume.

**Comment by MoojMidge** [comment]
There are already too many options IMO, but I suppose this could be added to the stream features selection.

Would rather add some code to automatically disable this workaround if it is no longer necessary.

It would be helpful if someone who is bothered by this would be able to test what recent versions of InputStream.Adaptive and Kodi do when the framerate is not included in the manifest.

Commenting this line out should be enough I think:
https://github.com/anxdpanic/plugin.video.youtube/blob/8c543b78a4a18d9f1ab28ce21321463b6482691b/resources/lib/youtube_plugin/youtube/helper/video_info.py#L1826

**Comment by toupeira** [comment]
Quickly tested the above on stable versions (Kodi 20.3, InputStream.Adaptive 20.3.16, YouTube 7.0.2.2) using the 24fps video https://www.youtube.com/watch?v=eQ9pk2SgY9s

What happens is that the FPS is reported as zero, so no refresh rate change happens when starting playback:

```
debug <general>: CRenderManager::Configure - change configuration. 1920x1080. display: 1920x1080. framerate: 0.00.
```

And then it switches to `24` after a couple of seconds, triggering the refresh rate change:

```
debug <general>: CRenderManager::Configure - change configuration. 1920x1080. display: 1920x1080. framerate: 24.00.
```

Would be great if someone could also test Kodi 21, in case something has changed there. I'm not sure if there are any beta builds available for Flatpak or Debian.

**Comment by MoojMidge** [comment]
So is that better/worse than before?

From what I understand the issue is that with the current method in place, Kodi will change the screen refresh rate at the start of playback, but then change it again if the original framerate information was incorrect.

Removing the framerate information removes the double refresh rate change but means that the video will initially play at an incorrect refresh rate, and may never switch to a correct refresh rate if the user does not enable the adjust display refresh rate option in Kodi.

Assuming that a simple two state option was added to this plugin, what is the preference for the two states?

1. Enable framerate hinting (current behaviour) <-> Disable framerate hinting (as above); or
2. Enable fractional framerate hinting (current behaviour) <-> Enable integer framerate hinting (basically the same as current behaviour but will instead be incorrect for the complementary subset of videos with which it is currently correct, and vice versa)

**Comment by toupeira** [comment]
> So is that better/worse than before?

Hmm I guess it depends:

- With a non-fractional framerate video, it's slightly better because the refresh rate change now only happens once, although still delayed (vs. one at the beginning and one delayed).
- With a fractional framerate video, it's slightly worse because the refresh rate change is now delayed (vs. at the beginning).

So I'm not sure it's worth adding a setting for your option 1, but option 2 might be more worthwhile for those users who mainly watch non-fractional framerate videos. In my case it's pretty much a toss-up with the channels I watch, even on the same channel it's not always consistent. I only tested because I was hoping InputStream.Adaptive might do the right thing :)

BTW I saw the v3 API provides a `double` framerate, unfortunately the `fileDetails` are only available to the video owner: https://developers.google.com/youtube/v3/docs/videos#fileDetails.videoStreams[].frameRateFps

**Comment by MoojMidge** [comment]
> BTW I saw the v3 API provides a `double` framerate, unfortunately the `fileDetails` are only available to the video owner:

Even if this was available for content consumers, it doesn't necessarily help. It is the fps of the uploaded video, not the video stream being played. 

> * With a fractional framerate video, it's slightly better because the refresh rate change now only happens once, although still delayed (vs. one at the beginning and one delayed).
> * With a non-fractional framerate video, it's slightly worse because the refresh rate change is now delayed (vs. at the beginning).

Am I misunderstanding, or should this be swapped? The fractional framerate videos should only ever have one display mode change.


> So I'm not sure it's worth adding a setting for your option 1, but option 2 might be more worthwhile for those users who mainly watch non-fractional framerate videos.

I'm not fussed either way, but I would have thought that for the majority an optional compromise (slightly better and slightly worse) would be more useful than an option that only benefits a handful of people (based on the number who commented in this issue) with a specific viewing profile.

Will leave this open for more comment.

**Comment by toupeira** [comment]
> Am I misunderstanding, or should this be swapped? The fractional framerate videos should only ever have one display mode change.

Sorry yes, I was thinking about it wrong :facepalm: Edited my comment for clarity.

> I'm not fussed either way, but I would have thought that for the majority an optional compromise (slightly better and slightly worse) would be more useful than an option that only benefits a handful of people (based on the number who commented in this issue) with a specific viewing profile.

Fair enough, I just meant that personally I probably wouldn't use either setting. But yes don't mind me, let's hear others' opinions :+1:

**Comment by MoojMidge** [comment]
> Will leave this open for more comment.

Never mind, added both options to the stream features selection

Edit: Will need to rethink this. Adding settings like this is problematic as the defaults will not be used unless the user resets their settings. Also the commit itself is wrong.

**Comment by Aloyah1** [comment]
Hi,

Did you find a solution today ? Is there a way to avoid changing the resolution ?

> ### Contexte
> Veuillez fournir toute information pertinente sur votre configuration
> 
> * Version complémentaire : 6.8.20
> * Versions Kodi : 18.9.0 (LibreELEC) / 19.4.0 (Windows)
> * Langue de l'interface graphique Kodi : anglais
> * Systèmes d'exploitation : LibreELEC 9.2.6 sur Intel x86-64 / Windows 10 Pro version 1909 (build 18363.1556) sur Intel x86-64
> * Langue du système d'exploitation : anglais (LibreELEC) / néerlandais (Windows)
> 
> ### Comportement attendu
> La vidéo démarre immédiatement à la bonne fréquence d’images.
> 
> (Et en fonction des paramètres, Kodi peut alors ajuster correctement le taux de rafraîchissement dès le début.)
> 
> ### Comportement actuel
> La vidéo démarre à [fréquence d'images 1] (FAUX), puis après 5 secondes passe à [fréquence d'images 2] (DROITE).
> 
> * 23,976 ips (FAUX) -> 24 000 ips (DROIT)
> * 29,970 ips (FAUX) -> 30 000 ips (DROIT)
> * 59,940 ips (FAUX) -> 60 000 ips (DROIT)
> 
> Mais PAS de changement soudain pour la vidéo, c'est-à-dire _en fait_ dans l'une de ces fréquences d'images fractionnaires, soit 25 ips et 50 ips. (Ma supposition folle : cela pourrait-il être dû à une erreur d'arrondi, car les fréquences d'images NTSC et non NTSC sont si proches ?)
> 
> Par souci d'exhaustivité, comment Kodi réagit à ce changement de fréquence d'images :
> 
> 1. cela fait que l'image devient vide pendant un moment
> 
> et si l'option « Ajuster le taux de rafraîchissement de l'affichage » est activée dans Paramètres Kodi > Lecteur (je l'ai sur « Au démarrage ») :
> 
> 2. cela fait également que l'écran devient noir (pendant bien plus longtemps au moins sur mon téléviseur) et se réajuste à un nouveau taux de rafraîchissement (souvent après qu'il soit devenu noir en s'ajustant au mauvais taux de rafraîchissement cinq secondes auparavant), et
> 3. Habituellement, mais pas toujours, cela provoque également une interruption temporaire de l'audio.
> 
> En guise de SOLUTION DE CONTOURNEMENT PARTIELLE, la désactivation de cette option empêche au moins (2) et (3) de se produire, mais l'image scintille toujours. De plus, désactiver cette option ne peut être effectué que globalement, à ma connaissance, et signifie regarder des saccades dans la moitié des vidéos provenant de n'importe quelle source/module complémentaire. Alors au revoir Vsync...! :(
> 
> ### Étapes pour reproduire
> 1. Lisez une vidéo à 24 ips, 30 ips ou 60 ips via MPEG-DASH :
> 
> * 30 images par seconde : https://www.youtube.com/watch?v=PjOE6qlZ3rU
> * 30 images par seconde : https://www.youtube.com/watch?v=dYpu3qW2UdQ
> * Test de saccades à 24 ips : https://www.youtube.com/watch?v=eQ9pk2SgY9s
> * Test de saccades à 30 ips : https://www.youtube.com/watch?v=yUeJ3rjDztQ
> * Test de saccades à 60 ips : https://www.youtube.com/watch?v=WrS2HBLScbc
> 
> Appuyez sur O pour obtenir des informations sur le processus du lecteur dès que possible. Après 5 secondes, la fréquence d'images passe de manière inattendue (par exemple) de 29,970 ips (FAUX) à 30 000 ips (DROIT).
> 
> 2. Lisez la même vidéo sans MPEG-DASH activé ;
> 
> Appuyez sur O pour obtenir des informations sur le processus du lecteur dès que possible, la fréquence d'images est et reste (par exemple) de 30 000 ips (À DROITE).
> 
> 3. (FACULTATIF)
>    Lisez l'une de ces vidéos NON AFFECTÉES via MPEG-DASH :
> 
> * Test de saccades à 23,976 ips : https://www.youtube.com/watch?v=FLkHN0Pgq50
> * Test de saccades à 29,970 ips : https://www.youtube.com/watch?v=SG2oKibyrT0
> * Test de saccades à 59,940 ips : https://www.youtube.com/watch?v=WnGYBUuTsPg
> * Test de saccades à 25 ips : https://www.youtube.com/watch?v=kpod7SaeZcU
> * Test de saccades à 50 ips : https://www.youtube.com/watch?v=t8Rtwr70HOc
> 
> Appuyez sur O pour obtenir des informations sur le processus du lecteur dès que possible, la fréquence d'images est et reste (par exemple) de 25 000 ips (À DROITE).
> 
> ### Journal
> Journal de lecture de la première vidéo de la liste ci-dessus : https://paste.kodi.tv/ewedojumud.kodi
> 
> Ce qui me saute aux yeux (à presque exactement 5 secondes d’intervalle) :
> 
> ligne 1354 : 2022-10-19 23:54:10.299 T:13900 DEBUG : ActiveAE::SyncStream - erreur moyenne de -57,821371, commencez à ajuster ligne 1355 : 2022-10-19 23:54:10.299 T:13900 DEBUG : ActiveAE::SyncStream - erreur moyenne -27,844047 en dessous du seuil de 30,000000
> 
> ligne 1394 : 2022-10-19 23:54:15.095 T:19232 DEBUG : CVideoPlayerVideo::CalcFrameRate la fréquence d'images était de : 29,970030 calculée : 30,000000 ligne 1395 : 2022-10-19 23:54:15.126 T:19232 DEBUG : CRenderManager::Configurer - modifier la configuration. 1920x1080. affichage : 1920x1080. fréquence d'images : 30,00.
> 
> ### Informations complémentaires
> * J'ai téléchargé le matériel source de la première vidéo de la liste à l'aide d'un outil en ligne, pour vérifier la fréquence d'images réelle. Les fichiers WEBM/VP9 et MP4/H.264 sont tous à 30 000 ips, et leur lecture à partir d'un fichier ne déclenche pas le problème.
> * Basculer entre VP9 ou H.264 dans l'onglet « MPEG-DASH » ne fait aucune différence.
> * J'ai joué avec tous les paramètres de l'onglet « MPEG-DASH » et sous « Configurer InputStream Adaptive » jusqu'à ce que mes doigts me fassent mal, rien ne fait de différence.
> * Basculer entre les décodeurs matériels et logiciels dans Kodi ne fait aucune différence.
> 
> Merci d'avoir créé ce module complémentaire, je ne voudrais pas revenir à une époque sans lui ! :) Tout pour vous aider à écraser un bug. (Ou les gens d'Inputstream Adaptive si le problème réside dans leur code.)

Hi,

Did you find a solution today ? Is there a way to avoid changing the resolution ?

**Comment by MoojMidge** [comment]
Please read the issue thread. The options available are identified. How they may work for you is something you can test for yourself.
