### ISSUE TITLE
Purchased movies stop after about 5 minutes

### ISSUE THREAD

**Issue by MartChic** [anxdpanic/plugin.video.youtube#35]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.5
* Kodi Version: 18.8
* Kodi GUI Language: French
* Operating System: LibreElec 9.2.4
* Operating System Language: French

------

### Expected Behavior

Purchased movies should play normally.

------

### Current Behavior

As the title says, purchased movies stop after about 5 minutes. All other videos play fine.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Purchase movie on Youtube
2. Play with with the Youtube extension.
3. 

------

### Log

https://drive.google.com/file/d/1unGGfOnqNmZvEzyAlFmnle4IR81Wy9Ls/view?usp=sharing
[01_KODI.log](https://github.com/anxdpanic/plugin.video.youtube/files/5396251/01_KODI.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MisterD81** [comment]
I have the same issue on Windows and LibreElec RPi. But I was not able to reproduce it on Linux x64. So I took a look at it and the issue is from my understanding not in the YT addon. The license expires after 5 minutes and inputstream.adaptive is not renewing the license.
I could see in the EME logger that CDM is triggering this event, but it was not triggered in inputstream.adaptive. I managed to modify inputstream.adaptive so that also there the license renewal is triggered, since the main code was already there but commented out. After that for me the playback worked.
If I find the time the next days I will create a PR for inputstream.adaptive.

**Comment by MartChic** [comment]
Great! Could you tell which lines need to be commented out?

**Comment by MisterD81** [comment]
In inputstream.adaptive addon you need to find the file:

1. wvdecrypter/cdm/media/cdm/cdm_adapter.cc
2. wvdecrypter/wvdecrypter.cpp


In both files there are lines that start with: "//LICENSERENEWAL: ". If you remove this part and compile the addon the playback started to work for me. But when you stop the playback Kodi will crash. There are some more additions required so that Kodi does not crash.
I still need to some more testing before I can create the PR.

**Comment by MisterD81** [comment]
Finally I was able to test the changes successfully on the "production" system at home. Therefor I have created the two PRs for Matrix and Leia.

**Comment by MartChic** [comment]
Did you fix the crash on stop issue?

**Comment by MisterD81** [comment]
Yes. There are some additions as mentioned previously required so that every is cleaned when playback stops.
