### ISSUE TITLE
suddenly only low-resolution streams available?

### ISSUE THREAD

**Issue by zen85** [anxdpanic/plugin.video.youtube#424]
I am using this plugin now for a long time on my kodi but since yesterday i can only see 144x256p streams on it. It always worked with HD streams too autotmatically and now i dont even see the better streams when trying to choose a different stream manually.
I, of course checked, if the streams  are available in a normal browser... its just this plugin that seems to be affected.

Is there a possibility that yt is pulling some shenanigans on us kodi users?

**Comment by bratekarate** [comment]
Got the same issue. But I have some sort of workaround:

Go to addon settings -> General and check "Always ask for the video quality". 

Then, before a video starts, a popup will ask you for the quality. Pick 720p.

Unfortunately, you will have to pick for every video now. I have no idea why the 1080p streams is not working in the first place.

AFAIK, the issue is only the 1080p stream, at least for me. My guess is that the 1080p stream fails and the addon automatically picks the lowest quality as a fallback (don't ask me why).

So I would propose a kind of fix for these situations, so that the addon always tries the next highest quality instead of the lowest.

**Comment by h31p** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6369 related, i guess.

another try by g00gle to throttle down yt videos in non-native apps.

**Comment by virtualdreams** [comment]
720p stream also starting with today.

**Comment by anxdpanic** [comment]
anyone have a debug log to post of this?

**Comment by virtualdreams** [comment]
Currently not, no error messages. Only that the video loading takes longer than usual.

**Comment by anxdpanic** [comment]
will need to enable debug logging and reproduce. will be a lot more information about the available streams then.

**Comment by virtualdreams** [comment]
I hope it helps...

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10875406/kodi.log)

**Comment by DoctorVanGogh** [comment]
This *might* be related, or may be its entire own issue:

The last few days almost **all** videos will "loose" the video stream at 1:06-1:16 after start. Seeking back and forth will regrab the stream. Simply continuing playback will not (for over 30-45 seconds)

Smells of suppressing video for when they want to inject ads (but not as obvious as twitch does it with the rainbow-y streams).

**Comment by h31p** [comment]
> will need to enable debug logging and reproduce. will be a lot more information about the available streams then.

please take a look at 
https://github.com/yt-dlp/yt-dlp/issues/6400#issuecomment-1454903800

**Comment by virtualdreams** [comment]
Updated libreelec to 11 (Kodi 20) and with this the addon to 7.0.0. The resolution issue has gone so far (2 videos tested).
