### ISSUE TITLE
A way for the Kodi-YouTube addon to work without requiring users to set up a YouTube API key

### ISSUE THREAD

**Issue by mYnDstrEAm** [anxdpanic/plugin.video.youtube#43]
### What Problem Does This Solve? 

A convenient, integrated way for accessing YouTube is a main requirement for a complete and comprehensive media center like Kodi strives to be or at least could be.

Requiring users to set up the addon without plug&play functionality is a major barrier to that. Requiring them to [set up developer API keys](https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys) even more so.

This is a barrier to users who prefer to not log in / have associated API keys on the device Kodi is running on and to users who are not tech-savvy (aside from requiring time and effort which is especially relevant to newcomers to Kodi just wanting to try out the software).

------

### Suggest a Solution (optional)

It seems like YouTube videos can be embedded without a problem. For example see [this Vue component](https://github.com/kaorun343/vue-youtube-embed). But it seems to be impossible to directly _search_ (and retrieve recommendations etc) from YouTube without an API key.

In this issue I'd like to ask about which ways could conceivably exchange such data with YouTube or YouTube overlay websites without requiring the user to set up a personal YouTube key. Here's what I found so far:

* the Kodi-reddit addon plays YouTube videos
* maybe [invidious](https://github.com/iv-org/invidious) could be used for this
* maybe an API key could be setup / assigned automatically when setting up the Kodi-YouTube addon with a new key being set up each time one starts the addon (or something similar to it)
* maybe youtube-dl could be used for this
* maybe [noembed or sth similar could be used for this](https://stackoverflow.com/a/32190892)
* it should be possible to just search the website with a user-agent like in the browser (also see the other solutions from the link above)

Do you know of more options?

Then this issue is also about _how_ this could be implemented _best_ / the implementation.

I think this is a really important issue for Kodi. (Once it's solved I hope that the Kodi-YouTube addon becomes suggested to the user during installation so the only thing that the user needs to do is check a box to install the addon with Kodi for less experienced users and convenience.)

------

See https://github.com/anxdpanic/plugin.video.tubed/issues/234

**Comment by anxdpanic** [comment]
I appreciate the time you took in this, but this all has been addressed before. Everyone seems to assume I want it this way?

>the Kodi-reddit addon plays YouTube videos
>maybe noembed or sth similar could be used for this
>maybe youtube-dl could be used for this

So does this add-on `plugin://plugin.video.youtube/play/?video_id=<video_id>` in a `.strm` plays the video with no need for keys, discoverability of video id's being the issue without keys. This is probably what the reddit add-on is using.

> maybe invidious could be used for this

invidious is the incorrect language to use here

> maybe an API key could be setup / assigned automatically when setting up the Kodi-YouTube addon with a new key being set up each time one starts the addon (or something similar to it)

No, we're allowed to exist on YouTube/Google's whim, I'm not about to programmatically circumvent their API system.

> it should be possible to just search the website with a user-agent like in the browser (also see the other solutions from the link above)

This add-on uses the api, not scraping web sources. Someone is very free to create an addon called \<something different\> that scrapes the web.

The API keys are required due restrictions put in place by Google, this add-on in particular will never be able to meet the requirements necessary to remove this. It is what it is, and I don't like it as much as you or anyone else.

There is something being done to resolve the issue as best as possible, it may not be everyone's favorite solution though.
I don't wish to talk about it publicly at the moment due to do current limitations, feel free to PM me on Kodi Forum or email me @ gmail if you wish to know more about that.

edit: Sorry to the github user gmail that I just pinged accidentally :)

**Comment by mYnDstrEAm** [comment]
> Everyone seems to assume I want it this way?

I didn't assume this: I outlined why exactly I believe this to be useful and important.

> This is probably what the reddit add-on is using.

But what about [noembed](https://noembed.com/), things like noembed and youtube-dl?

> invidious is the incorrect language to use here

What do you mean? I think [the invidious API does not require API keys and hence could allow searching YouTube without API keys requirements within Kodi](https://github.com/iv-org/invidious/wiki/API).

> No, we're allowed to exist on YouTube/Google's whim, I'm not about to programmatically circumvent their API system.

Okay, _if_ that is the case maybe somebody is interested in a fork or otherwise separate addon for the reasons I named? In particular: convenience, making things easier and faster to setup up, competitiveness of Kodi to other media centers, usefulness for people who don't want to login e.g. for privacy reasons, and for people that are less tech-savvy etc.

> This add-on uses the api, not scraping web sources. Someone is very free to create an addon called <something different> that scrapes the web.

Okay. However, I think the options listed above also include ways that aren't "scraping web sources".

> The API keys are required due restrictions put in place by Google, this add-on in particular will never be able to meet the requirements necessary to remove this. It is what it is, and I don't like it as much as you or anyone else.
> There is something being done to resolve the issue as best as possible, it may not be everyone's favorite solution though.

Okay, that sounds both good and bad at the same time. I'll keep track of it in any case; let's see how this goes.

**Comment by anxdpanic** [comment]
You may not have personally assumed it, it's just tiring at this point and sorry if I came off short at all.
This has been addressed numerous times in the old repository and in the forums, there is actually a thread of 100+ on the old repository.

>But what about noembed, things like noembed and youtube-dl?

Those provide playback solutions, the issue isn't playback. The add-on can play things just fine without API keys. This is why third party addons(reddit addon) and trailer add-ons that use the YouTube add-on don't require you to have keys. The issue is about video id discoverability so they can be listed. I actually switched to use youtube-dl in the add-on at one point and got a lot of complaints due to the slow down it causes compared to the current playback code, so it was switched back. youtube-dl is also limited to 360-720p in Kodi iirc as well.

> Okay. However, I think the options listed above also include ways that aren't "scraping web sources".

From what I've seen they are using the underlying requests from the website, this isn't "allowed and what I meant by scraping web sources. If this add-on started that way long ago it likely wouldn't be an issue today. However, as it stands now the add-on breaks TOS in so many ways that it exists on a thread. Adding things that make that worse at this stage seems like asking for the YouTube add-on being taken down to me. Hence the current situation.

> Okay, if that is the case maybe somebody is interested in a fork or otherwise separate addon for the reasons I named

That's always been the case and the beauty of open source, as long as the add-on id and name are changed there is no issue there at all. Though they may face external issues, that I can't predict.
I'd suggest a new add-on to anyone interested to save headaches, but that's up to that person :)

> Okay, that sounds both good and bad at the same time. I'll keep track of it in any case; let's see how this goes.
 
My hope and feeling is that it is/will be a step toward achieving what you're issue represents, and hopefully the majority of users can appreciate the result :)

**Comment by anxdpanic** [comment]
Something for Kodi 19 early adopters; [Tubed](https://github.com/anxdpanic/plugin.video.tubed) is a new add-on to access your YouTube content that is currently in beta. You'll find more information in the link.

**Comment by tlaurion** [comment]
@anxdpanic From their privacy disclosure and currently available information without digging into source code, that plugin also seems to require API key, isn't it?
