### ISSUE TITLE
Video lists no longer show duration next to the file name (after upgrade to Kodi 20)

### ISSUE THREAD

**Issue by thefoster** [anxdpanic/plugin.video.youtube#430]
After upgrading to Kodi 20 (LibreElec 11) from latest Kodi 19, all list views no longer show the playtime/duration of the videos.
This applies in my favorite skn "HorizonV" as well as in the default "Estuary".

* Add-on Version: 7.0.0
* Kodi Version: Kodi-20.0
* Kodi GUI Language: german (same issue when set to english)
* Operating System: LibreElec 11
* Operating System Language: $LANG=C.UTF-8, $LANGUAGE not set
------
### Expected Behavior
One of the listview options should show the videos duration in the list.
------
### Current Behavior
Just the video names are currently shown in the lists (ViewID 50)
The default view with "STANDARD" sorting in the list view previously (on Kodi 19) showed the video's duration.
------
### Steps to Reproduce
1. Open YT plugin, 
2. select "my subscriptions" or any other list with videos
3. try the different list view options
------
### Log
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10948593/kodi.log)
------

### Additional Information
Display of a video's duration is very helpful to decide to watch it now (e.g. 5min) or later (e.g. 45min). 
------

**Comment by BmdOnline** [comment]
I can confirm the behavior, using LibreElec 11 or using ArchLinux `kodi-20.0-7-x86_64.pkg.tar.zst`.
Rolled back to `kodi-19.4-8-x86_64.pkg.tar.zst`, video's duration is back again.

**Comment by thefoster** [comment]
The only thing i found so far was that one dependancy (script.module.pysocks v1.7.0+matrix.1) of the YT-plugin was not installed after upgrading to LibreElec 11, but installing it manually that didn't solve the issue.
As i don't see any benefit in Kodi 20 right now i ihink i'm gonna switch back to Kodi 19. 
Luckily, i upgraded to a larger sd card right before, so it is just about inserting the old card.

**Comment by crwolff** [comment]
There appears to be two issues here.
1) This plugin doesn't always get the duration, and issue seems to be worse on Nexus than Matrix, but that may just be a continuation of the trend. I suspect G* changing the API, but have no proof.

2) In Estuary (and I assume other skins) Window.IsActive(videoplaylist) isn't true. This results in the empty $INFO[ListItem.Label2] being displayed. I don't know if this is a Nexus or Plugin issue, but you can patch around this in Estuary by changing Label2 to Duration in line 93: 

```
*** skin.estuary/xml/Variables.xml.orig	2013-05-12 02:41:54.000000000 -0600
--- skin.estuary/xml/Variables.xml	2023-03-04 13:48:13.794267716 -0700
***************
*** 90,96 ****
  		<value condition="Container.SortMethod(7) | Container.SortMethod(29)">$INFO[ListItem.Year]</value>
  		<value condition="!String.isempty(ListItem.Appearances)">$LOCALIZE[38026]: $INFO[ListItem.Appearances]</value>
  		<value condition="Window.IsActive(musicplaylist) | Window.IsActive(videoplaylist)">$INFO[ListItem.Duration]</value>
! 		<value>$INFO[ListItem.Label2]</value>
  	</variable>
  	<variable name="PlotTextBoxVar">
  		<value condition="!String.IsEmpty(ListItem.PlotOutline)">$INFO[ListItem.PlotOutline]</value>
--- 90,96 ----
  		<value condition="Container.SortMethod(7) | Container.SortMethod(29)">$INFO[ListItem.Year]</value>
  		<value condition="!String.isempty(ListItem.Appearances)">$LOCALIZE[38026]: $INFO[ListItem.Appearances]</value>
  		<value condition="Window.IsActive(musicplaylist) | Window.IsActive(videoplaylist)">$INFO[ListItem.Duration]</value>
! 		<value>$INFO[ListItem.Duration]</value>
  	</variable>
  	<variable name="PlotTextBoxVar">
  		<value condition="!String.IsEmpty(ListItem.PlotOutline)">$INFO[ListItem.PlotOutline]</value>
```

**Comment by BmdOnline** [comment]
Workaround is working. Thanks. 👍 

What about providing Label2 directly from the addon, containing duration ?
Is it a possible solution ?

**Comment by XxAcielxX** [comment]
I'm also having the same issue. The video information is shown after playing the video, not before.

**Comment by crwolff** [comment]
In resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py there is a curious bit of code (in two places):
```
        # This should work for all versions of XBMC/KODI.
        if 'duration' in _info_labels:
            duration = _info_labels['duration']
            del _info_labels['duration']
            info_tag.add_stream_info('video', {'duration': duration})
```
Commenting it out (# at the beginning of each line) brings back all the durations in their former glory. Since the plugin only supports Nexus moving forward, perhaps deleting this code is the right choice?

Note, I think this works without patching the skin (see my comment above), but I'm using that patch also since it shows the duration of random movie files instead of the sizes.

**Comment by kedarz** [comment]
> 

Nice tip. It's working very well. Thanks

**Comment by XxAcielxX** [comment]
>         # This should work for all versions of XBMC/KODI.
>         if 'duration' in _info_labels:
>             duration = _info_labels['duration']
>             del _info_labels['duration']
>             info_tag.add_stream_info('video', {'duration': duration})
I confirm. Commenting out the lines makes the Duration come back in the View.

These are lines 140-143, incase someone ask.

**Comment by BmdOnline** [comment]
> Note, I think this works without patching the skin (see my comment above), but I'm using that patch also since it shows the duration of random movie files instead of the sizes.

Hi.
I confirm it works, even without patching the skin.
I have commented out both places : lines 88-91 and 140-143.

Thanks.

**Comment by anxdpanic** [comment]
fixed and new version pushed. just needed to delete
```
del _info_labels['duration']
```

**Comment by thefoster** [comment]
Thank you

**Comment by viper-666** [comment]
I have this problem since yesterday. It appears while using the plugin after a few videos.
Is there a way that I have pressed a wrong button on the remote control to hide the duration in the video list?

**Comment by MoojMidge** [comment]
[This comment](https://github.com/anxdpanic/plugin.video.youtube/issues/430#issuecomment-1464963608) partially identified the problem, however the issue goes quite a bit further than that.

The identified fix (to ensure that the duration info was actually set and not discarded), only works as long as Kodi respects the content type that the plugin sets for the virtual directory listing, and in some instances it seems to ignore or lose this information.

When a video is played Kodi will automatically refresh directory listings to ensure things like resume point, watched status, etc. are properly updated. This plugin can also be configured to refresh after watching (`Settings > General > Refresh after watching`) and a combination of both these actions, along with the functionality that Kodi has to cache virtual directory listings, causes the problem, although I haven't been able to identify exactly where the race conditions occurs (the process is too complicated for me to follow by just casually reading the code, would need to get a debug build and step through to investigate further). It also sometimes results in Kodi losing the entire window history, which is why sometimes the root video directory listing ends up being displayed after playback stops.

Unfortunately the Kodi behaviour to automatically refresh directory listings cannot be configured. It was a bit of a hack to workaround other more fundamental issues, but in turn causes yet other problems including this one. I guess on balance it was thought that it was the best (simplest?) method to resolve those original issues.

In any case, recent plugin updates have somewhat worked around the issue by forcing specific content and formatting for `Label2` so you shouldn't see this specific problem anymore once the updates are released.

**Comment by viper-666** [comment]
@MoojMidge  Thank you very much for your detailed answer. That's exactly what happened. I watched a video from a creator and after the end all videos in the list where without duration.
Also after a few restarts this error is present. 
I will test the workaround you linked to.

**Comment by viper-666** [comment]
Ok, I don't manage to get the workaround in the skin aeon nox silvo to work. 
But as soon as I changed to the skin confluence the duration appears. But only in this skin, after changing back to aeon nox the duration wasn't there.
So as long as there is no solution I will go with the confluence skin. But what I really like in the aeon nox skin is that you can configure the links in the homesreen how you want.

**Comment by MoojMidge** [comment]
The workarounds discussed above may or may not work correctly for different skins, and will  prevent new features added to this plugin from working correctly.

The plugin itself has recently been updated to avoid this problem, just need to wait for an official release to be made available. Once the update is available, it should work regardless of what skin you use.
