### ISSUE TITLE
Support YouTube clip

### ISSUE THREAD

**Issue by regseb** [anxdpanic/plugin.video.youtube#450]
### What Problem Does This Solve? 

I'm developing the [Cast Kodi](https://github.com/regseb/castkodi) WebExtension and I would like to send a YouTube clip (e.g. https://www.youtube.com/clip/UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz) to the _plugin.video.youtube_.

This plugin could support the URLs: `plugin://plugin.video.youtube/play/?clip_id=UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz`

**Comment by neo-neo1** [comment]
Your best bet to make a PR

**Comment by MoojMidge** [comment]
@regseb - what is the logic you use to determine the plugin url to send to Kodi?

For example in the hypothetical situation that clips were supported is there a reason you would use something like
`plugin://plugin.video.youtube/play/?clip_id=UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz`
rather than
`plugin://plugin.video.youtube/uri2addon/?uri=https://www.youtube.com/clip/UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz`

Are you fetching any video details to parse video data or anything like that?

The reason I ask is that a Youtube clip is not actually a seperate video, but rather a wrapper around a larger video, and there is no way to use the Youtube API to get details of the clip. Instead the video_id and start/end times need to be scraped from the clip HTML.

If this were to be implemented in the Youtube plugin then those details would need to be provided by Cast Kodi, which should be straightforward since it is a web extension and already has access to the clip page.

The Youtube plugin can do this as well, but it is more complicated. Perhaps two methods could be used:

When the plugin does the scraping:
`plugin://plugin.video.youtube/uri2addon/?uri=https://www.youtube.com/clip/UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz`

Or when the clip details are provided, to avoid the additional requests and scraping:
`plugin://plugin.video.youtube/play/?video_id=5C85S-RBm_I&start=18025.741&end=18040.741&clip=true`

`video_id` can be found by looking for the following type of meta element in the clip page`<meta property="og:video:url" content="[original_video_url_with_video_id_as_v_query_param]">`

`start` and `end` can be found from the following (note I am not that familiar with modern Javascript or JSONPath so not sure if this is valid, but you should be able to get the idea):
```
ytInitialData.engagementPanels[?(@.panelIdentifier == "engagement-panel-clip-view")].engagementPanelSectionListRenderer.header.engagementPanelTitleHeaderRenderer.visibilityButton.buttonRenderer.command.commandExecutorCommand.commands[?(@.openPopupAction)].openPopupAction.popup.notificationActionRenderer.actionButton.buttonRenderer.command.commandExecutorCommand.commands[?(@.loopCommand)].loopCommand
```
which contains the following object:
```
{
    "loop": true,
    "startTimeMs": "18025741",
    "endTimeMs": "18040741",
    "postId": "UgkxI0KsdOZA-Pq3tUjucaib8b1tbixLMXhz"
}
```
`start` can be calculated from `startTimeMs` divided by 1000, same for `end` and `endTimeMs`

`clip` is set to `true` if the `uri2addon` route is used and continuously loops the video between the `start` and `end` times. If `clip` is not `true` then the clip will only play once, then stop.

**Comment by regseb** [comment]
The user provides a URL to the Cast Kodi extension. For the [YouTube scraper](https://github.com/regseb/castkodi/blob/main/src/core/scraper/youtube.js), I only use the URL information:

- `youtube.com/watch?v=foo` : `/watch` and `?v` ⇒ video
- `youtube.com/watch?list=foo` : `/watch` and `?list` ⇒ playlist
- `youtube.com/playlist?list=foo`: `/playlist` ⇒ playlist
- `youtube.com/embed/foo`: `/embed` ⇒ video
- ...

For other scrapers, I search in the HTML and/or call APIs. So I can retrieve information from the YouTube clip in its page.

I suggested `plugin://plugin.video.youtube/play/?clip_id=foo` because I didn't know the `uri2addon` route and because there are already routes for `plugin.video.youtube/play/?video_id=foo` and `plugin.video.youtube/play/?playlist_id=foo`

The `plugin://plugin.video.youtube/play/?video_id=foo&start=12.345&end=67.890&clip=true` route is a good one. It will also allow you to start a video at a specified time. For example, for `https://www.youtube.com/watch?v=foo&t=42s` ⇒ `plugin://plugin.video.youtube/play/?video_id=foo&start=42`

**Comment by MoojMidge** [comment]
Just a note - the `t` query parameter from the original Youtube url will be supported when using the `uri2addon` route, and will be converted to a `seek` query parameter.

The `seek` query parameter has been available for a while but previously could interfere with the internal Kodi video resume functionality.

The distinction between `start` and `seek` will be that the `start` time will always be used, while the `seek` time will only be used if Kodi does not try to resume a video.
