### ISSUE TITLE
No Streams found youtube music and major buffering issues

### ISSUE THREAD

**Issue by gsg2016** [anxdpanic/plugin.video.youtube#454]
### Context

Please provide any relevant information about your setup

* Add-on Version:7.0.2-alpha4
* Kodi Version:20.1
* Kodi GUI Language: Eng
* Operating System: libreelec
* Operating System Language:Eng

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

Youtube music not working now "no Streams Found"
youtube buffers badly

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. youtube music and Kore app on android phone - Share - Play on kodi 
2. same for youtube
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
http://ix.io/4umI

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by XxAcielxX** [comment]
Same is happening with me too. Started yesterday with the buffering issue where after the video is played for like 25-30secs, it would get stuck with audio getting stuck as well in a 1sec loop over and over.

Today it started with the same thing, and now this `no Streams found`.

**Comment by damnms** [comment]
same here, this is a bug introduced in the latest dev version, because the stable version works but... have to start a stream maybe 10 times until it really starts playing.

**Comment by HeresJonny** [comment]
Fix for "not available" and buffering issue posted here:
https://forum.kodi.tv/showthread.php?tid=356934&pid=3151213#pid3151213

BUT you will have to disable MPEG-Dash AND might experience some audio dropouts and hangs on Kodi exit. Also videos will most likely be limited to 720p.

**Comment by damnms** [comment]
the "not available" has absolutely nothing to do with this error here (stream not found)
if u want a working version, i would recommend going with the latest dev-version -1, which is this one:
https://github.com/anxdpanic/plugin.video.youtube/archive/d4c53b5ebd92466cb4514e9ce3754fd7f7bba7f7.zip
works like a charm on my htpc

**Comment by gsg2016** [comment]
Thanks damnms Brilliant! 
Everthing working as normal

**Comment by Icetech6** [comment]
> the "not available" has absolutely nothing to do with this error here (stream not found) if u want a working version, i would recommend going with the latest dev-version -1, which is this one: https://github.com/anxdpanic/plugin.video.youtube/archive/d4c53b5ebd92466cb4514e9ce3754fd7f7bba7f7.zip works like a charm on my htpc

No idea what made this version special but thanks for the link. it appears to be working perfectly :)

**Comment by damnms** [comment]
what i noticed is that this version also requires dash disabled, otherwise there are some stutterings after about 50 seconds

**Comment by whatsuprob** [comment]
Any ideas on how to get this fix for Kodi Leia Users? (The update is only available for python 3.0 or Kodi Nexus and above)

**Comment by whatsuprob** [comment]
Thank you for everything you do anxdpanic... I have a quick request that may help all Kodi 18 users...I cannot figure out how to dm on here so I will just put it here. Sorry. For Kodi 18 users only...
Replace the 86.8.25 version of Youtube you have right now for Kodi 18 users with the 6.8.25.  Your 6.8.25 version fixes both youtube music and youtube videos on Kodi 18 (whereas the 86.8.25 fixes youtube videos). I appreciate you pushing the version number up to 86 for Kodi 18 users. Could you continue this and just push it up to version 86.8.26 for example so it gets pushed out to everyone still rocking Kodi 18?  You have no idea how much appreciate all your work and your foresight to push the version # up to 86 (because others have released 7.0x alpha versions that only work on Kodi 19+. I know how easy it would be to just tell me, you are done supporting Kodi 18, and for me to update my Kodi and rinse your hands of me. I know. It's just not an option right now for my folks. They rely heavily on super favourites and a few other addons that are just not working as well for them on Kodi 19. Thank you again!
