### ISSUE TITLE
Client ID truncated

### ISSUE THREAD

**Issue by ModMike** [anxdpanic/plugin.video.youtube#481]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.01
* Kodi Version: 20.1 Nexus
* Kodi GUI Language:
* Operating System: Fire Tv Cube latest gen
* Operating System Language: Android

------

### Expected Behavior

Entered client ID via copy paste

------

### Current Behavior

Client ID is too long for field and gets truncated.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Copy Client ID from Google Dev console
2. Paste ID into Client ID field in YouTube settings

**Comment by ThubLives** [comment]
If your Client ID is only missing the ".apps.googleusercontent.com" portion at the end, that's by design.  That portion needs to be removed anyway for the API to work correctly.

However, I would argue that maybe the string should be modified by the plugin only at runtime and the setting should remain as whatever the user put there to avoid this confusion.  At the very least, the help text should mention this.  It was always a source of confusion, even when the user was expected to remove this portion manually.

**Comment by ModMike** [comment]
I just tried it again and I noticed it doesn't just remove the ".apps.googleusercontent.com" portion at the end, it all removed 3 characters before that which is what was causing my issues.

Once I removed it manually and pasted result into the field, it worked perfectly. Thanks for the help and maybe update the instructions.
