### ISSUE TITLE
Incorrect position of auto-generated subtitles

### ISSUE THREAD

**Issue by SunderB** [anxdpanic/plugin.video.youtube#489]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.1
* Kodi GUI Language: English 
* Operating System: OSMC 2023-05.1 (beta)
* Operating System Language: English
* Hardware: Raspberry Pi 4

------

### Expected Behavior

Please describe the behavior you are expecting.

Auto-generated subtitles should be positioned near the bottom, somewhere near the centre.

------

### Current Behavior

What is the current behavior?

The subtitles are positioned to the very left. On the YouTube website, these appear in the centre.
This does not seem to be an issue with subtitles that aren't auto generated. Other content with subtitles works fine.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open the YouTube addon and log in
2. Enable the subtitle selection popup
3. Select a video with automatically generated subtitles and select them

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

See https://paste.kodi.tv/alobabuvud

------

### Additional Information

Please provide any additional information that may be helpful.

I can provide screenshots if that would be useful.

------

**Comment by MoojMidge** [comment]
The subtitles are formatted to appear left aligned and are being correctly displayed in Kodi 20+

In previous Kodi versions the formatting was ignored.

If you want them to display the same way as other subtitles, then you need to set Kodi to override the subtitle position in your subtitle settings.

**Comment by bitbooster** [comment]
I experience the same issue (on a Vero 4k+ with OSMC 2023-07.1, skin is Aeon Nox: Silvo).
The YT subtitles not only start at the left edge of the screen, but they wrap to the next line already in the middle of the screen (TV screen is at 1920x1080@60 mode, with subtitle font 42, subs position 'bottom of screen'))

**Comment by MoojMidge** [comment]
The reason for this, and a way to change the displayed position has been explained in the initial response.

If the subtitle line is long and the font size is large, then it will wrap, otherwise part of the subtitles will not be displayed.

If the wrapping is not working correctly, will need an example video with timestamp and screenshot to show the problem.

Regardless though, the plugin does not control how subtitles are displayed, that is dependent on how you configure Kodi

**Comment by jmbreuer** [comment]
Just want to mention this here, I was also struggling with how/where Kodi displays those modern-style YouTube subtitles.

I've put together a [trivial patch](https://github.com/jmbreuer/plugin.video.youtube/commit/4715ef3a4004aa388da4715661d804f7c3a37a22) that makes things "work good'nuff for me", with the caveats that I'm aware of listed in the commit message.

**Comment by MoojMidge** [comment]
I am planning on adding subtitles to the MPEG-DASH manifest so that they can be switched on the fly using the Kodi subtitle selection dialog, in the same manner as the audio and video streams can now be switched, and similar to how the subtitles can be switched in official clients.

Not planning on removing the ability to pre-download a single subtitle file, but the existing Kodi settings will work regardless of whether the subtitle is downloaded or not.

`Kodi Settings > Player > Subtitles > Override subtitles styles > Position`

**Comment by jetfir3** [comment]
While searching for this exact "issue" after updating to both the latest v3 beta + Nexus, and now reading the explanation of why the left offset is happened.. I'm also noticing that some videos with auto-generated subtitles display the entire subtitle track at the beginning of the video, overlaying the entire screen.

Each video with auto-generated subtitles appears to have 2 subtitle tracks -- sometimes it's track 1 which displays the entire videos worth of subtitles immediately, but sometimes it's track 2. Since I've updated to both Nexus and the latest v3 beta at the same time, I'm not sure if this is a byproduct of Nexus (like how it now respects the left offset formatting) or something with the add-on itself. I never experienced this while on Matrix + 6.x add-on builds (I only updated today due to the following issue, https://github.com/anxdpanic/plugin.video.youtube/issues/582). 

In addition to this, when it does happen and the screen is filled by an entire videos worth of subtitles, the video gets a bit jumpy (perhaps due to my box hardware?) and the video skips ahead a bit -- afterwards, the add-on sometimes fails to load subtitles in future played videos -- until I exit kodi from the power menu and re-open. 

Anyone else experiencing this? I can provide video examples and logs (or even open up a new Issue) if needed... but as this issue still falls under "subtitle positioning" I figured I'd start here.

**Comment by MoojMidge** [comment]
> I'm not sure if this is a byproduct of Nexus (like how it now respects the left offset formatting) or something with the add-on itself.

Neither, it is an error with the subtitles that are provided by Youtube

> In addition to this, when it does happen and the screen is filled by an entire videos worth of subtitles, the video gets a bit jumpy (perhaps due to my box hardware?) and the video skips ahead a bit

https://github.com/xbmc/xbmc/issues/21554

> Each video with auto-generated subtitles appears to have 2 subtitle tracks -- sometimes it's track 1 which displays the entire videos worth of subtitles immediately, but sometimes it's track 2.

> afterwards, the add-on sometimes fails to load subtitles in future played videos -- until I exit kodi from the power menu and re-open.

I haven't seen this happen before. Please create a new issue with a log for this.

**Comment by jetfir3** [comment]
> 
> I haven't seen this happen before. Please create a new issue with a log for this.

Just wanted to update that I've been able to track my issue down to the following setting in settings.xml:
`<setting id="kodion.subtitle.languages.num" default="true">2</setting>`

This was apparently my subtitle settings value while on Matrix + 6.x addon. 

Looking through the repo, that value seems tied to `LANG_CURR_FALLBACK`. You had replied earlier in this thread mentioning that previous Kodi versions were ignoring the formatting... 
perhaps this additional track which prints the entire subtitle track all at once is also related and never appeared on older Kodi builds?

On Nexus + latest v3 beta, with `kodion.subtitle.languages.num` set to `2` and `kodion.subtitle.download` set to `true` -- when only auto-generated subs are available for the video... 2 subtitle tracks will be available (at least when dealing with English). The first track will load -- depending on the video, track 1 could be this "wall of text" track or it could be the normal timed track which shows subtitles properly timed to the audio of the video. Whether it was track 1 or 2 did not appear to be consistent across different videos.

Example video: https://www.youtube.com/watch?v=zDriLtbazwQ
with `kodion.subtitle.languages.num` set to `2` and `kodion.subtitle.download` set to `true`... the video starts with a wall of text as track 1 gives this behavior.. switching to track 2 corrects it. 

Despite this "weirdness", I assume the addon is correctly handling what youtube is providing... 2 different subtitle tracks when `LANG_CURR_FALLBACK`... but went unnoticed pre-Nexus (at least to me). 

---

This leads me to my next discovery -- the usage of the `configure subtitles` option in settings was NOT changing my subtitle-related values in `settings.xml`, something I did not catch at first... which was adding to my confusion while initially running into the wall of text subtitle issue. Manually editing the subtitle-related values in `settings.xml` finally got things going... trying various combos and eventually setting `kodion.subtitle.languages.num` set to `3`. This is with the current v3 addon + Nexus 20.4 for Android on a CCwGTV box. I also had some weirdness with signing in and running the setup wizard, with some things not sticking... sometimes sticking after attempting them multiple times and other times (like with config'n subtitles) never working. This happened with a fresh Nexus install as well as with prior app/userdata. As some did "stick" sometimes, this would appear not to be permission related. This issue may require its own Issue thread with some logs which I could provide when I get some time to go though all that again -- if wanted. 

--- 

As for the issue I previously mentioned where once the wall of subtitle text appeared it would sometimes not load subtitles in future videos until Kodi was quit then re-opened... this was not an accurate description. After further testing and figuring out how to stop the wall of text by setting `kodion.subtitle.languages.num` set to `3` instead of `2`... I noticed that some videos would still "randomly" not load the subtitles despite the subtitles being toggled on while viewing the videos current subtitle settings. Exiting the video and restarting the video would correct this -- subtitles would load again. I had compared logs between when this happens and when it doesn't and there were no visible differences. 


Just wanted to share all this in case someone happens to run into same problem and ends up searching through these issues.

**Comment by MoojMidge** [comment]
Don't need to delve too deeply into this. I am aware of the issues, and as I mentioned will be changing the way the subtitles are handled, which will address some of those issues.

> On Nexus + latest v3 beta, with `kodion.subtitle.languages.num` set to `2` and `kodion.subtitle.download` set to `true` -- when only auto-generated subs are available for the video... 2 subtitle tracks will be available (at least when dealing with English).

This setting value means use whatever the current set language is, with fallbacks to English (en, en-US, en-GB) for subtitles and including auto-generated subtitles. This will mean there will usually be multiple subtitles available, even if they are only in English.

> trying various combos and eventually setting kodion.subtitle.languages.num set to 3

This is the same as 2, except excluding auto-generated subtitles, so where you may typically have seen two subtitles (en/en-US/en-GB + auto generated en), now only the first one will be downloaded if it exists.

> Despite this "weirdness", I assume the addon is correctly handling what youtube is providing... 2 different subtitle tracks when `LANG_CURR_FALLBACK`... but went unnoticed pre-Nexus (at least to me).

Yes, this was the same pre-Nexus. The issue is with the file generated by Youtube, sometimes the entire text content is included in the first cue point. There doesn't seem to be any reason for it, just happens randomly.


> This leads me to my next discovery -- the usage of the `configure subtitles` option in settings was NOT changing my subtitle-related values in `settings.xml`
...
This issue may require its own Issue thread with some logs which I could provide when I get some time to go though all that again -- if wanted.

Don't have the same issue. Create a new issue with logs, and I can have a look.

> Exiting the video and restarting the video would correct this -- subtitles would load again. I had compared logs between when this happens and when it doesn't and there were no visible differences.

I know there is a problem with the plugin sometimes not properly detecting the directory where the subtitles are downloaded too, which may explain this. Would need a debug log to confirm.

**Comment by MoojMidge** [comment]
The next beta will add a subtitle option to be able to switch between all available subtitles using the Kodi subtitle selection dialog.

It also switches to using ttml subs when this option is enabled. The good news is that these subs are not left aligned. The bad news is that these subs can be 2 line rolling subs, which is not displayed by libass (as used by Kodi) in a similar way to how it was presumably actually intended to displayed.

The end result is that new subtitle lines appear above old lines, rather than the old line moving up and the new line appearing below the old line. This makes it pretty difficult to read, but is apparently the desired behaviour of libass when converting these type of subs without explicitly identifying that the sub placement needs to move.

I will eventually change back to using vtt subs for this new subtitle option, which will re-introduce the problem with the subs being left-aligned, but I don't intend to try and fix this - the Kodi settings for overriding subtitle position should be used instead.

Edit: already switched back to vtt subs for next beta

**Comment by jmbreuer** [comment]
> I will eventually change back to using vtt subs for this new subtitle option, which will re-introduce the problem with the subs being left-aligned, but I don't intend to try and fix this - the Kodi settings for overriding subtitle position should be used instead.

Those Kodi settings are global, no? From a users point of view, I'd be looking for a way to have correctly placed BluRay-style subtitles where available, but YouTube subtitles still should 'not suck'. (Without monkeying through settings menus when switching between media types.)

That being said, I'm OK with working on something that meets these requirements myself; though I guess when the subtitles are listed in the manifest it won't be quite as easy as [my existing quick-fix](https://github.com/jmbreuer/plugin.video.youtube/commit/4715ef3a4004aa388da4715661d804f7c3a37a22) any more. But no worries, I'll figure something out.

Maybe `libaas` (or whatever is responsible) could use an enhancement along the lines of an  "render everything staying within the [title safe area](https://en.wikipedia.org/wiki/Safe_area_(television)#Title-safe_area)" flag or something similar.

I personally don't mind the left alignment, it's the subtitles squashed hard to the absolute 0px left edge that bugs me. For one, my display has a protruding frame so its not nice to focus right on the edge; and visible angle from the left is limited by the protrusion. Even head on, my plasma display's protection ("orbiter", shifting the frame around to mitigate burn-in) will sometimes move about half of the first letter out of frame.

**Comment by MoojMidge** [comment]
Unfortunately it is a case of balancing compromises.

Using Kodi to load subtitles means that you can't use ttml subs, and also that the language and track type descriptions in the subtitle selection dialog are not very useful.

Using InputStream.Adaptive means that you can use ttml subs (which aren't left aligned by default), and also that additional details can be provided to Kodi to properly display subtitle details in the selection dialog

Unfortunately InputStream.Adaptive has issues with displaying the auto-generated ttml subs, and also fails to load the correct url for the downloaded subs.

One option may be to allow the http server to also serve the downloaded subs so that they can be pre-processed, but it is a messy solution.

I would prefer to try and get InputStream.Adaptive to properly display the auto-generated ttml subs.
