### ISSUE TITLE
Error when playback

### ISSUE THREAD

**Issue by Gythion** [anxdpanic/plugin.video.youtube#507]
### Context

Please provide any relevant information about your setup

* Add-on Version: Alpha7 7.02
* Kodi Version: 20.2
* Kodi GUI Language: ita
* Operating System: win11
* Operating System Language: ita

------

### Expected Behavior

Please describe the behavior you are expecting.
play a video

------

### Current Behavior

What is the current behavior?
Stop playback in a while

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Channel: "Sky Sport Tennis" - Sinner def Paul - 08/13/23

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://gofile.io/d/Afvvnf

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
You will need to provide a debug log following [these instructions](https://kodi.wiki/view/Log_file/Easy), as requested in the Bug Report template.

The log needs to show you actually trying to play the video, so that the error can be logged. Simply opening and closing Kodi provides little useful information relevant to your issue.

**Comment by Gythion** [comment]
https://is.gd/qRNnXZ

**Comment by MoojMidge** [comment]
Should be fixed in this [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip)
