### ISSUE TITLE
Memory leak associated to Youtube when MPEG-DASH is enabled

### ISSUE THREAD

**Issue by wagnerch** [anxdpanic/plugin.video.youtube#520]
### Context

* Add-on Version: 7.0.1
* Kodi Version: 21.0 alpha 3
* Kodi GUI Language: English
* Operating System: LE 12
* Operating System Language: English

------

### Expected Behavior

No memory leak?

------

### Current Behavior

I have noticed a memory leak in Kodi after 21.0 alpha 2, so not sure if it is related to bug in Kodi, Python, or the plugin.  The behavior that I noticed is every 60 seconds approximately 500 bytes of memory is leaked.

After disabling Youtube add-on, the memory leak stopped.  Upon further investigation it appears to be related to the service that is monitoring the internal httpd service and restarting it.  Disabling MPEG-DASH (which causes the httpd service not to start, and the monitoring to not ping it) also eliminates the memory leak, with MPEG-DASH enabled the memory leak resumes.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Install recent LE12 nightly
2.  Install YouTube plugin, enable MPEG-DASH
3.  Sit and wait.

------

### Log

------

### Additional Information

See forum thread at: https://forum.libreelec.tv/thread/27544-kodi-21-alpha-3-memory-leak/#post183963 which includes a shell script I was using to monitor memory leakage, PSS/Dirty bytes increases every minute when sitting idle.

**Comment by MoojMidge** [comment]
I use Kodi 20 on an Odroid N2 running CoreELEC. It has 4 GB of memory, but current uptime is over 45 days, and previous periods of uptime have been much longer.

While current Kodi idle memory usage is high (~2 GB) a quick test doesn't seem to show any steady increase in memory usage (over a 10 minute idle period memory usage has actually dropped) and I have never experienced any OOM crashes.

Do you see the same thing happening with LE11?

If you shutdown Kodi do you get any kind of log messages on shutdown that mention something like the following or similar?
```
the python script "~\.kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
```

**Comment by wagnerch** [comment]
The issue started after 21.0 alpha 2, but a lot of other components also changed.  LE often bumps dependencies in a development release.  And there is really no indication in the debug log of a resource leakage.  This results in OOM crashes on RPi4, eventually after 2-3 days.

The issue is pretty apparent, when the httpd service is running inside of the YouTube addon.  And it is very apparent the leak is gone when MPEG-DASH is off and the httpd service is not running.  It suggests the problem is probably Kodi-related or Python interpreter related.

I tried retesting the basic behavior of the HTTP service & requests module calling itself in two separate threads using the Python interpreter in LE12, but really no issue there.

Is there any particular Kodi bindings that would be good to test out here?  I guess I can throw together a quick & dirty monitor addon to try and pin it down.

**Comment by MoojMidge** [comment]
I am not too knowledgeable about matters like this, but in my own experience Kodi historically has sometimes had problems with dereferencing members that are imported from C/C++ based Python modules, including its own `xbmc*` modules.

Typically this has happened when subclassing using these modules and creating instances of the subclasses, or referencing instances from these modules as member variables of other classes. This, for some reason, appears to cause discrepencies in the reference counts for the instances, that then prevents the allocated memory being freed as part of the normal Python garbage collection.

There is normally no indication that this has occurred until you close Kodi and you see warnings in the logs like what I posted previously. Can you shutdown Kodi and see if you see anything like this?

That being said I don't really see this happening in the code used for the service monitor loop, so it may be completely irrelevant.

> Is there any particular Kodi bindings that would be good to test out here?

I'm not sure I fully understand your question - can you clarify?

If I were you and was seeing a memory leak in the service monitor loop I would try to cut out as much functionality at each level of the code to see if the problem could be isolated to a specific part of the code.

Maybe first try making the service loop do nothing by changing:

https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/service.py#L73-L88

to be:
```
    while not monitor.abortRequested():
        if monitor.waitForAbort(sleep_time):
            break
```

If that fixes the problem then change the loop back to normal and instead change

https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/utils/http_server.py#L478-L494

so that `is_httpd_live` essentially only performs the GET request using hardcoded values, and see if there is still a memory leak. Specifically just change all of this:
```
    addon_id = 'plugin.video.youtube'
    addon = xbmcaddon.Addon(addon_id)
    address = address if address else addon.getSetting('kodion.http.listen')
    address = '127.0.0.1' if address == '0.0.0.0' else address
    address = address if re.match(r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$', address) else '127.0.0.1'
```
to just be 127.0.0.1, or whatever it is in the addon settings:
```
   address = '127.0.0.1'
```
There was a change to the addon settings code that made it into Omega Alpha 3 that introduced a new shared pointer to the addon instance that previously didn't exist. This is just pure speculation but perhaps this is not being released for some reason.

**Comment by wagnerch** [comment]
Turning off MPEG-DASH effectively reduces the service loop to doing nothing but the basic monitor loop, so I think that is OK.  I was also looking at changes and notices the addon settings change.  What I tested was the minimal I could find to reproduce:

```class MemoryLeakMontior(xbmc.Monitor):
   pass


def run():
   sleep_time = 1
   monitor = MemoryLeakMontior()

   while not monitor.abortRequested():
      xbmc.log(msg="memleak test 6", level=xbmc.LOGDEBUG)
      addon = xbmcaddon.Addon("plugin.video.youtube")
      mpd_proxy_enabled = addon.getSetting('kodion.mpd.videos') == 'true' and addon.getSetting('kodion.video.quality.mpd') == 'true'
#      response = requests.get("http://google.com/generate_204")

      if monitor.waitForAbort(sleep_time):
         break
```

This is the result after just running a few minutes:

```
2023-09-19 07:00:39,2824716,379729,297096,0,null
2023-09-19 07:00:49,2824716,381397,298764,0,null
2023-09-19 07:00:59,2824716,383069,300436,0,null
2023-09-19 07:01:10,2824680,384777,302144,0,null
2023-09-19 07:01:20,2824680,386449,303816,0,null
2023-09-19 07:01:30,2824608,388121,305488,0,null
2023-09-19 07:01:40,2824608,389961,307328,0,null
2023-09-19 07:01:50,2824608,391633,309000,0,null
2023-09-19 07:02:00,2824608,393305,310672,0,null
```

**Comment by MoojMidge** [comment]
Are you able to build an LE12 image yourself? If so, try to do so without the following commit and see if the memory leak still occurs. 

https://github.com/xbmc/xbmc/commit/e0ee04aaa5fcbb85ad987cc96c8d9c0f5b355256

**Comment by wagnerch** [comment]
Yeah, I can.  I'll give that a shot later today.  There were ~4 commits related to addon settings, so I might rollback that whole PR (not sure if there are inter-dependencies).

**Comment by wagnerch** [comment]
It does appear that may be the culprit, updated the issue on the Kodi side.  I'll leave it running idle until lunch and see where it stands.  MPEG-DASH is back on, as normal.

**Comment by wagnerch** [comment]
Looks like xbmc/xbmc#23864 solves this problem.  Thanks.
