### ISSUE TITLE
Live Video Issues

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#530]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2
* Operating System: OSMC

------

### Expected Behavior

Expecting videos that were once livestreams but no longer live to be able to play 1080 using MPEG-DASH settings same as normal videos. Currently live videos that are ongoing play at 1080p, but they time out after a few seconds, Id expect them to continue playing but it almost looks like the bar that measures the time until their end, catches up and it times out?

------

### Current Behavior

Videos that were once livestreams but are now just playbacks only go up to 720p no matter the settings and videos that are currently live tend to often time themselves out after a few seconds of playback. Note that 1080p playback works fine on youtube itself with the same material and it works fine on video that were never hosted as a livestream.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play videos that were once live or are currently live
2. Notice that live videos time out, and videos that were once live but are now playbacks of live videos dont play at full res even though they can on youtube.

------

### Log

Not sure if logs will be useful, I dont think this will show errors per say, will provide if the problem appears to be unreproducible

------

**Comment by MoojMidge** [comment]
For live videos use `Settings > MPEG-DASH > Use for live streams > Adaptive HLS`. MPEG-DASH is currently broken for live videos due to some changes in InputStream.Adaptive

For completed live videos playing at 720p, I am aware of the issue. It was caused by a change in the data returned by the Youtube API. Fix has been identified and will be available in the next release.

**Comment by ghost** [comment]
Im on Adaptive HLS, still getting the issue. Depends on the stream though.

**Comment by MoojMidge** [comment]
Which issue?

**Comment by ghost** [comment]
The issue with live streams timing out still happens on adaptive hls here's the log during it happening, if it helps:

https://pastebin.com/b51KmCbZ

**Comment by MoojMidge** [comment]
Yeah that helps. It looks like the stream is being downloaded and decoded but is not being rendered properly when the next stream segments starts playing.

In your Kodi settings what do you have for `Settings > System > Display > Delay after change of refresh rate`? Can you check if there is any difference between setting it to `Off` and something large, say `10 seconds`.

**Comment by ghost** [comment]
Still found some that would crash. [Log](https://zerobin.net/?3625257f45e54872#Zljp6AEsVpNVGnD5Dpa6j+svyil84dDoh43+GgJ5atg=). The last time I watched the Realed Minecraft live video it crashes with the 10 Second delay on. Was on off on the original log.

**Comment by MoojMidge** [comment]
That is a different issue to what you described before as it appears to be Kodi actually crashing rather than an issue with playback. You would need a stack trace to try and determine why.

The only issue with this plugin is that completed live videos only play at 720p.

The other issues you have mentioned don't have anything specifically to do with this plugin, and if you are seeking help with them I would recommend you raise the issue on the OSMC forums following their troubleshooting guidelines (which would include the process to retrieve the crash log containing the stack trace), as suggested previously.
