### ISSUE TITLE
Youtube Folders All empty randomly for no reason

### ISSUE THREAD

**Issue by I-dont-Care-Just-Let-Me-Post-An-Issue** [anxdpanic/plugin.video.youtube#545]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: Libreelec
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Videos To be visible in Folders

------

### Current Behavior

What is the current behavior?

No videos Visible in Folders

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Turn On
2. Click Youtube
3. Click Folder
4. No video/Playlists Visible

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/osojuqufoz

------

### Additional Information

Please provide any additional information that may be helpful.

Occasionally the issue will pop up after watching videos and the videos will continue to play but nothing more can be played.
nothing shows in search and subscriptions may show but they will not have anything to select except more folders

------

**Comment by MoojMidge** [comment]
I think your playlist is quite large and you are running out of your quota allowance by accessing it too frequently.

Few issues:

1. The access failure is not being properly displayed so you know what is happening
    - This was partially broken by the use of a builtin error handler, so the existing custom error handler can't function properly. ~This needs to be fixed.~ This is fixed for the next release.
2. The retrieval of playlist items is not being cached so you use up your API quota allowance every time you open it
    - ~This functionality needs to be added.~ This has been added for the next release. Playlist items will be cached for 1 hour.
    - Note that caching this playlist needs ~8MB of storage space, so the default max cache size of 10MB (5MB each for the function and data caches) will not be large enough to enable this to work. Change the cache size in `Settings > Advanced > Cache Size (MB)` to something larger
3. The retrieval of playlist items is being done in chunks based on how many items per page you have configured, but for playing a playlist (as opposed to viewing it), the playlist and item details should be retrieved in one go.
    - ~This functionality needs to be added.~ This is a limitation of the Youtube API
4. When the access failure occurs, there are subsequent errors that aren't being handled
    - This is fixed for the next release
5. There are a number of videos in your playlist that can't be played (because they are removed/blocked/private) but the fact that they are not playable is not cached, so the plugin keeps requesting details for them.
    - ~This needs to be fixed.~ This is fixed for the next release.
