### ISSUE TITLE
Playlists folder of channels does not contain playlists

### ISSUE THREAD

**Issue by upbox-org** [anxdpanic/plugin.video.youtube#556]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.3+beta.1
* Kodi Version: 20.3
* Kodi GUI Language: English
* Operating System: CoreELEC
* Operating System Language: English

------

### Expected Behavior

Playlists folder contains the playlists.

------

### Current Behavior

The playlists folder has no playlists and contains a folder called "uploads" with the regular uploads in it.

------

### Steps to Reproduce

1. Go to subscriptions and open any channel.
2. Choose the playlists folder.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

Will add a proper log later if necessary.
Can't right now because I'm not at home.

**Comment by C-O-D** [comment]
The same here and my subscription folder is also affected...

**Comment by MoojMidge** [comment]
Did this work any differently previously?

Nothing has really changed here, and from what I can see it still works anyway. Do you have an example channel where it doesn't show playlists that it should?

**Comment by upbox-org** [comment]
> Did this work any differently previously?
> 
> Nothing has really changed here, and from what I can see it still works anyway. Do you have an example channel where it doesn't show playlists that it should?

Yes, it worked fine before this update.
Unfortunately, it no longer works on **any** channel.

In addition I found that the search results folders "channels" and also "playlists" are empty too.
I made 2 short videos with my phone to make it clear what I mean. 
Sorry for the bad quality tho. 😅

https://youtu.be/NYG1wh_xK18
https://youtu.be/bOOWDOhGX44

**Comment by MoojMidge** [comment]
Hmm... works fine for me. Maybe I have made some local changes that I haven't created a PR for, but I don't recall changing anything with this anyway. Will look a bit closer later in the day, in the meantime can you try clearing the plugin cache and data cache?

Edit: A log will also help

**Comment by C-O-D** [comment]
Hey @MoojMidge,
I can only agree, there are no playlists displayed at all in any channel. Also the menu entry playlists and also saved playlists is empty, but above all the subscriptions, not a single subscription is visible. After I ran the commit acd6e53 locally, 'my subscriptions' at least work to some extent, although the entries there also disappear from time to time, which is why my widgets are then empty. When I go into the addon to my subscriptions, they are there again. I have already increased the cache in the settings as I read in another post that this can be helpful with large playlists - and of course I have already deleted all caches that can be deleted, including the temporary files, but none of this has helped.
I'm really surprised that I don't see more people reporting this problem here. I can maybe wait another day or so, but then unfortunately I'll have to revert to the previous version, which didn't have all these problems, so I won't be available for further reports.
However, I have attached a log for you:
https://paste.kodi.tv/koreyoheyu.kodi

best regards

**Comment by MoojMidge** [comment]
I don't doubt there is a problem, it is just not immediately apparent what it is.

> there are no playlists displayed at all in any channel

This works for me.

> Also the menu entry playlists

Also works for me.

> saved playlists is empty

Did this work previously? I thought this hasn't worked for a while, and had it on my list of things to look at.

> but above all the subscriptions, not a single subscription is visible

Also works for me.

> although the entries there also disappear from time to time, which is why my widgets are then empty. When I go into the addon to my subscriptions, they are there again

Are the issues you are describing only occuring in widgets created with Auto Widget?

> I'm really surprised that I don't see more people reporting this problem here.

Possibly because not many people have tried this beta version, or possibly because the problem is not universally effecting everyone. As I mentioned above, it all works fine for me.

> However, I have attached a log for you:

Thanks for that. Two things immediately jump out here:

- Some of the requests are failing and are being re-tried
- None of the empty lists you are reporting actually appear to be empty. If they were you would see warnings in your log saying "List of search result is empty"

Before you give up on it, can you try https://github.com/MoojMidge/plugin.video.youtube/tree/master and produce another log (a debug log would be even better)? This won't fix anything but it should properly log the failing requests so I can see what is happening.

**Comment by MoojMidge** [comment]
> I made 2 short videos with my phone to make it clear what I mean.

Strange, similar to @C-O-D, the list doesn't appear to be empty, it just isn't being displayed.

**Comment by MoojMidge** [comment]
Oh, there is a bug in the hide short videos option. Just turn that off for the moment.

Edit: Or apply fix manually https://github.com/MoojMidge/plugin.video.youtube/commit/fa323fb402be80aee1c71ef5a4f6a36d60e1dbdd

**Comment by C-O-D** [comment]
Wow @MoojMidge, I applied the fix fa323fb and rebooted and everything works like a charm - thank you so much, what a relief!
And no, the widgets I was talking about are pure skin widgets from Arctic Fuse and yes of course you are right, the saved playlists didn't work before either, my mistake.
Great, now life can go on :-)

**Comment by upbox-org** [comment]
> Oh, there is a bug in the hide short videos option. Just turn that off for the moment.
> 
> Edit: Or apply fix manually [MoojMidge@fa323fb](https://github.com/MoojMidge/plugin.video.youtube/commit/fa323fb402be80aee1c71ef5a4f6a36d60e1dbdd)

Awesome! Thank you!

**Comment by C-O-D** [comment]
Hey @MoojMidge, would a debug log from your fork still be helpful for you, although my problems seem to be solved?

**Comment by MoojMidge** [comment]
@C-O-D - for this particular issue it is not necessary, the log you already provided and the videos from @upbox-ai identified that the lists weren't empty, which was enough to figure out what the problem was.

Your other log did show a request failure, so if you see other listing's fail to load you can try to get a log, but it might be difficult to get a debug log of the problem.
