### ISSUE TITLE
Remove and add items don't work  properly

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#558]
### Context

Please provide any relevant information about your setup

* Add-on Version:  v7.0.3+beta.1
* Kodi Version: 20.3
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN
* Fix ` if not item.playable or not 0 <= item.get_duration() <= 60`
------

Expected Behavior

Remove and add items to own playlist or own watch later list (Login required)

------

Current Behavior

*  Remove of items in playlist and watch later are not possible.
*  If added items to playlist/watch later are not updated automatically, -->Fix for each item: Delete data cache data base in settings.

------

Steps to Reproduce

1.  Fresh installing  v7.0.3+beta.1 in  Kodi Nexus 20.3
2.  Set your API-key and watch later ID
3.  Fix manually ` if not item.playable or not 0 <= item.get_duration() <= 60`
4.  Kodi Restart
5.  Login in YT-Addon

------

Log and screencapture in same time

https://paste.kodi.tv/cojetiyeve.kodi
https://youtu.be/9DL5fFcNbgI

------

**Comment by MoojMidge** [comment]
At the moment playlists are cached for one hour, and there is currently no method to refresh them, except to wait or clear the cache.

A method to update cache entries is planned for the next release.

**Comment by MoojMidge** [comment]
> At the moment playlists are cached for one hour, and there is currently no method to refresh them, except to wait or clear the cache.

In the next beta, the first page of a playlist will only be cached for 5 minutes. This is an interim measure, with the eventual aim being to automatically (if practical) mark a cached playlist as needing an update on modification



> A method to update cache entries is planned for the next release.

In the next beta, the `Refresh` context menu item, will refresh the entire list rather than just reloading it from the cache. Unfortunately there appear to be some Kodi window history bugs that impacts this, so after refreshing and navigating back, you may see the old unrefreshed list rather properly navigating back.
