### ISSUE TITLE
Setting to show "views, comments, likes" of listed videos

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#559]
v7.0.3+beta.1
For cleaner look and more space in own playlists and watch later,  I suggest a setting point selectable by the user with or without  _Show "views, comments, likes" of listed videos"_  , independent to current setting to show in video description.
------
Screenshots: as example in  v7.0.3+beta.1 versus  v7.0.2.2
https://imgur.com/a/8NP4Xa1
vs.
https://imgur.com/a/JUsdowx
------

**Comment by MoojMidge** [comment]
Open to more feedback on this.

I'm not too keen to add more settings unless necessary and also not keen to make the extra info in the main label seperately optional because it doesn't take up any extra space, it simply uses what available space is already available.

Not sure there is much benefit in trying to preserve empty space that may or may not exist - half the list items in your screenshot are already completely filling all the available space, and the display can change quite significantly in different skins, or even different views.

More importantly, from a functuonal perspective, the additional info also changes depending on the sort order, and making it optional limits the usefulness of the other sort options.

What I was considering was seeing whether another sort order could be used, so the extra details on the right hand side, which do take up extra space, can be changed. If another one is available then I can make it mimic the older display.

**Comment by Mo1967** [comment]
@MoojMidge 
if that is possible, can you tell me the file and lines to pound out (#) the feature to show "views, comments, likes" in listed videos, only ?
Thanks for your great work!

**Comment by MoojMidge** [comment]
You can disable the additional info on the left hand side by commenting out this:

https://github.com/anxdpanic/plugin.video.youtube/blob/cfe6f68667faa71916b7657cd19467ff0fcd5d59/resources/lib/youtube_plugin/youtube/helper/utils.py#L493

**Comment by Mo1967** [comment]
@MoojMidge 
which lines are in beta 3 ? Thank you

**Comment by MoojMidge** [comment]
You can search for the same line of code. The line number may change, but the actual content of the line is unlikely to change in the near future.

https://github.com/search?q=repo%3Aanxdpanic%2Fplugin.video.youtube%20video_item.set_code(label_stats)&type=code

**Comment by steph09** [comment]
I've made the change above & it's got rid of the views & likes count in the video title but Is there any way to also stop it displaying the date next to the video length?

**Comment by MoojMidge** [comment]
At this stage, no.

It is possible to change, but not as easy as just removing or commenting out a single line of code.
