### ISSUE TITLE
"My Subscriptions", "Saved Playlists", and "Purchases" folders are empty

### ISSUE THREAD

**Issue by kuraikaze** [anxdpanic/plugin.video.youtube#56]
### Context

* Add-on Version: 6.8.8
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LibreELEC (Linux)
* Operating System Language: English

------

### Expected Behavior

Display of a merged list of new & recent entries from subscribed Youtube channels.

------

### Current Behavior

Folder is empty.

------

### Steps to Reproduce

1. Start plugin and navigate to "My Subscriptions" folder

------

### Log

Debug log: [https://paste.kodi.tv/yedururace.kodi](url)

------

### Additional Information

The subscribed channels' videos can be browsed and played from the Subscriptions/{ChannelName} subfolders normally, so it doesn't seem like a more systemic auth/list problem.

I deleted the function & data caches, cleared temporary files and did the sign-out/sign-in dance just in case, but no luck.

------

**Comment by tankstrr** [comment]
Can confirm I am having the same issue, similar debug log, only difference is running on Win10 (not MS store version)

**Comment by upbox-org** [comment]
Hi, I have the exact same problem.
I've tried deleting cache and temp files. 
Logging in again did not help either. 
I'm not sure if it's still necessary, because kuraikaze has already reported everything in an exemplary way, but here is my info anyway.

Details:
- Add-on Version: 6.8.8 (the unofficial build from test repo)
- Kodi Version: 18.9 (32-bit ARM)
- Kodi GUI Language: English
- Operating System: CoreELEC (Linux)
- Operating System Language: English

Log (debug):
https://paste.kodi.tv/mijiberilo

Greetings

**Comment by MxDevlin** [comment]
Can confirm: this just started happening for me tonight.

Details: 
> Addon version 6.8.8 (latest in repo)
> Kodi version 18.9 (Leia/raspberry pi 3B)
> OS - LibreELEC (Official) (Linux)
> Language: English

**Comment by shawenyao** [comment]
I can confirm the same. Meanwhile, "Saved Playlists" is now showing the same symptom as "My Subscription" (empty), rather than what was described in #55

**Comment by fedprod** [comment]
Dang that sneaking overnight YouTube API changes... bet it's because the new forced ads in every video (although, the videos themself are stil playing correctly... for now... -.-)

**Comment by C-O-D** [comment]
Me2

**Comment by BehnK** [comment]
Same here - I did read somewhere (one of the YouTube dev emails?) that the YouTube API was getting rid of 'My Subscriptions' but didn't think it would effect the add-on

**Comment by iceman20k** [comment]
> Same here - I did read somewhere (one of the YouTube dev emails?) that the YouTube API was getting rid of 'My Subscriptions' but didn't think it would effect the add-on

The "My Subscriptions" maybe was the most useful thing. Wow, if that is true and the reason (and cant be "worked-around") then YouTube is dead for me. At least for viewing long-time videos on TV.
In my country, germany, they started to delete a lot of videos anyway - one may could call that censorship...

Please someone, with time, do a _useful_ LBRY.tv Kodi plugin ;)

**Comment by Sebazzz** [comment]
The home parameter has been deprecated. Looks like this is the only alternative: https://stackoverflow.com/a/23620166/646215

**Comment by anxdpanic** [comment]
This has been expected for quite a while. `My Subscriptions`, `Saved Playlists`, and `Purchases` all use the API that was provided by the leanback interface (https://www.youtube.com/tv), which was discontinued October of last year iirc.

The return values for this API have changed, and don't provide the necessary information anymore. Since it is undocumented, discontinued, and no longer accessible from a public interface; it is unlikely I'll be able to resolve this. Will look into it further.

**Comment by Rialtho-the-Magnificent** [comment]
have the same issue. Uses OSMC on a PI3B+. Couple of weeks it was working as expected, then more and more videos wouldn't run, probably because of unskippable ads (that are not shown, as well as midroll ads do not show on any video that _**does**_ play). Have to resort back to viewing them on desktop in Chrome browser. Luckily I do not see the ads due to my hosts file that I keep up to date via the **_### someonewhocares.org_** website.

**Comment by deadspool** [comment]
Hello,

I've the same issue in  "My Subscription"

Context

    Add-on Version: 6.8.8
    Kodi Version: 18.9
    Kodi GUI Language: French
    Operating System: LibreELEC (Linux)
    Operating System Language: English

**Comment by cooljimy84** [comment]
Just did a fresh install and have this problem as well.
I can use "play on kodi" from my phone, but it was so nice to use kodi to browse my channels. Off to floatplane and hope the people i follow join soon :(

**Comment by C-O-D** [comment]
My beloved app 'NewPipe' is still working - maybe they can join forces?

**Comment by anxdpanic** [comment]
NewPipe isn't an option for us

**Comment by anxdpanic** [comment]
See: https://github.com/anxdpanic/plugin.video.youtube/issues/56#issuecomment-734367728

edit: I've locked this issue, it's reproducible and no additional debug information is required. Wish it was better news.

**Comment by anxdpanic** [comment]
It's not the fastest, but it works for now. https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
