### ISSUE TITLE
 Addon often crashes at startup #561 

### ISSUE THREAD

**Issue by GTP95** [anxdpanic/plugin.video.youtube#562]
### Context

Follow up to issue  #561, the same info as before applies. I now updated all my Python packages using pip. Sometimes the addon opens correctly, some other times it crashes.  

* Add-on Version:
* Kodi Version:
* Kodi GUI Language:
* Operating System:
* Operating System Language:

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to open the YouTube addon
2. If kodi was jsut started, it will open correctly
3. go back
4. try to open the addon again, it will likely fail

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14015608/kodi.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Unfortunately it is the same issue and outside of the scope of this plugin to resolve.

Your Kodi installation is trying to import modules from your system Python installation, and one of those modules (charset_normalizer) is either not up-to-date or has installed a binary wheel using pip which is failing to import a hidden submodule 

The maintainer of that module does not believe it is their responsibility to fix, and I can understand their stance on this issue even if i don't agree, but it is also not something this plugin can resolve.

I believe the Kodi request module is meant to use the chardet module by default, instead of charset_normalizer, but because you have charset_normalizer installed in your system Python installation it is ~trying to use it, in preference to chardet.~ being imported (and failing to import but not raising an ImportError) even if not used.

You can try to uninstall the charset_normalizer module but I'm not sure what unintended effects that will have on your system for (if?) things that actually need it.
```
pip uninstall charset-normalizer
```

Alternatively you can try to re-install the latest version
```
pip install -U --force-reinstall charset-normalizer 
```

Or install the non-optimised/compiled version
```
pip install charset-normalizer --no-binary :all:
```

Again completely unrelated to this plugin, and you can try this at your own risk.

**Comment by MoojMidge** [comment]
This really seems like a bug in charset-normalizer going by the comments in https://github.com/python/cpython/issues/76595#

Solution would be to explicitly import the md__mypyc submodule. Which was already suggested in https://github.com/Ousret/charset_normalizer/issues/253, but not accepted.

Just uninstall it and hope nothing else actually need it. 

Edit: Note as well that you don't need to create a new issue if this, or the previous one was closed. Closing an issue simply identifies that there is no planned/required/possible future action to take within the scope of this plugin, not that your messages will be ignored. Opening a new issue means that relevant information is now split in multiple locations and makes it more difficult to manage things.

**Comment by GTP95** [comment]
Thank you! uninstalling it seems to work for now
