### ISSUE TITLE
Having "adjust display refresh rate" enabled with youtube videos causes random audio/video dropouts

### ISSUE THREAD

**Issue by ilikenwf** [anxdpanic/plugin.video.youtube#565]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3 beta
* Kodi Version:  21.0 beta 2
* Kodi GUI Language: English
* Operating System: Linux
* Operating System Language: English

So I'm not sure if these should be reported to inputstream.adaptive or here, but here goes...

I admit I am using an Arc A380 card which makes the situation more interesting but I don't know that it is the cause of all these issues.

When I have "adjust display refresh rate" enabled, while the resolution change does work, I experience intermittent issues where the picture and audio are lost, then come back, and sometimes it plays normally, and then others it continues to drop out. 

In addition, whenever I play a youtube video, with or without resolution switching turned on, the first second or two of audio is lost. I use passthrough, and have tried without it, and it doesn't help this situation at all.

In my kernel dmesg log, I see these when it happens:

[  146.481918] snd_hda_codec_hdmi hdaudioC2D2: HDMI: audio coding xtype 11 not expected
[  153.094259] snd_hda_codec_hdmi hdaudioC2D2: HDMI: audio coding xtype 11 not expected

In the Kodi log, I see a lot of these:

2024-01-29 01:23:09.883 T:597   warning <general>: ActiveAE - large audio sync error: 580269.240722
2024-01-29 01:23:09.934 T:597   warning <general>: ActiveAE - large audio sync error: 580219.257993
2024-01-29 01:23:09.984 T:597   warning <general>: ActiveAE - large audio sync error: 580169.237388

------

### Expected Behavior

Please describe the behavior you are expecting.

The video should play back without dropping to black without audio, then return.

------

### Current Behavior

What is the current behavior?

See above.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Resolution switching by the player is enabled
2. Play a youtube video
3. Experience pain

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[kodi.zip](https://github.com/anxdpanic/plugin.video.youtube/files/14081183/kodi.zip)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by ilikenwf** [comment]
As an aside, I'm the guy with the youtube specific HDR playback issues, which very well may be my intel arc card...while I doubt that there's much that the plugin has to do with it, in case it does, I thought it worth mentioning...

Are we using the API itself to extract the possible stream URLs or are we doing it similar to how yt-dlp does? I can download the videos via yt-dlp or even use yt-dlp with a simple plugin I/GPT wrote that grabs all possible streams from a given URL using yt-dlp (albeit without sound since I'm not building an MPD manifest...or HLS manifest) and those play back fine...just asking for advice on that particular item.

For the one in question of this issue, it only happens when using the youtube plugin or tubed from what I've seen. Other streams, not so much.

**Comment by ilikenwf** [comment]
I lean toward it maybe being an inputstream.adaptive issue - as I understand it, vp9 can have different sized frames at times (resolution) and I wonder if this is an issue either there, or in my video card's driver - disabling vp9 acceleration in vaapi fixes the HDR issue, but isn't as ideal since I have a fancy vp9 compatible card.

**Comment by MoojMidge** [comment]
I think I might regret this, but anyway...

I have previously mentioned to you that the videos you were trying to play seem to be different after remuxing (appear to have different HDR metadata and different framerates).

I had to figure this out myself because you didn't explain what you were trying do in a simple step-by-step manner, and I had to download the video myself and examine it myself, because you didn't provide any samples or details when requested.

After doing this, and requesting you provide a log and samples for the videos that did work, compared to the ones that didnt, you just didn't bother, but still keep bringing up the same issue regarding VP9 HDR.

With that being said, with respect to this particular issue, the plugin cannot really control actual video playback in Kodi, but it can influence some things that may be not well supported by your hardware in conjunction with the plugins you use.

When you play video using this plugin, it is guessing the exact framerate to be used and providing this information to InputStream.Adaptive/Kodi.

When this guess is incorrect Kodi will adjust the refresh rate to the correct detected framerate, however the original guessed value cannot be changed, so when you use Sponsor Block to skip sections of the video, this process may be repeating itself.

This is just a guess because your log is incomplete and doesn't provide any details of what you claim is happening in the issue report.

> I experience intermittent issues where the picture and audio are lost, then come back, and sometimes it plays normally, and then others it continues to drop out.

Your incomplete log doesn't show anything like this occurring.

> In addition, whenever I play a youtube video, with or without resolution switching turned on, the first second or two of audio is lost. I use passthrough, and have tried without it, and it doesn't help this situation at all.

Your incomplete log doesn't show anything like this occurring.

> The video should play back without dropping to black without audio, then return.

Playback will be interrupted by a display mode change, and Kodi has to resync audio and video playback when this happens. Your expectations here are not reasonable, but maybe there are improvement that could be made in Kodi regarding this.

Given all this I am not too keen to investigate any further, but if you want to start afresh and provide some logs clearly showing the problem then I can have a look. Regarding your VP9/HDR issues, if you actually provide a log and samples where you only change one thing at a time, clearly identify what you have changed, and clearly identify what works or doesn't work, then we might get somewhere.

The other options is you can try playing around with some combination of the followings plugin settings yourself:
`Settings > InputStream Adaptive > Stream features`
- Unselect `Enable VP9 video`
- Select `Disable fractional framerate hinting` (available in https://github.com/MoojMidge/plugin.video.youtube/commit/5ecc11753a72896b3f1c7aed75a8ef490148f424)
- Select `Disable all framerate hinting` (available in https://github.com/MoojMidge/plugin.video.youtube/commit/5ecc11753a72896b3f1c7aed75a8ef490148f424)
