### ISSUE TITLE
Related Videos first page without results in v7.0.3 Beta 2

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#572]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3 Beta 2
* Kodi Version: Nexus 20.3
* Kodi GUI Language: Default
* Operating System: Android
* Operating System Language: Default

------

### Expected Behavior

First page with results to Related Videos of selected item.

------

### Current Behavior

First page without results, in second page everything okay.

------

### Log and sreenshot

https://paste.kodi.tv/eyezibeken.kodi

![020124164418](https://github.com/anxdpanic/plugin.video.youtube/assets/157020721/ebc70885-a951-467a-9b63-af36a7b55cf9)
![020124165005](https://github.com/anxdpanic/plugin.video.youtube/assets/157020721/62e9858a-55b6-4954-ac33-7a4e92b0f7c1)

------

**Comment by Mo1967** [comment]
@MoojMidge 
excellent, first page filled out with [bd13ff4](https://github.com/MoojMidge/plugin.video.youtube/commit/bd13ff433eed268e2fadcc8cd0ce2c8f02cdd7ba)
Thanks for the fast fix

**Comment by MoojMidge** [comment]
This is caused by issues with the Youtube response (may be a bug, may be a deliberate change) and effects all third party clients that utilise the same API endpoint eg https://github.com/TeamNewPipe/NewPipe/issues/10808, https://github.com/FreeTubeApp/FreeTube/issues/4625, https://github.com/iv-org/invidious/issues/4415, etc

Looks those other projects are choosing to follow a similar approach as https://github.com/MoojMidge/plugin.video.youtube/commit/bd13ff433eed268e2fadcc8cd0ce2c8f02cdd7ba I.e. just load the continuation, but that is not a proper fix and will need further work.

In some instances there will be no continuation to load. The only correct way to workaround the issue is to either load the video watch page and get the related videos from there, along with any continuations that can then subsequently be loaded using the V1 API next endpoint, or alternatively get the response for a TV client via the next endpoint but which won't have any continuations.

This was how @RNavega originally did it here in https://github.com/anxdpanic/plugin.video.youtube/issues/508#issuecomment-1704432260, but I was trying to avoid the multiple requests and parsing the video watch page.
