### ISSUE TITLE
Problem with sig in - {'error': 'invalid_client', 'error_description': 'Invalid client type.', 'code': 401}

### ISSUE THREAD

**Issue by Wolvverine** [anxdpanic/plugin.video.youtube#583]
* Add-on Version: 7.0.3+beta.3+unofficial.1
* Kodi Version: Nexus (Kodi-20.2) with Python 3.10.12
* Kodi GUI Language: English
* Operating System: Ubuntu
* Operating System Language: English

Upgrade from 7.0.2.2

Logs:
https://paste.kodi.tv/rucipomaza.kodi

**Comment by daukus** [comment]
Same here, cannot login with same error message.

**Comment by orabidoo** [comment]
It needed new API key and in  Creation of identifiers (OAth client)   select  TV application type

**Comment by MoojMidge** [comment]
> It needed new API key and in Creation of identifiers (OAth client) select TV application type

Yeah thats correct. You technically don't need a new API key, just the client ID and secret, but it doesn't hurt to also create a new project and API key.

To those experiencing this problem, there have been lots of issues opened for this exact same thing, you can search the issues list to get details on how to update your OAuth client details e.g.

https://github.com/anxdpanic/plugin.video.youtube/issues/256
https://github.com/anxdpanic/plugin.video.youtube/issues/259
https://github.com/anxdpanic/plugin.video.youtube/issues/272
https://github.com/anxdpanic/plugin.video.youtube/issues/299
https://github.com/anxdpanic/plugin.video.youtube/issues/325

Previously Google used to allow the login process that this plugin uses to be used for any type of application/client, even though it is only meant for TVs and other limited input devices.

They tightened up on this, so now you need to create the correct type of OAuth client identifiers to be able to login.

The beta version does not currently correctly transfer existing access tokens when updating, which is why you need to login again, and when logging in, if you don't have the correct type of OAuth client identifiers then the login will fail.

**Comment by Wolvverine** [comment]
Is second problem:

https://support.google.com/accounts/answer/6010255?hl=en

**Comment by MoojMidge** [comment]
What is the second problem?

**Comment by Wolvverine** [comment]
Only one application not two is authorized: youtube on TV.

When entering the code for the other one there is a 401 error after entering and selecting the account.

**Comment by MoojMidge** [comment]
The reason for that, and what you need to do to fix it is explained in the previous posts - just create OAuth credentials with "TVs and Limited Input devices" as the application type.

It doesn't have anything to do with logins for less secure apps.

**Comment by Wolvverine** [comment]
@MoojMidge  I deleted old keys APi in google and create all new as previous post says, and now I have this problem, every time continous loging and asks for key.

Deleted Also json files for AP and manager access, temporary and cache.

![image](https://github.com/anxdpanic/plugin.video.youtube/assets/5873929/5d3a3bdc-109f-4f36-b4a9-c3199b19d39d)

https://paste.kodi.tv/qofomuzamo.kodi


I think I find - 

The problem was with updating the old key - through the addon API page plugin it does not enter the new one. And earlier although I entered the new one after the change in the interface - it did not update.

**Comment by MoojMidge** [comment]
The error is telling you that you are trying to use an OAuth Client ID, beginning with "76231" that has been deleted.

You need to use the new client id and secret that you created.

**Comment by syntron** [comment]
I had this problem, too! My solution:

* the api key is not only saved in api_keys.json but also in settings.xml
* after I changed it in both places, the login worked as expected!

Perhaps this should be communicated or only one place should be used and the second (api_key.json) be autocreated?

**Comment by MoojMidge** [comment]
If you are editing files directly then yes you need to clear the settings first. This is mentioned in the wiki: https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys#method-3

**Comment by syntron** [comment]
@MoojMidge Thanks! - I had not found the wiki entry ...

Perhaps it could be added to the wiki that one could just change the data in both files (api_keys and settings)? That way, there is no need to enter things via the kodi interface using the remote or to activate a webserver.

**Comment by MoojMidge** [comment]
Editing the files directly is not recommended at all. If someone makes a mistake when doing so it can cause all addon settings and login details to be wiped.

It is there as option, but deleting any existing values is a trivial task via the normal addon settings UI.

Entering new details can be complicated, but using a keyboard or remote app or the Web server interface from another device will always be the recommended method.
