### ISSUE TITLE
"Trailer" don't works anymore from v7.0.3+beta.2

### ISSUE THREAD

**Issue by Nanomani** [anxdpanic/plugin.video.youtube#598]
### Context

From YT addon v7.0.3+beta.2 button "trailer" in "Video dialog Info" has no effect. no video is launch.
All works fine with v7.0.3+beta.1 and before. But after this version the issue is alway the same.
Tested with the latest version "YT addon v7.0.3"

![2024-02-25_154050](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/ab04f4f8-dd35-4777-b1b0-85b4445129b3)
------

### Expected Behavior

I expect the Youtube video value in $INFO[ListItem.Trailer] to be launched

eg value in nfo file : 
`<trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=14oNcFxiVaQ</trailer>`

------

### Current Behavior

Nothing is launch. Kodi back to home.

------

### Steps to Reproduce

Tested from scratch with Kodi 21 Beta 3 on Windows 11 x64 pro and default skin Estuary all by default.

1.  scrape a movie info with option "trailer" from youtube enable in scraper setting
2. open this movie information 
3. click on button "trailer"

------

### Log

https://paste.kodi.tv/uxerenumor.kodi

------

### Additional Information

------

**Comment by MoojMidge** [comment]
The plugin url format used for those trailers has been deprecated for years and was removed in https://github.com/anxdpanic/plugin.video.youtube/commit/1ce49f0e7a80d9c9f1d8e5291c2ccc85f1de138a

Didn't realise that the official Kodi scrapers still use that format
https://github.com/xbmc/metadata.themoviedb.org.python/blob/master/python/lib/tmdbscraper/tmdb.py#L237

I guess the scraper needs to be updated but that doesn't help with stuff already in the video database.

The `action` parameter is actually being used for other things, which is why I removed this, but I guess this will need to be reverted.

**Comment by Nanomani** [comment]
@MoojMidge 
Indeed it is not so simple...
In any case, thank you for your very quick comprehensive answers.

**Comment by MoojMidge** [comment]
Can you check if https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.3.1 fixes the issue?

**Comment by Nanomani** [comment]
@MoojMidge

all works fine now. 
Thanks you

**Comment by MoojMidge** [comment]
Thanks for testing
