### ISSUE TITLE
7.0.2.2 seems to be broken.

### ISSUE THREAD

**Issue by M-Reimer** [anxdpanic/plugin.video.youtube#616]
### What Problem Does This Solve? 

No video plays anymore and no new version of your Addon is automatically installed.

### Suggest a Solution (optional)

Would really help if you updated what is shipped using the Kodi repo. Manually updating really sucks.

**Comment by m-alice** [comment]
`using android client (logged in)`
this error?

**Comment by simonbuehler** [comment]
Yep the same error popped up here

**Comment by M-Reimer** [comment]
Exactly. Just wondering if it is planned at all to get this updated in the repo? Manual updating is really fiddly. Just decided that I won't watch YouTube this evening and deal with this tomorrow.

**Comment by simonbuehler** [comment]
Updated to latest fixed it! 🚀

**Comment by M-Reimer** [comment]
Nice to know. Would still prefer to just get it offered as an update...

**Comment by karlo2105** [comment]
@M-Reimer
Meanwhile, you can install [Git Browser](https://github.com/azzy9/plugin.git.browser/archive/refs/heads/master.zip) and update Youtube from there.

**Comment by ThubLives** [comment]
@karlo2105 
If only it were that easy.  I think there's been a run on the API key for that plugin and the rate limit has been swamped.  It wants me to wait 3200 seconds before my next search.

**Comment by karlo2105** [comment]
@ThubLives
To generate your own api key you first need your own (free or paid) github account. Log in to github and visit this page: https://github.com/settings/personal-access-tokens/new. You shouldn't require any special permissions so you can keep the default "Public repositories (read-only)" option and give it an expiration date far in the future if you dont want to have to keep regenerating a new one every time it expires. Once you are given the api key, you can plug it into the "Personal Access Token" field in the git browser settings to increase the amount of searches you can do: You can generate api key validity till 12 months.

**Comment by douchebanner** [comment]
updated to v7.0.3.2 but still getting the same error.

**Comment by xyzfre** [comment]
> Updated to latest fixed it! 🚀 

My apologies when you say the latest version are you referring to 7.0.3.2

**Comment by simonbuehler** [comment]
Exactly

**Comment by spukisputnik** [comment]
same here
version 7.0.2.2. no longer played videos.
update to v7.0.3.2 solved the problem.
I also prefer to install from the repository but for now it solves the problem.

thx for that,I can watch videos again

**Comment by douchebanner** [comment]
> updated to v7.0.3.2 but still getting the same error.

am i missing something? why wouldnt it work for me?

**Comment by MoojMidge** [comment]
@douchebanner - without a log your guess is as good as mine.

For everyone else, there is a minor change #617 that will improve this. Can copy the file over the top of the existing one if you are using v7.0.3.2, or make the changes manually if using v7.0.2.2

If you are using v7.0.3.2 then the update is not necessary (one of the backup client requests will still work), but is recommended if you are capable of making the changes.

**Comment by M-Reimer** [comment]
@MoojMidge What about shipping any more up to date version using the Kodi repos? Currently the version, new Kodi users have easy access to, is useless.

**Comment by MoojMidge** [comment]
All in good time, and luckily there are other options in the meantime

https://github.com/anxdpanic/plugin.video.youtube/releases

**Comment by douchebanner** [comment]
> @douchebanner - without a log your guess is as good as mine.

i think this is the relevant portion

2024-03-08 15:08:18.361 T:8060     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3.2) on Nexus (Kodi-20.0) with Python 3.8.15
                                                   Path: /
                                                   Params: {}
2024-03-08 15:08:22.221 T:8060     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3.2) on Nexus (Kodi-20.0) with Python 3.8.15
                                                   Path: /sign/in/
                                                   Params: {'category_label': 'Sign In'}
2024-03-08 15:08:22.321 T:8628     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-03-08 15:08:25.076 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:08:25.076 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-03-08 15:08:35.356 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:08:35.356 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-03-08 15:08:45.596 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:08:45.596 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-03-08 15:08:55.858 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:08:55.858 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-03-08 15:09:06.110 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:09:06.110 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-03-08 15:09:16.627 T:8060     info <general>: Skipped 1 duplicate messages..
2024-03-08 15:09:16.627 T:8060    error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Device/user code request failed (config_type: |YouTube-Kodi| client_id: |76710...|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'invalid_client', 'error_description': 'Invalid client type.', 'code': 401}
2024-03-08 15:09:16.628 T:8060    error <general>: [plugin.video.youtube] LoginException: {'error': 'invalid_client', 'error_description': 'Invalid client type.', 'code': 401}
2024-03-08 15:09:16.628 T:3792    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In
2024-03-08 15:09:16.636 T:8628    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In) failed
2024-03-08 15:09:16.653 T:8060     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3.2) on Nexus (Kodi-20.0) with Python 3.8.15
                                                   Path: /
                                                   Params: {}
2024-03-08 15:09:39.475 T:8628     info <general>: Stopping the application...
2024-03-08 15:09:39.475 T:8628     info <general>: Stopping player
2024-03-08 15:09:39.475 T:8628     info <general>: Storing total System Uptime
2024-03-08 15:09:39.475 T:8628     info <general>: Saving settings
2024-03-08 15:09:39.478 T:8628     info <general>: Saving skin settings
2024-03-08 15:09:39.479 T:8628     info <general>: Stopping all
2024-03-08 15:09:39.479 T:8628     info <general>: ES: Stopping event server
2024-03-08 15:09:39.479 T:8628     info <general>: [WS-Discovery]: terminating
2024-03-08 15:09:39.824 T:6932     info <general>: ES: UDP Event server stopped
2024-03-08 15:09:39.989 T:8628     info <general>: CServiceAddonManager: failed to stop service.xbmc.versioncheck (may have ended)
2024-03-08 15:09:40.020 T:8628     info <general>: Application stopped
2024-03-08 15:09:40.263 T:8628     info <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "directinput"
2024-03-08 15:09:40.263 T:8628     info <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "xinput"
2024-03-08 15:09:40.263 T:8628     info <general>: ADDON: Dll Destroyed - Joystick Support
2024-03-08 15:09:40.264 T:8628     info <general>: unload skin
2024-03-08 15:09:40.287 T:8628     info <general>: Unloaded skin
2024-03-08 15:09:40.320 T:8628     info <general>: unload sections
2024-03-08 15:09:40.327 T:8628     info <general>: Exiting the application...

i already put the keys in api_keys and access_manager
is there a step-by step tutorial to regenerate the api keys?

**Comment by rlKoekie** [comment]
just a "same for me" comment: I also ran into the "using android client (logged in)" failed to play error.
upgrading to v7.0.3.2 solved this for me. Thank you for the update!

(upgrading the crude way: download the plugin.video.youtube-7.0.3.2.zip from the releases page, unpack it. Go to .kodi/addons/ folder (linux), remove the old plugin.video.youtube/ folder, and drop the new one you just unpacked from the zip in the addons/ folder. Restart kodi. For me the icons in the plugin changed, so it was easy to see that the upgrade worked)

**Comment by hpannenb** [comment]
The mentioned upgrade procedure by @rlKoekie worked flawlessly for me. Thanks for this and obviously the plugin version 7.0.3.2. :+1:

**Comment by MoojMidge** [comment]
All - There is no real need to unpack the zip file releases to install, unless you really want to. Kodi supports installing from a zip file directly: https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

@douchebanner - that is an unrelated issue, that has been raised many times before: https://github.com/anxdpanic/plugin.video.youtube/issues/583#issuecomment-1953173154

**Comment by benyamin-codez** [comment]
Looks like this is the root cause:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player

Upgrading directly to v7.0.3.2 worked for me. I had to patch for #529. There is a diff [here](https://github.com/anxdpanic/plugin.video.youtube/issues/529#issuecomment-1986723888) for those affected.

Even under v7.0.3.2 the log still spills:

debug <general>: [plugin.video.youtube] Get |youtube.client.selection|: 0 (int, success)
error <general>: [plugin.video.youtube] Request failed
                                                   Status: 400 - Bad Request
                                                   Stack trace (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 60, in run
                                                       __PLUGIN__.run(provider, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 63, in run
                                                       results = provider.navigate(context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 112, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 289, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 656, in on_play
                                                       return yt_play.play_video(self, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 48, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 214, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 656, in load_stream_infos
                                                       return self._get_video_info()
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1029, in _get_video_info
                                                       result = self.request(
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 118, in request
                                                       stack_trace = format_stack()
debug <general>: [plugin.video.youtube] Retrieved video info for video_id: zUs4ptmpf9k, using android_youtube_tv client (logged in)

...but  then carries on...

**Comment by MoojMidge** [comment]
@benyamin-codez - see https://github.com/anxdpanic/plugin.video.youtube/issues/616#issuecomment-1985094616

The plugin is designed to use a variety of client requests in case some don't work

**Comment by hugalafutro** [comment]
I was able to manually install myself, but I have elderly relatives who absolutely cannot do that.

Any timeframe on when the working version will get to official repo? Not really keen on travelling halfway across the town and then finding myself fixing three hundred thousand unrelated issues for 6 hours.

**Comment by MoojMidge** [comment]
The process has already been underway since v7.0.3.2 was released.

Commenting about it isn't going to make that process go any faster.

Complaining about it, on the other hand, may or may not make it go slower, as it can act to discourage those involved, who are contributing their time and effort for free, from bothering.

Since it doesn’t bother me either way and won't impact on the process to update the official repository, happy to keep discussing it in a respectful manner in this particular issue, as it can be useful/helpful when other users help each other.

It just means I am doing this instead of doing anything constructive with regards to development.

**Comment by xyzfre** [comment]
It takes two minutes to install. People complain too much can never be satisfied. Lol.

**Comment by M-Reimer** [comment]
This really depends. Yes, it is easy if you have Kodi installed on some "regular PC". Just download the ZIP file in a browser and install it into Kodi. But there are people who have something like a Raspberry Pi installed with something like "LibreElec". "Out of the box" it is close to impossible to get something installed from a ZIP file with just the Raspberry running LibreElec on. I tried and failed and I was way too lazy to get my laptop just to get YouTube running. And there are people that just lack the knowledge to do anything at all which is not possible with just the remote control.

I wonder how much work it actually is to get a release into the repo? It's always easy to complain about things but after all most of the stuff, we all use in context with Kodi, is created in someones spare time. Is it possible to "join the team" and help with the tasks that have to be done to get a finished release transferred to the official repo? Then @MoojMidge could focus on releasing on GitHub only and I could take over within whatever timeframe my spare time allows and get this release into the repo? Maybe we could exchange about that directly? Is your mail somewhere in the source files?

In my opinion having a working YouTube Add-on directly in the offical repo is somewhat important. The currently broken version is what people get when first installing Kodi. And their first impression is that YouTube doesn't work.

**Comment by fernandolordan** [comment]
This is not to blame anyone. I really appreciate and thank A LOT the work of Youtube plugin maintainers and Kodi maintainers. They definitely make my life better and I am really aware of it and grateful.

That said, in my opinion a non-working version of a plugin making its way to the official repo and from there to thousands of Kodi setups out there, should definitely be a circumstance to be avoided. Specially when a newer release of the plugin has already addressed the problem.

It is not about the effort of updating the plugin from outside the official repo. The fact is that most users will simply not know how to find the Github plugin repository, locate the newest release, download the zip and use it. Most users will neither know about the existence of the newer working version of the plugin.

And that is nobody's fault. The plugin maintainers do have fixed the problem, and the repo maintainers have its own procedures and timings to release and deploy.

Maybe that last part is the one that could solve a potential lack of synchronism between the latest working release of a plugin and the one in the official repo being automatically deployed to the users. Maybe an exception case or a special attention could be applied to plugins that release often due to frequent breaking changes in external services (as it happens in the Youtube case). Possibly the Kodi repo deployment procedure could include a double-check for a newer non-beta release of that specially-mutant plugins before making its way to the official Kodi repo.

I really do not even know if that is possible. It is just an idea.

P.S.: If this could sound demanding or impolite, that is definitely not the intention. It is just  am a non-english speaker, and I do not know many ways to express the ideas.

Thanks for all the good work. From heart.

**Comment by malversoft** [comment]
This is not to blame anyone. I really appreciate and thank A LOT the work of Youtube plugin maintainers and Kodi maintainers. They definitely make my life better and I am really aware of it and grateful.

That said, in my opinion a non-working version of a plugin making its way to the official repo and from there to thousands of Kodi setups out there, should definitely be a circumstance to be avoided. Specially when a newer release of the plugin has already addressed the problem.

It is not about the effort of updating the plugin from outside the official repo. The fact is that most users will simply not know how to find the Github plugin repository, locate the newest release, download the zip and use it. Most users will neither know about the existence of the newer working version of the plugin.

And that is nobody's fault. The plugin maintainers do have fixed the problem, and the Kodi repo maintainers have its own procedures and timings to release and deploy.

Maybe that last part is the one that could solve a potential lack of synchronism between the latest working release of a plugin and the one in the official repo being automatically deployed to the users. Maybe an exception case or a special attention could be applied to plugins that release often due to frequent breaking changes in external services (as it happens in the Youtube case). Possibly the Kodi repo deployment procedure could include a double-check for a newer non-beta release of that specially-mutant plugins before making its way to the official Kodi repo.

I really do not even know if that is possible. Probably it is impossible to automate. It is just an idea.

P.S.: If this could sound demanding or impolite, that is definitely not the intention. It is just I am a non-english speaker, and I do not know many ways to express the ideas.

Thanks for all the good work. From heart.

**Comment by MoojMidge** [comment]
I don't have any involvement in updating the repository, except for starting the process by creating a release and submitting it for review. I would prefer conversation about timeframes stay here, rather than bothering the people who are involved in reviewing and approving the updates to the repository.

Regardless of the intention, at the end of the day everyone is volunteering their time here, and it is not a productive exercise to question why such a task takes time to be completed. It simply takes the amount of time that the volunteers are willing and capable of volunteering, for the benefit of others.

It is also important to understand that when referring to people who are not capable of updating a plugin manually, the time required to review updates is to ensure that what gets pushed out is safe and meet the standards of Team Kodi, without causing issues for such people or the wider Kodi using public. It is not simply an administrative task that just anyone can do if they have the time for it.

That's not to say that things can't be improved, but as mentioned previously, it will take time. In the meantime there are other options available, even if it does require a bit more effort to update.

**Comment by benyamin-codez** [comment]
@MoojMidge - Thanks for that. I will drop in those #617 mods too. The multi-client approach should prove to be quite reliable. Thanks for all your recent work. I'm enjoying the stats and the new look. 8^D 

@hugalafutro - You might consider creating and hosting your own repo for your relatives. Also host the add-ons you want to manage as specified in the repo's datadir element. Then you just need to update the addons.xml (specified in the info element) and the associated hash file (specified in the checksum element) when you provide an updated add-on. This should automate the updates for your relatives according to the timeframe you require.

**Comment by Doktor-X** [comment]
Since im lazy and I already did have developer repository setup, I installed 7.0.2 alpha7 and this also works

**Comment by bwesen** [comment]
I could not figure out how to add the "developer repository", so I couldn't back down to 7.0.2 alpha7, and after installing the 7.0.3 github Release zip, it fails during Kodi startup with a LONG list of Python errors, for example for ImportJSONError etc.

So, I re-installed the 7.0.2.2 from the official repo, and found the file to patch instead as mentioned further above but writing here exactly what to patch in case someone else has the same problems.

The file to patch is located in .kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py and you need to open that in a text editor and manually do the changes mentioned in the diff here:

https://github.com/anxdpanic/plugin.video.youtube/pull/617/commits/3b83a6619736ac0f9e940e6a70c0f806f06bfaf0

Search for the various edits, and you'll find them, it's 3 places that need to be updated with various Android versions etc.

And if someone has instructions on how to add the dev repo (preferably without using the Kodi GUI as that kind of sucks in this regard I guess) I'd appreciate it :)

**Comment by benyamin-codez** [comment]
@bwesen - The instructions are [here](https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation#repositories).

Option 2, via file manager and whilst the one you don't prefer, allows for automatic updating of the repository.

Option 1 still requires the installation of the repository via the GUI (install from zip) and does not allow for automatic updating of the repository. You manually download the repository zip file to your home directory structure and then install it via the GUI, e.g. on a linux based device, from the console or a SSH session, whilst in your home directory, issue the command (or equivalent): `wget https://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/repositories/repository.tubed_development-1.0.5.zip`, then install it via the GUI.

**Comment by MoojMidge** [comment]
@bwesen - If you are getting an `ImportJSONError` then it means you are running an outdated version of Kodi v21 (Alpha 1 or older) on a Linux system and/or are not keeping up to date with other Python module updates, specifically `script.module.requests`

Jumping through hoops to try and install old versions of this plugin just because you haven't installed other updates is not something I would recommend.

The development repository is not currently up to date. Fixing your system is a better course of action than trying to install it.

@Doktor-X - The reason why the v7.0.2+alpha.7 version works is because it uses, by default, the fallback client that is used in v7.0.3.2. The reason why it is only a fallback client is because various types of videos and features won't work with it, without additional handling that only exists in newer versions. So while basic video playback may work, restricted videos and subtitles, amongst other things, may not.

Save yourself the hassle and just update manually.

**Comment by Doktor-X** [comment]
@MoojMidge i updated to 7.0.3.2 now, only reason why i used dev version is because i wanted to watch videos right now and did not have will to go manual route, but now im up to date

**Comment by bwesen** [comment]
> @bwesen - If you are getting an `ImportJSONError` then it means you are running an outdated version of Kodi v21 (Alpha 1 or older) on a Linux system and/or are not keeping up to date with other Python module updates, specifically `script.module.requests`

Thanks, I'll check this out! My version is a v21 alpha nightlies version but it seems the nightlies ubuntu repo for Kodi had stopped updating half a year ago or something for me so was stuck on that, will get it to work again..

The plugin does say it works on "v20+" of Kodi, so therefore I kind of assumed any Kodi dev version above v20 would be OK for the plugin - but what you say is that the error I got was more of a kodi python environment problem than an actual incompatibility between Kodi and the plugin? So installing the newer Kodi v21 pre-release, would force upgrades of other python stuff on the kodi virtual env, and then that makes it compatible with the plugin?

I guess this dependency problem can't happen when you run the officially released Kodi releases :)

**Comment by Bindou01** [comment]
Cool, thanks for the solution!

By manually installing this version, will automatic updates continue?

**Comment by talos-sail** [comment]
youtube  broken after update CoreELEC 20.4 Nexus to CoreELEC 20.5 Nexus with youtube plugin v7.0.2.2 .
Manual update from youtube plugin v7.0.2.2 to v7.0.3.2 Official ==> All is OK 👍
And don't loose youtube api key !

**Comment by MoojMidge** [comment]
@bwesen - the bug is that Kodi added system Python packages to the `sys.path` of the Python interpreter instances it was running ahead of the Kodi packages, so system packages are used instead of the Kodi packages.

This plugin is compatible with Kodi v19+ (and will also work in Kodi v18 with minor issues), but if you are using specific older versions of Kodi v20 or v21 on Linux with out of date system Python packages then this issue will occur.

@Bindou01 - yes

**Comment by MoojMidge** [comment]
The update has been reviewed and been merged into the official Kodi repository.

It should be available for automatic updates shortly.

**Comment by M-Reimer** [comment]
Sorry for commenting on a closed issue but I want to say thank you for the new release. I love it. So much better than 7.0.2.2.

**Comment by xyzfre** [comment]
> Sorry for commenting on a closed issue but I want to say thank you for the new release. I love it. So much better than 7.0.2.2.

Agreed I use it only for trailers and even that looks and plays amazingly smooth plus the quality looks perfect.

**Comment by MoojMidge** [comment]
Issues get closed for organising/filtering purposes, to identify whether or not there are any outstanding actions that are required. It doesn't mean that you can't continue discussing things in a closed issue - there is no problem in doing so.

Cheers for the positive feedback too.

**Comment by malversoft** [comment]
> Sorry for commenting on a closed issue but I want to say thank you for the new release. I love it. So much better than 7.0.2.2.

I agree and sum my gratitude. By surprise I found fixed the ”related videos” feature, one I use a lot.

With the Youtube side constantly changing, we are all lucky that this project is very alive thanks to its current developer.
