### ISSUE TITLE
Youtube unable to play video

### ISSUE THREAD

**Issue by m1nhx** [anxdpanic/plugin.video.youtube#623]
### Context

Please provide any relevant information about your setup

* Add-on Version: youtube 6.8.25
* Kodi Version: 18.9
* Kodi GUI Language: English (UK)
* Operating System: RPi 4LibreELEC-RPi4.arm-9.2.8
* Operating System Language: English 

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

Youtube signed and videos are unable to play - error "Failed to get player response for video_id"xxxxxxxxxxxxxx"

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. launch Kodi and open Youtube Addon
2.  Click My subscriptions
3. Play video

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Have since deleted API and created you settings, even created new gmail account with new API settings but still get same error, also uninstalled addon, delete cache, et... still not able to resolve this!

------

**Comment by RobinouDuBois** [comment]
Same problème for :
Add-on Version: youtube 6.8.25
Kodi Version: 18.9
Kodi GUI Language: Fr
Operating System: RPI 1 OSMC
Operating System Language: Fr

Thank you for your work, i hope That YT Api will still be compatible with old kodis and raspberry pies.

**Comment by av21389** [comment]
Same issue here:
Add-on Version: youtube 6.8.25
Kodi Version: 18.9
Operating System: LIBREELEC 9.2.8 (RPI 3)

Any workaround to get this working again on Kodi 18.9? I can't update beyond Kodi 18.9.

**Comment by martinrotter** [comment]
Same

**Comment by C0br4** [comment]
Same for me. Started happening 2 days ago

**Comment by germede** [comment]
Same here

**Comment by mchawk777** [comment]
...aaaaand: Same here.

**Comment by martinrotter** [comment]
> ...aaaaand: Same here.

Welcome to the party.

**Comment by seemebreakthis** [comment]
What a relief to know I am not the only one.

**Comment by dumbie** [comment]
You can temporarily fix this issue for add-on version 6.8.25 by editing the following file:
plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py

Open the file in a text editor and edit line 743 from:
'context': {'client': {'clientVersion': '16.49', 'gl': self.region,

to the following:
'context': {'client': {'clientVersion': '19.09.37', 'gl': self.region,

Save the file and restart Kodi and it should work again.

**Comment by germede** [comment]
@dumbie The temporary fix worked! However I had to edit another line (609): 
```python
[...]
    CLIENTS = {
[...]
        'android': {
            '_id': 3,
            'json': {
                'params': 'CgIQBg==',
                'context': {
                    'client': {
                        'clientName': 'ANDROID',
                        'clientVersion': '19.09.37', # changed this
                        'androidSdkVersion': '30',
                        'osName': 'Android',
                        'osVersion': '11',
                        'platform': 'MOBILE',
                    },
                },
            },
[...]
```

**Comment by martinrotter** [comment]
new version should be deployed asap, plugin is broken now

**Comment by MoojMidge** [comment]
Due to time constraints the Kodi 18 version of the plugin is no longer maintained, but users who still use it themselves, are also welcome to keep it updated themselves. 

The latest versions of the plugin may largely work in Kodi 18, with the exception of some buttons not working from the plugin settings, but it is untested and unsupported.

You just need to [update the addon.xml](https://github.com/MoojMidge/plugin.video.youtube/commit/21d13d88c5f8dbee6065bf9a4fe0881ce24ca6cb) appropriately.

**Comment by xyzfre** [comment]
Surprise Kodi 18 still Works why not update to the latest stable version ,even the latest Omega RC1 is working smoothly with the latest version of YouTube 7.0.3.2

**Comment by RobinouDuBois** [comment]
> You can temporarily fix this issue for add-on version 6.8.25 by editing the following file: plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py
> 
> Open the file in a text editor and edit line 743 from: 'context': {'client': {'clientVersion': '16.49', 'gl': self.region,
> 
> to the following: 'context': {'client': {'clientVersion': '19.09.37', 'gl': self.region,
> 
> Save the file and restart Kodi and it should work again.

@dumbie, thank you for your solution. It works for me on OSMC rspi1.
The file to modify on this system is : /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py

It also works on libreelec 9.2.6 on rspi0w
File to modify :
/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py

Thank you again ;)

**Comment by av21389** [comment]
> Surprise Kodi 18 still Works why not update to the latest stable version ,even the latest Omega RC1 is working smoothly with the latest version of YouTube 7.0.3.2

Kodi 19+ introduced changes which mean h265 videos no longer play on RPi 3, while 18.9 plays the same files flawlessly. Generally, 18.9 is the best version for compatibility with older RPi hardware.

**Comment by mchawk777** [comment]
> Due to time constraints the Kodi 18 version of the plugin is no longer maintained, but users who still use it themselves, are also welcome to keep it updated themselves.

Hmmm.... I've got the same Error on Nexus. 🤔
I'll download tonight the actual version on this plugin from github and see if it works.

**Comment by C0br4** [comment]
Issue fixed for me on Matrix.

**Comment by modem2k2** [comment]
Changing the clientVersion string to 19.09.37 in the video_info.py file corrected the problem for me in Coreelec

**Comment by f2hamza** [comment]
> You can temporarily fix this issue for add-on version 6.8.25 by editing the following file: plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py
> 
> Open the file in a text editor and edit line 743 from: 'context': {'client': {'clientVersion': '16.49', 'gl': self.region,
> 
> to the following: 'context': {'client': {'clientVersion': '19.09.37', 'gl': self.region,
> 
> Save the file and restart Kodi and it should work again.

Hey i will appreciate a reply can i do this in ios using ifilza or something cos i can't find this " plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py"

**Comment by musicmagix** [comment]
The suggested fix (clientVersion edit to 19.09.37) didn‘t solve the problem for me. Kodi 18.9 installed on Wemax One Pro Projector, i.e. MIUI TV Version 1.3.105 / Android 6.
Updating kodi or the yt plugin is not an option as 18.9 proved to be the only working Version on this hardware.
I‘d love to help re-enabling the plugin for this exact version of kodi. Can anyone provide me with a link about how to do this?

**Comment by MoojMidge** [comment]
Only changing the version numbers may work for some, but not others. For those who were happily using v6.8.25 you were some of the lucky few who, for whatever reason (perhaps it is region based?), were unaffected by the previous round of YouTube changes. I guess things are catching up now.

Future releases of the plugin will include versions for Kodi v18 (Leia), but only up until such time as it is practical to keep doing so, and with the following conditions:
- No support will be provided. The releases are offered as-is. If there is a problem, replicate it on a supported version (Kodi v19+, soon to be Kodi v20+), otherwise the issue will not be actioned.
- They will not be made available in the official Kodi plugin repository.
- Excessive complaints or requests for support will mean that the releases will stop.
- Releases will only be made available for as long as it doesn't require additional work to produce them. As soon as it does, the releases will stop.

For the following week only, I will respond to issues regarding these releases to ensure that at least basic functionaly works. If you have any issue with these releases, create a new issue and follow the issue template fully. Any missing information (like everyone posting in this issue without a debug log) will mean that the issue will not be actioned.

First release is available here ~https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.2~ for testing.

**Comment by musicmagix** [comment]
I can confirm basic functionality after manual zip install. Thank you very much. 
There is an issue with the "My Subscriptions" folder/playlist. I'll follow up with a proper issue as suggested as soon as I've figured out how to extract the debug log from the projector.

Thank you very much, again, for the time and effort already invested!

**Comment by MoojMidge** [comment]
Updated release now available
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.2

**Comment by mchawk777** [comment]
Short feedback:
Works with actual github-Version. 👍

**Comment by ParkEvans** [comment]
Confirmed that fix (..'clientVersion': '19.09.37'..) works on v16.1 too.
1,000 thanks.
