### ISSUE TITLE
My Subscriptions returning error

### ISSUE THREAD

**Issue by musicmagix** [anxdpanic/plugin.video.youtube#636]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.4+beta.2 (Leia official)
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: MIUI TV 1.3.105 (aka modified Android 6.0.1
* Operating System Language: English

------

### Expected Behavior

When opening the „My Subscriptions“ I should see the latest video releases of my subscriptions.

------

### Current Behavior

Plugin Error. (See log)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. starting Kodi
2. opening the youtube plugin
3. clicking on „my subscriptions“

------

### Log

Please include a complete [debug log] https://paste.kodi.tv/fokufipiku

------

### Additional Information

Turning on debug logging in Kodi caused the plugin to not open at all. Only when deactivating debug logging could I reproduce the aforementioned behaviour.

------

**Comment by musicmagix** [comment]
I managed to have debug log activated while accessing the plugin eventually. Log: https://paste.kodi.tv/unowiliqut

**Comment by MoojMidge** [comment]
Thanks for making the effort to get a debug log. It didn't work because of a commit error I made in the version you are testing.

In any case the non-debug log had enough details to identify the actual problem you are having with the My Subscriptions folder.

Both issues will be fixed in a subsequent release.
