### ISSUE TITLE
My Subscriptions still not working

### ISSUE THREAD

**Issue by musicmagix** [anxdpanic/plugin.video.youtube#639]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.4+beta.2 (Leia.1 official)
* Kodi Version: 18.9
* Kodi GUI Language: Eng
* Operating System: MIUI TV 1.3.105 (aka modified Android 6.0.1
* Operating System Language: Eng

------

### Expected Behavior

When opening the „My Subscriptions“ I should see the latest video releases of my subscriptions.

------

### Current Behavior

My Subscriptions folder returns error.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Kodi startup
2. open yt plugin
3. open My Subscriptions folder

------

### Log

Please include a complete [debug log] https://paste.kodi.tv/puyucuxoqo

------

### Additional Information

The new beta has not fixed the problem, at least for me. Debug logging is impossible as the log file becomes too big for the Logfile Uploader Plugin. I can search and extract the log manually if needed. The time from clicking „My subscriptions“ to error abort is 20s long now. That is more than in the last beta.

Thank you for your help. Please let me know if I can do anything else.

------

**Comment by MoojMidge** [comment]
Whoops, this is why supporting Kodi 18 (Python 2) is problematic - different parts of the standard library handle inputs in different ways and fixing it for some/most common uses, breaks it for others, with some parts doing implicit conversions, other requiring explicit conversions, some parts supporting unicode strings, other parts only supporting encoded string. What a mess!

Anyway should be fixed properly now in https://github.com/MoojMidge/plugin.video.youtube/commit/d395ce8b76361c8d97d92aef6295e88ad4fef0b9

It is a simple fix, so you can try to make the change yourself, otherwise I will push a new beta release in the next couple of days

**Comment by musicmagix** [comment]
I have tried and successfully moved the line myself - it works!
Navigating Acode with the Chinese onscreen keyboard was quite a stretch.. feeling (slightly) smarter now^^

Thanks a lot!
