### ISSUE TITLE
Option to remove a video from a playlist without opening up the Youtube app like was possible before.

### ISSUE THREAD

**Issue by woodside007** [anxdpanic/plugin.video.youtube#681]
### What Problem Does This Solve? 

I used to be able to remove a video from a playlist in my personal app with older versions of the Youtube app using a command parsed from the context menu action such as...

`"RunPlugin(plugin://plugin.video.youtube/playlist/remove/video/?playlist_id=PLpMDNHHPkkPDvI9gbCy7rqk8dEz_5Q8-d&video_id=UExwTUROSEhQa2tQRHZJOWdiQ3k3cnFrOGRFel81UTgtZC41NkI0NEY2RDEwNTU3Q0M2&video_name=Shania+Twain+-+Any+Man+Of+Mine+%28Official+Music+Video%29)"`

but now, in newer versions it opens up the Youtube app and closes my app. 

------

### Suggest a Solution (optional)

Allow for way to run a direct command to remove a video from a playlist without opening up the Youtube app like was possible before these recent versions. I would have just kept the older version which made this possible but that went out the door when videos stopped playing in older versions due to Youtube shenanigans.

Would much appreciate if you could do this. Thanks. 

------

**Comment by MoojMidge** [comment]
You can test https://github.com/MoojMidge/plugin.video.youtube/commit/5c05a0be9913519d208a03ba63096aafc7a69486 and add `&reload_path=False` to your `RunPlugin` call

**Comment by woodside007** [comment]
Thanks very much. 
I am able to successfully remove a video from a playlist using this `RunPlugin `call here...

`"RunPlugin(plugin://plugin.video.youtube/playlist/remove/video/?category_label=Boots+in+the+Park&playlist_id=PLpMDNHHPkkPDPCvSOor5tuLQt2rKNJ_Hi&video_id=UExwTUROSEhQa2tQRFBDdlNPb3I1dHVMUXQycktOSl9IaS5DQUNERDQ2NkIzRUQxNTY1&video_name=Break+Up+In+A+Small+Town&reload_path=False)"`

It doesn't open the Youtube app anymore but it still however exits/crashes my app and drops me down into the skins video path directory as seen here below...(you can see in upper right corner it was successful).

![Screenshot 2024-04-02 135454](https://github.com/anxdpanic/plugin.video.youtube/assets/8515006/a1cadac3-5101-4573-bfed-2cd9a6952d44)

**Comment by MoojMidge** [comment]
Can you describe in more detail what your own plugin/app is trying to do?

Technically a call to `RunPlugin` should normally return a directory of listitems for Kodi to display, or a resolved url for Kodi to use for playback. If there is an action to be performed without returning a listing or url/listitem then that should normally be done using a script endpoint and `RunScript`, rather than a plugin endpoint, or my using the plugin as an importable Python module.

The framework that this plugin uses is quite old and didn't really acount for this seperation of functions, but the process of separating these has begun. Part of this process involves fixing a bunch of bugs associated with this plugin calling itself using `RunPlugin`, and I am unlikely to change this back as it will cause those other bugs to re-appear.

In the meantime it is possible to add specific workarounds for specific calls to `RunPlugin`, that should really be script actions, to cause them to fail and essentially do nothing, but Kodi does not always handle this gracefully, and you may still see the same behaviour of the video library window opening.

**Comment by woodside007** [comment]
Basically I have scripted an app that opens up using a WindowXML window and provides Youtube user playlists and video listings in a GUI interface. The lists are created by using json calls to get the Youtube directories and then using python to create the lists of videos from those directories to play in a smaller video window. While playing the videos it shows similar artists, fanart slideshows, artist, song info for the artist and song of the video playing. I also offer up concert event listings for the currently playing artist or you can search for events for any artist.

I offer a way (by a scripted context menu) to remove videos/playlists or add videos to playlist using Youtube RunPlugin commands. I can still do all that in the newest versions of your Youtube app except removing a video because now it wants to open up the Youtube app. I can still add and remove playlists or add videos to certain other playlists but removing a video is a no go with the newest version of the Youtube app. Hope this explains it.

![Screenshot 2024-04-02 193838](https://github.com/anxdpanic/plugin.video.youtube/assets/8515006/766fc96d-eecb-4ced-aab8-aeae5ecb6ede)
![Screenshot 2024-04-02 192802](https://github.com/anxdpanic/plugin.video.youtube/assets/8515006/1db81646-292b-4732-aaed-3d90420d32c3)

![Screenshot 2024-04-02 201847](https://github.com/anxdpanic/plugin.video.youtube/assets/8515006/31d4e3bb-97a9-4531-87bc-cf5e04ad93cd)

**Comment by MoojMidge** [comment]
That looks pretty good. You should post a link to it if you feel like making it available for others to use.

Given the use case, you made me look into this a bit more and I realised that https://github.com/MoojMidge/plugin.video.youtube/commit/5c05a0be9913519d208a03ba63096aafc7a69486 was not complete, and identified a few other related issues.

https://github.com/MoojMidge/plugin.video.youtube/tree/master includes additional related fixes if you want to test whether it fixes this issue, and also doesn't cause any others.

**Comment by woodside007** [comment]
Hey hey! Now works great. Thanks and really much appreciated for you going the extra mile to help me out. The only thing now though is that it seems to take about 4 or 5 minutes or so for the playlists to update (I'm supposing it's a cache thing) when adding a video to a playlist or removing a video. Before, I think it was instantaneous. What I had going before was (in the case of removing a video), I had a while loop...

` while xbmc.getCondVisibility('System.HasVisibleModalDialog'):
       time.sleep(1)`

to wait for the Ok/Cancel confirmation dialog that pops up (after choosing to remove a video) to close before I updated my list. If cancel was chosen then the list would be the same after reloading and if OK was chosen, then after reloading the list, the video would be gone. I had to do it this way because I had no way of knowing what option was chosen "Ok" or "Cancel" in your dialog (because my code didn't initiate the dialog) to guide my code on whether or not to reload the list. I thought about just adding some code to pop the video from the reloaded list but then I figured that wouldn't work if the option to cancel was chosen.

But anyhow, if nothing could be done about it then it is what it is. I really do just appreciate what you have already done.

**Comment by MoojMidge** [comment]
Yes the playlist is being cached. Your original issue, where the Youtube plugin was opening after the `RunPlugin` call, was caused by the Youtube plugin refreshing the playlist to update the cache.

Not sure how you are actually loading the playlist, but if it is by using a `plugin://plugin.video.youtube/playlist/` url, then you can try to add a `&refresh=True` query parameter to do the same playlist refresh in your own plugin.

**Comment by woodside007** [comment]
> Yes the playlist is being cached. Your original issue, where the Youtube plugin was opening after the `RunPlugin` call, was caused by the Youtube plugin refreshing the playlist to update the cache.
> 
> Not sure how you are actually loading the playlist, but if it is by using a `plugin://plugin.video.youtube/playlist/` url, then you can try to add a `&refresh=True` query parameter to do the same playlist refresh in your own plugin.

Wow! You're the boss. Adding '&refresh=True' was the ticket. Works like a charm. I really appreciate your help.

**Comment by MoojMidge** [comment]
No problem.
