### ISSUE TITLE
"Mark watched" doesn't work reliably

### ISSUE THREAD

**Issue by Solarunit** [anxdpanic/plugin.video.youtube#709]
### Context

"Mark watched" doesn't work reliably either by triggering it with `w` shortcut or via context menu.

- there is no watched video indicator after you marked video as watched
- video could be marked as watched temporary but when you return to playlist it's marked as not being watched

In Advanced setting I have "Use Local playback history" enabled

* Add-on Version: v7.0.5, v7.0.6+beta.1
* Kodi Version: 21 flatpak
* Kodi GUI Language: En
* Operating System: Linux
* Operating System Language: En

------

### Expected Behavior

"Mark watched" should works always reliable

------

### Current Behavior

"Mark watched" works very unreliable, it mostly doesn't work

------

### Steps to Reproduce

1. Mark video as watched
2. See that it doesn't works reliable

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> In Advanced setting I have "Use Local playback history" enabled

So you are using the plugin to manage watched history, so you need to use the plugin mark as watched or unwatched context menu item.

If you don't use the plugin history, then you use the Kodi context menu item.

**Comment by Solarunit** [comment]
I see, I thought "Use Local playback history" is kodi local history  vs YouTube history when you logged in.

I am interesting only in Kodi internal history. I disabled "Use Local playback history" and looks like it works now, thanks

**Comment by MoojMidge** [comment]
Have made some changes that may allow this to work when `Use local playback history` is enabled.

Can you check that it works? https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.2

**Comment by Solarunit** [comment]
I will check it today

**Comment by Solarunit** [comment]
@MoojMidge when `Use local playback history` is enabled, mark as watched from the context menu or `w` shortcut is very unreliable:

- thumbnail can blink after pressing  `w` but stays without proper watched/unwatched indicator
- watched/unwatched indicator can disappear from other thumbnails when you pressing  `w` on some other thumbnail

In my testing when `Use local playback history` is disabled it works correctly.

PS: I restated Kodi flatpak when I enabled/disabled this setting

**Comment by MoojMidge** [comment]
It is doing this because Kodi and the plugin have different details. The blinking you are seeing is Kodi refreshing the video listing to try and display updated info, but where the info was coming from may have changed during the display update i.e. from the plugin before pressing `w`, then from Kodi afterwards.

Doing it again should allow it to sync and it should work after that.

**Comment by Solarunit** [comment]
By blinking I mean a quick zoom-in/zoom-out thumbnail animation (and loading thing in the center) when pressing `w`. In my testing I tried pressing `w` ~10 times on one thumbnail and switched to the next. In some cases ✅ watched/unwatched indicator didn't appear when it should or for some reason disappeared from the unselected  thumbnail that I previously marked as watched (thumbnail with ✅)

**Comment by MoojMidge** [comment]
Yes that is because the plugin and Kodi have different information.

It takes some time in order to sync any existing differences. Currently it takes at least 1 second after the loading animation to sync the difference, so if you keep pressing `w` or move to a different item too quickly, then the syncing can fail.

**Comment by Solarunit** [comment]
I see, I will keep using `Use local playback history` disabled because it just working without any issues for me.

**Comment by MoojMidge** [comment]
You can do that if you want, but the local history is used for a bunch of other functions, and as you opened this issue I was hoping you would be willing to help test a fix.

**Comment by Solarunit** [comment]
I wonder why `Use local playback history` should be managed by the plugin when it could be managed internally by Kodi?
One of the reason I am thinking of is when you login into YT via plugin.

**Comment by MoojMidge** [comment]
The plugin has no way to know what the internal Kodi watched status is until after the list item is created by the plugin and displayed by Kodi, because Kodi has no way to indicate the watched status for something until after the plugin creates it.

However the local history is used for things like related videos and the watched history list, which would otherwise only be available if you do login via the plugin.

Anyway, the sync can now work. If it doesn't, then it is no worse than before, and I will get feedback from someone else if they have problems with it.

**Comment by Solarunit** [comment]
I see. Well I don't use any of those features (related videos and the watched history list) so this option just not for me.
I just need an indicator if video was being watched or not.
