### ISSUE TITLE
Unable to playback music videos since regenerating API key and OAuth ID

### ISSUE THREAD

**Issue by graysky2** [anxdpanic/plugin.video.youtube#730]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.6
* Kodi Version: Omega
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

Music/video content should to play back

------

### Current Behavior

What is the current behavior?

Music/video content refuses to play

GUI displays: "This video is not available"
Logs:
```
warning <general>: [plugin.video.youtube] Failed to retrieved video info - video_id: g65oWFMSoK0, client: android, auth: True,
           status: CONTENT_NOT_AVAILABLE_IN_THIS_APP, reason: Watch on the latest version of YouTube
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Attempt to playback content that contains music

------

### Log

Please include a complete [debug log](https://gist.github.com/graysky2/5cdddeccad48d0a30a34ea7b9bf2a035)

------

### Additional Information

Did I incorrectly setup my API key and/or OAuth client ID?  Prior to me needing to regenerate it, music/video content played back.  The OAuth 2.0 Client ID is type "TV and Limited Input"

Thank you.

------

**Comment by karldixon1986** [comment]
Have you tried version 7.0.6+Beta.1 That version fixed this issue for me although i am still having issues sending a playlist from my phone using yatse. Although i have found if i add to queue from the youtube addon it plays. If i send from yatse the first video plays and then it goes back to the system menu.

**Comment by graysky2** [comment]
I am on 7.0.6 final.

**Comment by woodside007** [comment]
Looks like Youtube is at it again. I believe  a couple of days ago they changed the android version number required to play video links again. This happened about a month or so ago. The work around for now is go to settings/advanced and change "use alternate client details" from "Default" to one of the alternates. Only thing is you won't get quality above 1080 using one of the alternates. Any 4k quality videos will only play using the "default" setting and right now nothing will play using the default setting. Hopefully @MoojMidge will fix it again soon.

**Comment by graysky2** [comment]
I tried both alternatives but got the same error.

**Comment by karldixon1986** [comment]
Im using alternative 2 and its working fine

**Comment by woodside007** [comment]
Hmmm. Sorry. I thought this might be your problem too since I got the same log warning  and videos wouldn't play until I changed to an alternate client setting. Hopefully you'll get it worked out soon.

**Comment by graysky2** [comment]
I did get it working:
```
Use alternate client details = Alternate #1
Support alternative player [x]
Use adaptive streaming formats with external player [x]
Use InputStream Adaptive [x]
Use for live streams = MPEG-DASH
```

**Comment by xyzfre** [comment]
> Looks like Youtube is at it again. I believe  a couple of days ago they changed the android version number required to play video links again. This happened about a month or so ago. The work around for now is go to settings/advanced and change "use alternate client details" from "Default" to one of the alternates. Only thing is you won't get quality above 1080 using one of the alternates. Any 4k quality videos will only play using the "default" setting and right now nothing will play using the default setting. Hopefully @MoojMidge will fix it again soon.

Thank you for this info I did not know, changing it from default to alternate it won't play 4K

**Comment by MoojMidge** [comment]
All, I have started to see a similar issue but everything still works for me using default settings because the alternatives are used automatically.

The alternative client selections doesn't change the client's that are tried, only the order in which they are tried, but this change https://github.com/anxdpanic/plugin.video.youtube/commit/5ab565d4295c84accc0f70a225f04bfbd2e47c02 may be too greedy depending on region and language used.

Can you comment out the following line: https://github.com/anxdpanic/plugin.video.youtube/blob/016ed385504372503d11a853e6c9b6c10d24cb0e/resources/lib/youtube_plugin/youtube/helper/video_info.py#L1145

By changing from
```
            self._context.localize(10005, 'not available').lower(),
```
To
```
            # self._context.localize(10005, 'not available').lower(),
```

Use v7.0.6 final, with these default settings, and report back if it works.
```
Use alternate client details - [Default]
Support alternative player - [Disabled] (this is unrelated to this issue. Only useful if you want to use an external or remote player in Kodi)
Use adaptive streaming formats with external player - [Disabled] (this is unrelated to this issue. Only useful if you want to use an external or remote player in Kodi)
Use InputStream Adaptive - [Enabled]
Use for live streams - [MPEG-DASH]
```

**Comment by woodside007** [comment]
> Use v7.0.6 final, with these default settings, and report back if it works.
 
@MoojMidge ... Commenting out that line and setting those settings does in fact fix the problem. Everything works great after making those changes. 4k and all.👍

**Comment by MoojMidge** [comment]
That's good.

Will push out a v7.0.6.1 release when I am back at a computer some time.

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6.1

**Comment by neo-neo1** [comment]
7.0.6.1 didn't fix this issue.

I ran the setup wizard and chose 1080p/60p.

This video (originally released Live) does not play on the default settings. I had to select Alternative Client#2 for it to play. However, Alternative Client#2 plays many videos at 720p or even 540p (instead of 1080p). 

https://www.youtube.com/live/ODnRjjbZzTE

In general, default settings are problematic and don't play some videos which originaly were released Live when using 1080p/60 selection on setup wizard.

Edit: selecting Adaptive HLS for Live Streams (instead of MPEG-DASH) also let's me play the linked video. It seems to the best fix as it doesn't downgrade some 1080p videos to 720p like Alternative Client#2 does.

**Comment by MoojMidge** [comment]
I have limited access to test anything at the moment, and even if I could, differences in region or even how Youtube responds to different requests from different users, will mean that I will not be able to reproduce the same result.

If you have a problem then I need to see a log.

**Comment by MoojMidge** [comment]
@neo-neo1 - I had a look on the website - that isn't actually a live video, but it may not have been converted a VOD yet. That would be the only reason why the `Settings > Advanced > InputStream Adaptive > Use for live streams` setting would have any effect on this.

Based on some of your previous comments you are still using Kodi v20, which means that you are also using a version of InputStream.Adaptive that won't properly with this, so your problem is likely nothing to do with this issue, but a more general live streaming problem.

If that is the case then the default setting to use `MPEG-DASH` for live streams may need to be reverted to `Adaptive HLS` for older versions of Kodi.

This is why logs are important.

**Comment by neo-neo1** [comment]
> @neo-neo1 - I had a look on the website - that isn't actually a live video, but it may not have been converted a VOD yet. That would be the only reason why the `Settings > Advanced > InputStream Adaptive > Use for live streams` setting would have any effect on this.
> 
> Based on some of your previous comments you are still using Kodi v20, which means that you are also using a version of InputStream.Adaptive that won't properly with this, so your problem is likely nothing to do with this issue, but a more general live streaming problem.
> 
> If that is the case then the default setting to use `MPEG-DASH` for live streams may need to be reverted to `Adaptive HLS` for older versions of Kodi.
> 
> This is why logs are important.

You're right, the video wasn't streamed live but it was infact a scheduled priemere.

I'm using Kodi 20.5 — are you suggesting Kodi 21 will fix the issue? Kodi 21 was only released 3 weeks for CoreELEC — which is what I use.

**Comment by MoojMidge** [comment]
Not specifically Kodi 21 itself, but the latest version of InputStream.Adaptive is required and that is only available for Kodi 21

I'll update the settings wizard to still prefer `Adaptive HLS` for older versions of Kodi.
