### ISSUE TITLE
"Next Page" in PVR

### ISSUE THREAD

**Issue by OzDrDj** [anxdpanic/plugin.video.youtube#750]
I am Using the YouTube addon in conjunction with Pseudo TV Live. I have many Youtube channels that PTVL pull down and loads into the TV Guide, However the first few will come up with the correct details then everything shows up with the title "Next Page" 
I conveyed this to Lunatixz the Dev from PTVL who tells me the problem probably lies with the YouTube Addon.

QUOTE: "PseudoTV parses the plugins meta, if the meta is incomplete PTVL will assume the directory label is the same as the contents title. There is nothing I can do, please contact your plugin developer and request they pay special attention to filling in as much listitem values as possible."

Could you please have a look at this in your next build.

Thanks In Advance

Oz

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> However the first few will come up with the correct details then everything shows up with the title "Next Page"
> I conveyed this to Lunatixz the Dev from PTVL who tells me the problem probably lies with the YouTube Addon.

Unlikely. This plugin does not do anything special for specific channels. They are all listed and displayed the same.

If it works for some, there is nothing different in how any channel listing is created for it not to work for others.


> PTVL will assume the directory label is the same as the contents title

This means nothing to me. Directories don't have a label. They can have a category though, and this plugin sets the category for channels as the name of the channel.

Listitems that open a directory do have a label, but the only listitem that has a label or name that is "Next Page" is the actual Next Page item and I am not going to change how that is labelled just because another plugin is using it as the name of the entire channel content, that makes no sense.

Actually there is nothing in this plugin that would create anything labelled "Next Page", there will always be a number in brackets as well e.g. "Next Page (2)", so if you are seeing just "Next Page" by itself then it is not coming from this plugin. 

As an aside, if you think it is a bug then you should provide a screenshot and log showing the problem. These details are not optional.

> request they pay special attention to filling in as much listitem values as possible

However this is not a bug, it is a feature request, and if you want to request something you need to provide sufficient details of what exactly you want i.e. what listitem values you want filled in and with what so it can be evaluated whether this can be done.
