### ISSUE TITLE
My Subscriptions & Bookmarks doesn't respect fanart_type

### ISSUE THREAD

**Issue by C-O-D** [anxdpanic/plugin.video.youtube#751]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7+beta.1
* Kodi Version: 20.5
* Kodi GUI Language: de
* Operating System: Manjaro Linux
* Operating System Language: de

------

### Expected Behavior

That the fanart selected in the settings is shown in all categories.

------

### Current Behavior

The corresponding fanart is not displayed in the bookmarks and in My Subscriptions but the blanket YouTube fanart background - neither in widgets with parameters nor in the addon itself

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  For example, set fanart_type as a preview image and go to the corresponding categories and look up...
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

I would find it very helpful if the subscription category always showed the channel fanart, as there is no preview image there.

And one more question: I use the Arctic Fuse skin and have to set the widget path for the spotlight widget manually. This is e.g. 
"plugin://plugin.video.youtube/kodion/bookmarks/list/?category_label=bookmarks"
There is already a question mark in there, how exactly do I have to add the parameter in this case?

"plugin://plugin.video.youtube/kodion/bookmarks/list/?category_label=bookmarks?fanart_type=3"
Is this right?

Btw, thanks a lot for adding this feature - especially with Arctic Fuse it is a great enrichment (if it is working)!
------

**Comment by C-O-D** [comment]
I have no idea why the last sentence appears in bold 😄

**Comment by MoojMidge** [comment]
My Subscriptions will be fixed in the next beta

> "plugin://plugin.video.youtube/kodion/bookmarks/list/?category_label=bookmarks" There is already a question mark in there, how exactly do I have to add the parameter in this case?
>
You need to use an ampersand (`&`): 
```
plugin://plugin.video.youtube/kodion/bookmarks/list/?category_label=bookmarks&fanart_type=3
```

However, the implementation of Bookmarks is still very immature and only has a limited feature set. Essentially every item in the Bookmarks (and also the local Watch Later list) is a snapshot of that item as it was when it was added to the Bookmarks, including any artwork associated with that item. This is done for speed, but means that the Bookmark items cannot currently by dynamically updated. This may change in the future.

**Comment by C-O-D** [comment]
Ok, thanks for the info 👍

**Comment by MoojMidge** [comment]
> I would find it very helpful if the subscription category always showed the channel fanart, as there is no preview image there.

BTW what does this mean? Are you talking about the My Subscriptions list or the list of subscribed channels themselves (Subscriptions)? What is the preview image?

**Comment by C-O-D** [comment]
I'm talking about the list of subscribed channels, actually only the channel fanart makes sense there. At the moment I only get the youtube fanart from the addon itself...I can change it in the widget but not in the addon itself

**Comment by MoojMidge** [comment]
So when you choose thumbnails as fanart you only see the default YouTube logo as fanart for channels?

This is to be expected, as channels don't have thumbnails, only banners used as fanart. However it is not a particularly useful result since those same banners are used instead of the thumbnails for channels, but are being ignored for the fanart. Will fix this.
