### ISSUE TITLE
7.0.7+beta.1 error notification 'My Subscriptions'

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#756]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7+beta.1
* Kodi Version: 20.5
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

------

### Expected Behavior

When open My Subscriptions to get content of subscriptions.

------

### Current Behavior

Error notification

------

### Log

[debug log]
[kodi(1).log](https://github.com/anxdpanic/plugin.video.youtube/files/15318016/kodi.1.log)

------

### Additional Information

All other features working fine (Playlists, Watch Later, etc.)

------

**Comment by DjDiabolik** [comment]
So... problably i can attach to this issue because whit same exact version of addons apparently today it doesn't work at all and in my case it doesn't even seem to log my account correctly.
now in Italy it is almost midday. last night the same addons worked without problems.

In my case I tried to log in again (with the two sessions of google.com/device) but after entering the second code it goes into error and doesn't even complete the login.

a pastebin of kodi.log it's here:
https://pastebin.com/reqGXxqf

I hope it's be usefull.... I think the two problems could be related to each other. Thanks in advance.


*EDIT*
Can also add some addictional information.....
Apparently same youtube addons works flawlessy in last PPA Kodi version 20.2.

**Comment by MoojMidge** [comment]
@DjDiabolik - that is a completely unrelated issue. Please open a new issue so it can be tracked.

@Mo1967 - I think this is related to #720. Your bookmarks database contains corrupted information. Would you be willing to share it with me privately so I can see what has happened and how it can be fixed without wiping the database?

Alternatively, if you are not concerned about the bookmarks database, can you make a backup of it, then delete it using the maintenance options in the settings? You can then try and re-add anything you had there previously to see whether the issue has gone away.

**Comment by Mo1967** [comment]
**@MoojMidge**  - 'Delete bookmarks database' in maintenance options was the goal. Thank you very much!
[kodi(1).log](https://github.com/anxdpanic/plugin.video.youtube/files/15330095/kodi.1.log)
