### ISSUE TITLE
7.0.7 unofficial - Using "Large List" result in different type of view style. Because ?

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#781]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7 unofficial
* Kodi Version: flatpak 21.0 updated
* Kodi GUI Language: Italian
* Operating System: Ubuntu 22.04 LTS
* Operating System Language: Italian

------

My current Skin it's the "Estuary Mod V2" KodiNerd edition.. and this an example inside the "My subscription" section:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/dcd95f58-52f8-498f-aeae-3c8a3605079a)

After that if i choose to open a Youtuber "Channel" from context menù instead of watched status icons all the thumbnails come out:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/6110396c-ed60-45ab-be19-4177f1f684a5)

the type of display is always the same. That is, "Large List" but why does this look different between the two sections?

**Comment by DjDiabolik** [comment]
Some additional information.

The problem seems to only appear if you use the "Go to xxxx" function (how xxxx it's the youtube channel directly from "My Subscription" feed )
so if I open the channel from here:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/a76d470b-fc59-4552-b0db-50c7d3d4ee1f)



If i open a channel directly from here:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/51a26716-714e-488b-96ec-d66c4f66d222)

"Registrations" from main list this thing doesn't happen

**Comment by MoojMidge** [comment]
I think this is the same underlying issue as #776. Can you check if it is fixed in:
https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by DjDiabolik** [comment]
@MoojMidge exact.
you suggest me to try to better describe the problem with photos/screenshots and some details in a different issue....

~~Can you have also the 'unofficial' version of your 7.0.7.1 ?~~

sorry, my English isn't the best around :) Google Translator it's by big friends in some cases :)

*EDIT*
Unofficial available... 
https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.7.1/plugin.video.youtube-7.0.7.1+unofficial.1.zip

**Comment by DjDiabolik** [comment]
Can test same issue whit 7.0.7.1 unofficial... this is screenshot of "My Subscription" feed:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/a3bd95a4-b268-4d82-a870-0f081159f139)

Use "Go To" from here:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/779990ac-11aa-47e2-aa39-a2686fbff7fc)

Obtain this:
![immagine](https://github.com/anxdpanic/plugin.video.youtube/assets/9040397/df2c3139-46bc-423e-b26a-fb8faacca6a9)

Apparently this strange issue/trouble it's fixed... now the "view style" and also the "watched status icon" it's correctly work.

**Comment by benyamin-codez** [comment]
@DjDiabolik & @MoojMidge, this was the behaviour I've been seeing since I think v7.0.6.3. It might have been an earlier beta tbh. It would also occur during a Refresh of "My Subscriptions". @MoojMidge, I hadn't mentioned this because I saw you were working on the refresh codebase and I presumed it was just a work in progress.

In any case, both _Refresh_ and _Go to Channel_Name_ do appear to be working now using MoojMidge_v7.0.7.1.

Refresh appears to actually refresh again too, which is nice given it hasn't since the cache was introduced (v6...?). I noticed in debug logging that the refresh counts the refresh attempt (it has done this for some time).  Is there a purpose to this or is it purely informational? Is the refresh rate-limited, i.e. are only a certain number of refreshes permitted (I previously stopped at four or five)?

It's worth noting, that instead of "spinning" during the refresh, the UI returns immediately. Some seconds later when the script finishes, the list is updated, i.e. there is no spinner displayed during the whole refresh. Should this be fixed?

**Comment by MoojMidge** [comment]
@DjDiabolik - I didn't quite understand what the problem was that your were describing, but the screenshots have helped to explain. Thanks.

It was unrelated to #779 which is why I asked you to post a separate issue, but it turns out that #776 has the same cause.

@benyamin-codez - Kodi has various ways of updating the content of an existing listing. Unfortunately they all have various issues when used in different ways.

> Refresh appears to actually refresh again too, which is nice given it hasn't since the cache was introduced (v6...?).

For a while now, the refresh was actually just a visual refresh rather than a refresh of the cached content.

Alternatively trying to update the container content within a window had issues where it could cause Kodi to load plugin content in a non-video window.

While trying to open a completely new window would often times lead to losing window navigation history and dumping the user back to the root of the video window.

All of these methods also run the risk of causing Kodi to crash if something else also activates a busy dialog (the spinner) at the same time.

To workaround these issues this plugin now uses the same method for all actions that programmatically load a listing, regardless of whether it is refreshing the current listing, or jumping to a different page in a listing, or opening a completely different listing - it loads the content in the background, caches the content if the loading worked, and only opens the window with the cached content if the loading worked.

> I noticed in debug logging that the refresh counts the refresh attempt (it has done this for some time). Is there a purpose to this or is it purely informational?

One other issue that Kodi has is that it will refuse to open a window with the same address as the current window. This is why the refresh count changes - it causes the url to change allowing Kodi to open the window with the refreshed content that was newly loaded and cached.

> there is no spinner displayed during the whole refresh. Should this be fixed?

This is an intentional consequence of the method chosen to load content, to avoid crashes. I suppose a notification can be shown instead, to indicate that something is loading.

**Comment by DjDiabolik** [comment]
@MoojMidge I knew the "next page" problem in "My Subscriptions" and this whit miniature instead "watched or unwatched" status they could not correlate.
I saw it as a minor problem and above all not invalidating the general functioning of the addon itself and so I mentioned it like that out of curiosity.

Is the "watched status" refresh problem also being corrected? I had an issue open perhaps years ago regarding something like this (if i remember somethigs like watched status not correctly preserved when you step back from page to previous page or somethings similar) .

**Comment by MoojMidge** [comment]
There is no problem in just mentioning something, but I need details to actually do anything about it. It is easier to track things in separate issues with details provided, otherwise it will just get lost amongst the other discussion.

> Is the "watched status" refresh problem also being corrected?

Try it and let me know. There has been recent changes made to fix this.
