### ISSUE TITLE
Can't open "My Subscriptions" folder

### ISSUE THREAD

**Issue by pnperehod** [anxdpanic/plugin.video.youtube#782]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7
* Kodi Version: 20.5
* Kodi GUI Language: en
* Operating System: Linux
* Operating System Language: en

------

### Expected Behavior

Enter "My Subscription" folder 

------

### Current Behavior

Can't enter "My Subscriptions" folder. Other folders work as usual

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Enter Add-On
2.  Try to open "My Subscriptons" folder
3. 

------

### Log

------

### Additional Information

------

**Comment by Mo1967** [comment]
Please test v7.0.7.1

https://github.com/anxdpanic/plugin.video.youtube/issues/780

**Comment by pnperehod** [comment]
7.0.7.1 - nothing changed

**Comment by MoojMidge** [comment]
🤷 No log, no problem.

**Comment by mlebedaLM** [comment]
Same problem for me. LOG is here: https://paste.coreelec.org/EaterPatience

**Comment by MoojMidge** [comment]
Unfortunately that is not a debug log (and it also has line breaks stripped out which makes it very difficult to read).

Can you try to get a debug log using the process outlined here: https://kodi.wiki/view/Log_file

Alternatively try https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

But it would helpful if you can provide a debug log of it not working in any case.

**Comment by mlebedaLM** [comment]
I appreciate your patience; it has been years since I sent the last logs. Thank you for the wiki guide. 

Now I tried to reproduce the problem again after reboot, and "My Subscriptions," aka "Moje odběry" works like a charm: https://paste.kodi.tv/okodezakuk.kodi
Here is an upload of the log from yesterday when it was not working: https://paste.kodi.tv/sopovonito.kodi
**edit:** Yesterday, I tried a few reboots after installing v7.0.7 without success.

**Comment by MoojMidge** [comment]
There is nothing much to see in the logs, but that itself is useful information.

My Subscriptions is now being cached much more aggresively than it used to, and I think you must have had some internet connectivity issues (similar issues are shown in your log for other plugins) which led to an empty My Subscriptions list.

I think that the empty list was being cached and reused (until the cache expires), because your log doesn't show any attempt to update the listing at all. If that is the cause of the problem, then should be able to put something in place to guard against that.

**Comment by mlebedaLM** [comment]
Thank you. 
A little offtopic: Could you just point me to which string signs "connectivity issues" to know in the future? I will look into that.

**Comment by MoojMidge** [comment]
> Could you just point me to which string signs "connectivity issues" to know in the future?

Common things to look for are errors associated with urllib3 (script.module.urllib3) and/or requests (script.module.requests). Although the exact error messages seen in this instance could mean that it was a server error rather than a connectivity issue, or possibly a proxy/VPN error if you use that. 

Also your weather keeps trying to download over and over again, possibly indicating that it keeps failing and retrying.

**Comment by crowly0** [comment]
Short version: Try clearing the function and data caches + temporary files from Settings - Maintenance

Bit longer version: This issue has come and gone on my two Kodi installs. Last two times it happenend was last night and this morning (as of writing). 
Last night i first tried to clear the function and data cache. That didn't help. I then deleted the function and cache databases and temporary files, and then it worked. A bit to many things changed at once to narraow down the cause. So when it happened again this morning, I first deleted just the temporary files. Didn't help. I then cleared the function and data caches, and then it worked.

Edit: This is on 7.0.7. Have not tried 7.0.7.1

**Comment by neo-neo1** [comment]
Also can confirm had this exact same problem on 7.0.7 — and upgrading to 7.0.7.1 fixed it.

Note: I tried clearing/deleting cache and temp files and rebooting and it didn't help. 

### Edit: Problem occurs in 7.0.7.1 as well. Same issue occured.

I need to learn to stop upgrading to the latest bleeding edge version, unfortunately always something breaks. I do appreciate the active dev work on the Addon for a change after only bug fixes for the last couple years.

**Comment by neo-neo1** [comment]
Edit: Problem occurs in 7.0.7.1 as well

I need to learn to stop upgrading to the latest version, unfortunately always something breaks.

**Comment by Mo1967** [comment]
@MoojMidge 
since few days the problem come back with v.7.0.7.1, observed  in alternation the same with v7.0.7+beta.3
[kodi.log](https://github.com/user-attachments/files/15571588/kodi.log)

**Comment by MoojMidge** [comment]
Yep, the problem was identified in the log that @mlebedaLM provided, after the v7.0.7.1 test release

A possible fix is in https://github.com/MoojMidge/plugin.video.youtube/commit/7db63bf19606d288e922405f842e76071f29967b but I haven't had a chance to create a new test release yet

**Comment by neo-neo1** [comment]
Thanks for your work @MoojMidge

**Comment by MoojMidge** [comment]
Can you try again. Test release updated https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by Mo1967** [comment]
> Can you try again. Test release updated https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

Can confirm, working for each user. Thanks for your passion.
[kodi(2).log](https://github.com/user-attachments/files/15746223/kodi.2.log)

**Comment by pnperehod** [comment]
thanks for the update, this problem solved, but now "new search" in search section gives an error message. Unfortunately, cant make an error log now,  try to do it later.

**Comment by MoojMidge** [comment]
All good, no need for a log - #792
