### ISSUE TITLE
The videos in "My Subscriptions" are not updating after Sign Out and Sign In to a new channel

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#786]
### Context
* Add-on Version: v7.0.7.1
* Kodi Version: 21
* Kodi GUI Language: English
* Operating System: Window 10
* Operating System Language: English
------
After Sign In to a new channel, "My Subscriptions" shows videos from the previous channel. At the same time, in "Subscriptions" after Sign In everything is new, as it should be. Restarting Kodi does not help. After clearing the cache in some "Maintenance" items, either videos from the new channel appeared or "My Subscriptions" did not open. So, maybe it's the same problem as #782. [Log ](https://paste.kodi.tv/ubiwicobif.kodi)(before clearing the cache in Maintenance).

There are a couple questions on a related topic. I apologize if they are not relevant here. I tried to understand how "My Subscriptions" is updated on different versions of the plugin and didn't get it. Is there a pattern? It seems like the updates are rare. For example, after subscribing to a new channel, it appears instantly in "Subscriptions" and with some incomprehensible delay in "My Subscriptions". And restarting Kodi does not speed up the process. Similarly, it is not clear how often the plugin updates the contents of saved playlists. For example, if you save a playlist from another account (without being logged into it) directly into Kodi's "Favorites" and then add a new video to that playlist, Kodi doesn't see it right away, although it has seen it in the past.

**Comment by MoojMidge** [comment]
> After Sign In to a new channel, "My Subscriptions" shows videos from the previous channel.

By channel do you mean Youtube user account?

I think you are getting mixed up between Youtube user accounts, user in this plugin, and OAuth credentials that need to be created to access a specific Youtube user account. 

When you sign-in or sign-out, that is for a specific Youtube user account that you have created OAuth credentials for. If you want to use a different user account then you need to setup OAuth access for that account.

The user selection in the plugin is meant to allow you to easily switch the OAuth details for different Youtube user accounts, otherwise you will need to keep changing these details manually.

You are not changing users, you are just signing out of one account, trying to access the subscriptions of that same account (which you can no longer do because you have signed out) which results in an empty My Subscriptions list being cached (this is the problem in #782), then logging back into the same account and trying to open My Subscriptions, which now uses the cached empty list (#782 again) from when you were signed out.

> Is there a pattern?

Most requests are being cached. Typically for 30 minutes or an hour, some content is cached for longer periods, some for shorter periods. If you want to update it immediately, open the context menu and select refresh.

**Comment by demouser007** [comment]
> By channel do you mean Youtube user account?

In a youtube account, you can create "channels" that work as separate youtube accounts. You can do that [here](https://www.youtube.com/channel_switcher?next=%2Faccount). I meant such channels, as they require a separate login and in practice work as separate accounts. I've now tried to reproduce the bug with a completely separate youtube account that's on a different google account. The bug was reproduced.

> I think you are getting mixed up between Youtube user accounts, user in this plugin, and OAuth credentials that need to be created to access a specific Youtube user account.

I used to use the user system in this plugin as a way to separate YouTube feeds by topic. I logged in with separate accounts (channels) in separate users and it always worked well. But this particular problem I noticed in a plugin with only one user (default).

> When you sign-in or sign-out, that is for a specific Youtube user account that you have created OAuth credentials for. If you want to use a different user account then you need to setup OAuth access for that account.

I don't really understand this. If I make a Sign Out for a "default" user, it's not a "full" Sign Out? Can I then fully Sign In to the "default" user with another YouTube account? If so, the problem is that after the new Sign In (when you have to enter the code twice at google.com/device), "My Subscriptions" shows videos from the "old" Sign In to the "old" YouTube account.

> The user selection in the plugin is meant to allow you to easily switch the OAuth details for different Youtube user accounts, otherwise you will need to keep changing these details manually.

That's how it usually works for me. I'm logged in with different accounts for different users and switch between them easily.

> You are not changing users, you are just signing out of one account, trying to access the subscriptions of that same account (which you can no longer do because you have signed out)

I did sign out and then sign in to another account (by entering the code twice at google.com/device). After that the videos in "My Subscriptions" did not update, but the channels in "Subscriptions" did. It looks like changing the account in the user doesn't cause the "My Subscriptions" cache to auto-refresh.

> Most requests are being cached. Typically for 30 minutes or an hour, some content is cached for longer periods, some for shorter periods. If you want to update it immediately, open the context menu and select refresh.

Thanks for the clarification. Is it possible to make "My Subscriptions" refreshed after restarting Kodi, and the videos in the saved playlist immediately after opening it? 
It would be very convenient and intuitive.

**Comment by MoojMidge** [comment]
Yes, the way the plugin users works has changed a bit since v7.0.3

Previously every plugin user shared the same cache, and switching users simply cleared the cache. Signing out/in did the same.

Now each user has their own cache, so clearing the cache is not necessary when changing users. I didn't consider that someone would sign in/out to multiple accounts using the same user, and it doesn't make sense to clear the entire cache for this, but this scenario probably needs to be handled better.

> I used to use the user system in this plugin as a way to separate YouTube feeds by topic. I logged in with separate accounts (channels) in separate users and it always worked well.

This is the way I thought most people would use the user function. 

> But this particular problem I noticed in a plugin with only one user (default).

Yes, this won't work if you are signing in/out to different Youtube accounts using the same user.

> I don't really understand this. If I make a Sign Out for a "default" user, it's not a "full" Sign Out? Can I then fully Sign In to the "default" user with another YouTube account?

The plugin user is not the same as Youtube account, unless you only use one Youtube account per plugin user. You are not signing in to the default user, you are signing in to the YouTube account. 

> If so, the problem is that after the new Sign In (when you have to enter the code twice at google.com/device), "My Subscriptions" shows videos from the "old" Sign In to the "old" YouTube account.

That's because the cached data is per user, not per YouTube account.

> videos in the saved playlist

The first page playlist items are only cached for 5 minutes I think.

**Comment by demouser007** [comment]
>I didn't consider that someone would sign in/out to multiple accounts using the same user, and it doesn't make sense to clear the entire cache for this, but this scenario probably needs to be handled better.

Yes, it's not a frequent scenario, but if a sign out is done sometime, there is an expectation that it will be a "full" sign out.

> The first page playlist items are only cached for 5 minutes I think.

As far as I understand, caching is necessary to increase the speed of the plugin and save resources. It seems that people don't visit saved playlists very often, and if they are refreshed at the moment of opening, there will be no noticeable slowdown in the plugin. Such playlists are convenient to use for sending videos to Kodi from YouTube's web version or official mobile clients. 

And all other periods for refreshing "cached requests" look rational. The only thing that seems to be missing is updating "My Subscriptions" after restarting Kodi (while keeping the periods that are already used when Kodi is running).

**Comment by MoojMidge** [comment]
> there is an expectation that it will be a "full" sign out.

I don't make use of this at all. Can you describe in greater detail what you expect a "full" Sign Out to do, or what you want it to do?

Note that you are completely signed out, so you can't access content that requires you to be signed in, but anything that is cached still exists in storage.

This is pretty much the same as a web browser i.e. logging out of a website doesn't clear the stored data for the website.

The main difference is that a browser is typically smarter and less aggressive with storing and using cached content, especially with dynamic content. I have a plan to improve this https://github.com/anxdpanic/plugin.video.youtube/issues/116#issuecomment-2131709065 but it is not something that will happen soon.


> As far as I understand, caching is necessary to increase the speed of the plugin and save resources.

Yes, and because of things like this #545

**Comment by demouser007** [comment]
>Can you describe in greater detail what you expect a "full" Sign Out to do, or what you want it to do?

I meant it from a user perspective. That after sign out of one account and sign in to another, you expect to see content corresponding to the new account. And if some content remains old, then from the user's point of view it looks like the sign out was incomplete. But I understand that technically it's about the cache, and that technically sign out works.

>I have a plan to improve this https://github.com/anxdpanic/plugin.video.youtube/issues/116#issuecomment-2131709065 but it is not something that will happen soon.

This is a minor issue, as the need to change accounts in a single user is extremely rare.

> Yes, and because of things like this #545

So is it possible to refresh "My Subscriptions" after restarting Kodi, and refresh saved playlists after opening them?

**Comment by MoojMidge** [comment]
> That after sign out of one account and sign in to another, you expect to see content corresponding to the new account. And if some content remains old, then from the user's point of view it looks like the sign out was incomplete.

Yeah that makes sense, unfortunately the user storage is not separated per account, so it is not currently possible to do this without clearing the cached items.

> So is it possible to refresh "My Subscriptions" after restarting Kodi, and refresh saved playlists after opening them?

Not easily. Identifying when cached content is stale, without downloading it again is just about impossible, and why it is usually done based on the age of the cached content. The future plan is to rely on YouTube to tell the plugin if the content is stale, which should resolve most of the problems.

To do what you are looking for would require the plugin to keep track of the age of the cached content (which it already does) and also keep track of the first time that the cached content is accessed after the plugin is started. Not impossible, but not straightforward.

**Comment by demouser007** [comment]
> To do what you are looking for would require the plugin to keep track of the age of the cached content (which it already does) and also keep track of the first time that the cached content is accessed after the plugin is started. Not impossible, but not straightforward.

Do these difficulties apply to refreshing saved playlists (particularly those saved in Favorites)? Updating a playlist when it is opened is more important than updating "My Subscriptions" after restarting Kodi. The second seems like a logical behavior, but the need for it is not too great (especially if it's difficult to implement).

**Comment by MoojMidge** [comment]
Refreshing is easy. Knowing when to refresh is what is complicated.

Refreshing on open is also easy. Refreshing only the first time something is opened, and after that refreshing based on time, requires implementing some kind of session storage that can be accessed across various plugin invocations which is not straightforward.

**Comment by neo-neo1** [comment]
Just encountered this same issue hours after updating to 7.0.7.1
