### ISSUE TITLE
The last page in "Subscriptions" is missing

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#787]
### Context
* Add-on Version: v7.0.7.1
* Kodi Version: 21
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English
------
In plugin version 7.0.5, on the last page (the one with the latest channels) in "Subscriptions" there is no link to the next page.  In the latest versions of the plugin on the page with the latest channels there is a link to the next page, which is the first one. And page flipping starts in a circle.

**Comment by MoojMidge** [comment]
> In the latest versions of the plugin on the page with the latest channels there is a link to the next page, which is the first one. And page flipping starts in a circle.

That is intentional. The next page item now includes a context menu to help with navigation and avoid having to press back multiple times. To include this context menu on the last page of a listing, which would otherwise not include a next page item, a link to the first page is shown instead. 

Are you saying the last page is actually missing and you can only get to the second last page, or just observing that the last page no longer leads to a deadend?

**Comment by demouser007** [comment]
> That is intentional. The next page item now includes a context menu to help with navigation and avoid having to press back multiple times. To include this context menu on the last page of a listing, which would otherwise not include a next page item, a link to the first page is shown instead.

I understood the compromise. Aesthetically it got worse, but those reasons are important.

> Are you saying the last page is actually missing and you can only get to the second last page, or just observing that the last page no longer leads to a deadend?

Just observing that the last page no longer leads to a deadend.
