### ISSUE TITLE
Setup wizard keeps on popping up

### ISSUE THREAD

**Issue by jusboa** [anxdpanic/plugin.video.youtube#789]
### Context

Please provide any relevant information about your setup

* Add-on Version: tried following: 7.03, 7.04, 7.05 and 7.07
* Kodi Version: 21
* Kodi GUI Language: Czech
* Operating System: Ubuntu 22.04
* Operating System Language: English

------

### Expected Behavior

Whe the wizard is disabled it should never show up.
When the wizard is once completed or quit it shall never appear.

------

### Current Behavior

The wizard window keeps on coming on activating either of youtube menu items, like new search etc., regradless it is disabled or it's already been completed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
The details asked for in the issue template are required. If you don't complete them then no help can be provided.

However despite the lack of information I can probably guess what is wrong because other people have reported similar issues which you can see when you search the closed issues.

You are using an old unsupported Alpha 1 version of Kodi 21 on an old version of Ubuntu.

You need to either downgrade to a release version of Kodi 20 or try and figure out how to use a release version of Kodi 21.

**Comment by jusboa** [comment]
ok, thanks. That worked. I upgraded to Ubuntu 24.04 and Kodi 21 and the erroneous behavior is gone.
