### ISSUE TITLE
Adding YouTube Playlist to Kodi Smart playlist

### ISSUE THREAD

**Issue by OzDrDj** [anxdpanic/plugin.video.youtube#790]
Is there a way to add a YouTube Playlist to a Kodi Smart Playlist?

I have been fiddling around with Pseudo TV Live for some time now, and while it does a great job most of the time, it has some problems with a lot of YouTube Content.
This problem could be fixed if there were a simple way to add a YouTube Playlist to a Kodi Smart Playlist.
This would Speed-Up Pseudo TV Live
Make Playback of a YouTube Channel better as the rules in the smart playlist would make YouTube Channels Manageable.
For example, I can drag a playlist into Kodi and watch it, or do the same from Pseudo, but in this instance I only get about 10 videos off the top of a playlist and always in the same order.
If the YouTube Addon pulls down a playlist, and dropped it into a Kodi Smart Playlist Kodi could then screen videos based on the video name, and most importantly it could take a playlist of 100 videos in a few seconds, and randomize them for playback giving the user a unique playlist everytime.
Playlist then of course could be combined to mix and match channels to your hearts content.

So thats the What and Why, The question to answer is How? Is this possible at all, I'm sure it is a posibility as Using a website as simple as playlist copier can drag down a Full Youtube playlist up to 100 Videos in seconds. If thats possible then it should be a simple task to drop that list into a kodi smart playlist, or at least i think it would. 

Im guessing this would be a simple trick for the YouTube Addon, or perhaps even a seperate script.  Please let me know what you think and thanks for listening.

Oz

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

------

**Comment by MoojMidge** [comment]
> I'm sure it is a posibility as Using a website as simple as playlist copier can drag down a Full Youtube playlist up to 100 Videos in seconds. If thats possible then it should be a simple task to drop that list into a kodi smart playlist, or at least i think it would.

Sounds like you already have your own answer.

In future follow the issue template, it is not an optional requirement. Questions belong in the forum, just like all your other questions which were responded to, and which you subsequently ignored.

This is not your personal Q&A line for random questions about how Kodi or Youtube works.

**Comment by OzDrDj** [comment]
Good God, I was just asking a simple question, but seems you not only don't care about the idea, you want to be rude about it also. I sometimes wonder why those who know the answers to these sorts of enquiries decide that because they are so smart and some of us who are learning still take it upon themselves to be rude and condescending to others, civility costs nothing, a trait sorely missed in this day and age. Looks like I'll have to go learn Python or whatever it is this is written in. It's many years since I worked in programming and I didn't really want to learn a new language, but what else can you do when he developers of such wonderful software don't listen to the people they are supposedly writing for. I weep for the future.

**Comment by MoojMidge** [comment]
> I was just asking a simple question

It is made clear that questions belong in the forum. Latitude was given previously, but you keep on ignoring simple requests to provide relevant information and keep things on-topic and relevant to this plugin.

> I sometimes wonder why those who know the answers to these sorts of enquiries decide that because they are so smart and some of us who are learning still take it upon themselves to be rude and condescending to others

You are describing your own behaviour. You pose a random question that is of no relevance to this plugin, then expect someone else to spend their own time doing work for you, in order to fulfill your unreasonable expectations based on your own nonsensical answers to these random questions.

> don't listen to the people they are supposedly writing for

Do you honestly think people are writing software just for you?

To be very clear, you are the only one being rude:

- Who ignores the clear direction that questions are to be directed to the forums when creating an issue?
- Who posts random questions about other plugins and Kodi in general in this issue tracker?
- Who ignores the details that are required when creating bug reports in this issue tracker?
- Who ignores responses and questions asked about all their other opened issues?
- Who has a tantrum when they get an answer they don't like?
