### ISSUE TITLE
Play with quality doesn't list all available qualities

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#806]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7
* Kodi Version: 20.5
* Kodi GUI Language: FR
* Operating System: Android
* Operating System Language: FR

------

### Expected Behavior

When you select play with quality, Youtube shall list all available qualities. 

------

### Current Behavior

Play with quality lists 1080p (dash) and 360p (mp4). Qualities such as 720p, 480p, 240p, 144p aren't proposed. 
When I disable dash, play with quality is skipped and video starts with default 360p. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Hit middle button to display play menu
2. Select play with quality
3. It doesn't display all available qualities when dash is enabled

------

### Log

https://paste.kodi.tv/emehiqopuj.kodi

------

### Additional Information

Take a look with this video : 
https://www.youtube.com/watch?v=87sIn_ANauA

![Play with quality](https://github.com/anxdpanic/plugin.video.youtube/assets/5579457/669cbfd5-7851-4122-9e67-e7980c0247c4)

------

**Comment by MoojMidge** [comment]
If it isn't displayed then it is not available. Without MPEG-DASH qualities above 720p are generally not available.

Lower quality streams may be available, but I can't remember if they are purposefully filtered out because no one used them. Normally should be able to see 720p and 360p but that will vary depending on settings, the video itself, and which client is used.

You can try https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.3 which improves support for displaying the streams offered when you change the client to Alternative 2 in the plugin advanced settings. It will still vary depending on the individual video though.

If you want to switch quality, use MPEG-DASH and change the stream from the stream selection dialog in the video OSD options.

**Comment by karlo2105** [comment]
@MoojMidge 
Could you please restore all available qualities listing in default client ? Alternate 1 plays Youtube in 1080p h264 which is much better than 1080p dash. It would be great if you could add it in default client.

**Comment by MoojMidge** [comment]
There is nothing to restore. The default client does not offer that quality, and that quality is not even available for all videos.

Refer to #505 for further discussion.

youtube-dl/yt-dlp users (and even some website users) are currently experiencing issues where they are getting IP blocked and needing to login/authenticate to access YouTube.

While this plugin doesn't take extensive measures to disguise itself, making multiple requests at the same time for the same resource, pretending to be a bunch of different clients, is a pretty easy giveaway of the use of a third party client or bot-like activity.

The consequences of getting your account blocked is a bit more significant than just an (temporary?) IP block.

**Comment by karlo2105** [comment]
@MoojMidge
Alternative 1 with inpustream adaptive enabled, gives me vp9 video without sound. Is there any chance to put h264 by default? 
When i switch to Alternative 2, i can't play video with subtitles. Any workaround?
I wish i could have 720p on default client with inputstream enabled.

**Comment by MoojMidge** [comment]
> Alternative 1 with inpustream adaptive enabled, gives me vp9 video without sound. Is there any chance to put h264 by default?

No. The unmuxed streams aren't selected by default unless you have set it up to do so. These individual streams will be disabled in a future release when using Alternative 1. Just use the combined HLS stream instead.

Maybe in the future could look to transform the provided playlist to a MPEG-DASH manifest, but it's additional work to replicate what is already done for the default client.

> I wish i could have 720p on default client with inputstream enabled

Use the default client, enable MPEG-DASH, and choose the resolution that you want to use.

> When i switch to Alternative 2, i can't play video with subtitles. Any workaround?

Need a log to understand why this may not work. Edit: Just wasn't enabled. Will be fixed in next release.

**Comment by karlo2105** [comment]
@MoojMidge 

> No. The unmuxed streams aren't selected by default unless you have set it up to do so. These individual streams will be disabled in a future release when using Alternative 1. Just use the combined HLS stream instead.

I am not fond of VP9 streams as it doesn't allow smooth advance as mp4. Could you tell me how to put h264 by default on Alternative 1 Client ?

> Use the default client, enable MPEG-DASH, and choose the resolution that you want to use.

I don't like mpeg-dash in Youtube because unlike SmartTube, it heats my box which provokes auto reboot despite 4GB RAM after some hours which is seldom case with adaptive streams. Fast forwarding with MPEG-DASH also provokes CPU overheat. 
How come did default client propose all qualities till Monday without problems ? I can understand lack of qualities when some streams in Youtube don't propose 720p or 480p but it happens on all streams in Youtube addon default client which isn't case in Youtube site. 

> Need a log to understand why this may not work. Edit: Just wasn't enabled. Will be fixed in next release.

Regarding Alternative 2, with lack of subtitles, you can take a look in the log : https://paste.kodi.tv/fudezoheza.kodi
I hope it helps. Thanks for updates. I shall stick with alternative 2 when you fix subtitles load because i prefere h264 over MPEG-DASH.

**Comment by MoojMidge** [comment]
> Could you tell me how to put h264 by default on Alternative 1 Client ?

As I said before, no, this can't be done.

> it heats my box which provokes auto reboot despite 4GB RAM after some hours which is seldom case with adaptive streams. Fast forwarding with MPEG-DASH also provokes CPU overheat.

Use MPEG-DASH. MPEG-DASH uses adaptive streams and they can be switched between and selected on the fly during playback, without having to select them prior to playback starting.

It includes all streams available (all different qualities and codecs) in one MPEG-DASH manifest. Your device is likely overheating because you are trying to play AV1 video streams, which are included with all the other streams

> How come did default client propose all qualities till Monday without problems ? I can understand lack of qualities when some streams in Youtube don't propose 720p or 480p but it happens on all streams in Youtube addon default client which isn't case in Youtube site.

Again, use MPEG-DASH. All the qualities are there. The different qualities listed in the ask for quality dialog are the non-adaptive streams, which YouTube have been progressing removing for a while.

Please don't ignore the answers provided to you and then repeat the same question multiple times.

It sounds like you have simply misconfigured the plugin based on your desire to avoid MPEG-DASH without understanding what it is. Run the Setup Wizard, use the recommended default settings, then choose the performance settings that best match the device you use.
