### ISSUE TITLE
Alternative 2 client : Played video not synced with Youtube history

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#826]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.8
* Kodi Version: 20.5
* Kodi GUI Language: FR
* Operating System: Android
* Operating System Language: FR

------

### Expected Behavior

When you play video within addon on alternative 2 client, it shall be shown in Youtube history as in default client. 

------

### Current Behavior

History playback isn't saved in Youtube account on alternative 2 client. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Youtube 7.0.8
2. In advanced settings, set alternative 2 client with inputstream adaptive enabled
3. Play any video and check in Youtube history

------

### Log

Please include a complete : https://paste.kodi.tv/yovifokozi.kodi

**Comment by MoojMidge** [comment]
I have tried to explain this to you previously - there are very few reasons to set up the plugin in the way that you have.

For almost all videos, the only thing that using alternative client 2 offers, that the default client does not, is the ability to select 1080p or 720p video, before the video starts playing.

However the default client using MPEG-DASH will adaptively switch to those same qualities, and also allow you to switch to those qualities manually, if you want, during playback. Something which you can't do if you have manually selected a video quality prior to playback.

I am disinclined to investigate why this particular feature works differently, because I already know that the request queries provided are different. As mentioned previously, the different clients do not behave the same, nor offer the same features, and it serves little purpose to try and re-implement stuff that already works using the default settings.

If you really insist on making things difficult for yourself, then you will need to provide a debug log of the playback, otherwise there is nothing to even look at.

**Comment by karlo2105** [comment]
@MoojMidge 
I enabled Verbose logging of Video component if it means log of the playback. 
You can find [here](https://paste.kodi.tv/abozuseted.kodi) log. I hope it shall help. Thanks for effort. 
I shall give MPEG-DASH benefit of doubt but so far it made my box so hot after watching some long videos that you could make scramble eggs on it. I am not keen of having my box rebooting after a couple of days because of watching dash videos in Youtube.

**Comment by MoojMidge** [comment]
> I shall give MPEG-DASH benefit of doubt but so far it made my box so hot after watching some long videos that you could make scramble eggs on it. I am not keen of having my box rebooting after a couple of days because of watching dash videos in Youtube.

As I mentioned before you are misunderstanding what MPEG-DASH is. It is not a video format, it is a method for streaming different video formats.

It is not MPEG-DASH that may be causing your device to overheat, it is the type of video being provided, likely AV1, that your device can't handle.

I have asked you to use the Setup Wizard to configure the plugin a number of times previously. You are just creating problems for yourself (and taking up my time trying to explain things to you multiple times) by not doing so.

Use the default setting and the `4K/60 fps, HDR if compatible` preset and your issues will magically disappear.


> You can find [here](https://paste.kodi.tv/abozuseted.kodi) log. I hope it shall help.

Unfortunately it doesn't. The update requests are being made, but as I said before, the format the request query takes is different compared to other clients.

**Comment by MoojMidge** [comment]
Closing. Alternate client selections will be removed.
