### ISSUE TITLE
More navigation buttons in Channel pages

### ISSUE THREAD

**Issue by mhomak** [anxdpanic/plugin.video.youtube#868]
### What Problem Does This Solve? 

When you want to watch older (or even oldest) videos in a channel, navigation become laborious and you have to go dozens of times via the "next page" button if the page has many videos.

------

### Suggest a Solution (optional)

Adding more buttons along with the existing (next page) button would be helpful. Most helpful would be the "Last page" button,  accompanying that a "Previous page" button (because "back" button in remote wouldn't work in that case).

------

I don't know if it's trivial to implement (I think "next page" link depends on the current page so getting to the last page would take a lot of API calls maybe?). If that's the case please feel free to ignore.

**Comment by MoojMidge** [comment]
Related discussion: https://github.com/anxdpanic/plugin.video.youtube/issues/715#issuecomment-2099434490

I think it should work and be enabled for channels, but maybe it didn't work and I ended up disabling it. Can't remember now.

If it works I'll re-enable it.

**Comment by MoojMidge** [comment]
Doesn't work unfortunately, and I don't have the time to try and reverse engineer the protobuffer data that is being sent, especially since YouTube appears to use non-standard/deprecated functionality which is not properly supported by almost all tools that could be used to try and extract the data.

As an alternative you can jump around in the My Subscriptions list, and also select which channels you want to include in the filtered list.

Going to close this issue, and will track any further progress in #715

**Comment by mhomak** [comment]
Thanks for looking at it
have a good day
