### ISSUE TITLE
KODI frezzes / YouTube addon stops responding when accessing 'My Subscriptions'

### ISSUE THREAD

**Issue by C-O-D** [anxdpanic/plugin.video.youtube#882]
### Context

* Add-on Version: 7.0.9
* Kodi Version: 21.1
[kodi.log](https://github.com/user-attachments/files/16648903/kodi.log)

* Kodi GUI Language: German
* Operating System: Manjaro Linux
* Operating System Language: German

------

### Expected Behavior

Unhindered access to 'My Subscriptions', be it in the addon or as a widget, without the CPU boiling and KODI freezing

------

### Current Behavior

CPU gets hot and kodi.bin is very busy as soon as I access 'My Subscriptions' (via widget or addon). Content won't load and I have to kill KODI because it stops responding. It may work without any problems the next time you start it - but maybe not the next time.

------

### Steps to Reproduce

1. Simply go to 'My Subscriptions' or create a 'My Subscriptions' widget and then access it
2. 

------

### Log

See attachment

------

### Additional Information

- I have already set the widget address to the new version (plugin://plugin.video.youtube/special/my_subscriptions) , before it didn' t even load one single time
- I also had these problems with the previous beta versions of version 7.0.7.1 (which still works perfectly so far and which I am using again). I thought I'd wait and see if the problem cleared up but now that 7.0.9 has appeared in the repos I wanted to try again but the problem is still there and my KODI is super unstable as a result.

------

**Comment by MoojMidge** [comment]
How are you accessing the plugin? Via the plugin directly? Skin widgets? Via a Kodi remote app? Some other plugin? 

You seem to have multiple plugin invocations happening simultaneously in different threads.

The last plugin invocations at the end of your log is for My Subscriptions using the new plugin url, while almost simultaneously a second attempt to access My Subscriptions occurs using the old plugin url.

This is going to be problematic for a number of reasons, but lets try and narrow down some potential causes of the freeze. 

Can you comment out the following two lines and see if there is any difference? 
https://github.com/anxdpanic/plugin.video.youtube/blob/23c1824fbe6e9a33f6d73cb42abafeec3f3dd243/resources/lib/youtube_plugin/kodion/sql_store/storage.py#L212

 https://github.com/anxdpanic/plugin.video.youtube/blob/23c1824fbe6e9a33f6d73cb42abafeec3f3dd243/resources/lib/youtube_plugin/kodion/sql_store/storage.py#L219

**Comment by C-O-D** [comment]
I'm here with the Arctic Fuse skin and open Kodi as normal on my PC, then navigate to my 'My Subscriptions' widget (that I created on my home screen) with my remote control and at that moment the CPU load increases and that's it, the content of the widget is not displayed. With a lot of luck, I sometimes manage to navigate directly into the addon and select 'My Subscriptions' from there, but nothing loads there either.
For comparison, with the old version 7.0.7.1 the widget loads lightning fast and does not cause any particular CPU load.
Your suggestion of commenting out the lines didn't help, see log.

[kodi2.log](https://github.com/user-attachments/files/16650075/kodi2.log)

**Comment by C-O-D** [comment]
You were right, your hint about the simultaneous invocations made me (luckily) think again and lo and behold, I had forgotten an entry in the Spotlight widget from Arctic Fuse that still had the old address. After I corrected that, I had two trouble-free starts, but then it happened again: as soon as I navigated to the entry that activated the widget, the CPU load went up (and the content was not processed) and I had to kill KODI.
Btw, I also deleted the feeds.sqlite in the hope that that would help, but unfortunately that wasn't the case.
I have attached the log...

[kodi3.log](https://github.com/user-attachments/files/16656640/kodi3.log)

**Comment by C-O-D** [comment]
And here's another log with the changes you suggested: [kodi4.log](https://github.com/user-attachments/files/16656906/kodi4.log)

**Comment by C-O-D** [comment]
And here's another log with the changes you suggested: [kodi4.log](https://github.com/user-attachments/files/16657194/kodi4.log)

**Comment by MoojMidge** [comment]
I'm tied up with a few other things so can't look at this in great detail for the next few days unfortunately, so my responses are going to be broad suggestions that may or may not achieve anything.

If you just leave Kodi for more than 30s does it eventually recover?

The reason I ask is that your log indicates a request is made but no response is ever received. The requests should timeout after around 30s, but given that you should normally get a response in ~300ms we can try and reduce the timeout period in the plugin settings:

`Settings > Advanced > Internet > Requests read timeout` - change from 27s to 7s and see if Kodi recovers next time this happens.

**Comment by C-O-D** [comment]
Changing the request read timeout didn't have any effect, I'm now pretty sure that calling both widgets at the same time (i.e. the spotlight and the category widget in Arctic Fuse) is the problem IF they have the same address - in this case 'My Subscriptions '.
If I change the spotlight widget to 'Recommendations', for example, I no longer have any problems - even without all your suggestions for changes.
Loading is still a bit delayed at around 1 sec and not as fast as in version 7.0.7.1 where it was lightning fast, but that's maybe ok.
It would still be nice if you could solve it at some point, in any case, thank you for your quick response...

[kodi5.log](https://github.com/user-attachments/files/16673908/kodi5.log)

**Comment by MoojMidge** [comment]
@C-O-D, @DjDiabolik,

Been looking at this a bit more, still don't know what is going on.

Found a couple of minor issues with My Subscriptions. Shouldn't have caused this issue, but try installing this version of the plugin and seeing if there is any difference:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

I also duplicated your setup with multiple widgets pointing to the same plugin path and reloading the same plugin path at the same time, and it works fine for me with Kodi 20/21 and Python 3.8.15/3.11.2

The only thing common between the two of your reports is that you are both using the Flatpak version Kodi 21 with Python 3.11.9

How familiar are you with Flatpak? Do you know how to backup your Kodi settings, then try to "update" to an older version of Kodi using Flatpak to see if the problem persists with a different Kodi and Python version? This will definitely cause problems with your setup which is why a backup is essential before attempting this.

**Comment by DJMix-I-Can** [comment]
This is happening to me as well. I believe it started about a week ago. I never had this issue before. When I first open Kodi & the widgets are loading, Youtube just keeps trying to load. It does not timeout. It just keeps trying to load & just hangs. I'm able to maneuver to the Youtube addon & disable it. Once I do that, Kodi freezes & have to kill Kodi. Once I reopen Kodi, all of the widgets load up, minus Youtube since it's disabled. Once I re-enable it & reload the skin. The widget loads. It only works one time after re-enabling it. The next time I re-open Kodi, it hangs again. I also redid the widget path. I did try the zip file you just posted. Unfortunately, the problem persists. I'll try to post a log tomorrow.  I'm using Kodi Nexus 20.5 on the Nvidia Shield with 7.0.9 addon. It's happening on both of my shields. Thanks.

**Comment by MoojMidge** [comment]
> I'll try to post a log tomorrow. I'm using Kodi Nexus 20.5 on the Nvidia Shield with 7.0.9 addon. It's happening on both of my shields.

That would be very helpful if you can, showing it working the first time, then hanging the next time

**Comment by DJMix-I-Can** [comment]
OK Here goes the three logs from my description above. The logs are in order according to my steps. I forgot to mention yesterday. I've also noticed that every time a video ends. The refreshing (loading) takes a little longer. Sometimes it crashes Kodi. It's happens sporadically. 

[(1)YoutubeHangsKill.log](https://github.com/user-attachments/files/16733623/1.YoutubeHangsKill.log)
[(2)ReenableYoutubeReloadSkin.log](https://github.com/user-attachments/files/16733624/2.ReenableYoutubeReloadSkin.log)
[(3)YoutubeHangsQuit.log](https://github.com/user-attachments/files/16733625/3.YoutubeHangsQuit.log)

Edit: Last night I installed the 7.0.7.1 version that @C-O-D  mentioned. That's definitely much faster & snappier. I then decided to try out some different versions to try to pinpoint when it started happening.  I believe the issue started in 7.0.8+beta 1. It performed the same way as 7.0.9. 
Thanks.

**Comment by MoojMidge** [comment]
Can you check if there is any improvement with the following test version?

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by C-O-D** [comment]
I would really like to refrain from your suggestion to install another KODI version (as I am far too happy to have finally found a working version via Flatpak and I also don't really know how to do this in the most sensible way + the time factor) and perhaps leave this to @DJMix-I-Can as he still has an older version.
But I have installed your last suggested add-on version and it seems to work without any problems but I don't get complete subscriptions but only some entries from one channel...?
(even after deleting all caches, etc.)

Btw: I was just about to revert to version 7.0.1.0 this morning as the current version caused a lot more problems and KODI kept freezing even when I was doing other things with KODI...

**Comment by MoojMidge** [comment]
> I would really like to refrain from your suggestion to install another KODI version

Yeah, no need to do this since the issue does not appear to be related to the version of Kodi being used.

> but I don't get complete subscriptions but only some entries from one channel...?

Can you get a log of this?

**Comment by C-O-D** [comment]
Sorry, forgot about that: [kodi6.log](https://github.com/user-attachments/files/16735666/kodi6.log)

**Comment by MoojMidge** [comment]
Ah timeout is too short. Try with this version. It may freeze again though.

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by C-O-D** [comment]
Now no subscriptions are loaded at all: [kodi7.log](https://github.com/user-attachments/files/16735999/kodi7.log)

**Comment by MoojMidge** [comment]
Lol... time for dinner I think

One more try: https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by rjousse18** [comment]
Hi, same issue here for a week, I use Artic Horizon 2 skin

**Comment by kloodhu** [comment]
i have very similar issues for about a week too.

**Comment by C-O-D** [comment]
Last version looks very promising so far - trying to stress KODI here but so far no problems and everything very performant...

**Comment by MoojMidge** [comment]
> Last version looks very promising so far - trying to stress KODI here but so far no problems and everything very performant...

Thats good. It is not going to be quite as fast as v7.0.7.1 because that version caches the My Subscriptions listing, but it gets pretty close I think.

If some other people can test and confirm the problem is resolved then I can push out a release while I try and figure out whether it will be possible to resolve the root cause of the problem.

Edit: Thanks for testing and providing the logs btw, very helpful.

**Comment by MoojMidge** [comment]
I still haven't been able to actually replicate or properly identify the problem. The previous test versions are changes based on guessing what could avoid the problem.

Can anyone who was experiencing this problem using v7.0.9 test the following version and see if it also freezes? https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/thread_test_fix.zip

**Comment by DJMix-I-Can** [comment]
> I still haven't been able to actually replicate or properly identify the problem. The previous test versions are changes based on guessing what could avoid the problem.
> 
> Can anyone who was experiencing this problem using v7.0.9 test the following version and see if it also freezes? https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/thread_test_fix.zip

It's still happening.  I let it sit for 5 minutes & it doesn't time out.  Selected Quit to exit Kodi.
[kodi.log](https://github.com/user-attachments/files/16737818/kodi.log)

**Comment by MoojMidge** [comment]
Ok that rules out one possible cause. 

Do the workarounds in this version avoid the freezes?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by DJMix-I-Can** [comment]
> Lol... time for dinner I think
> 
> One more try: https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

I'm actually trying this one right now. Will let you know in a couple.

**Comment by DJMix-I-Can** [comment]
Just as @C-O-D . This version is working fine. It loaded fine with my old widget path of  ActivateWindow(Videos,"plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?category_label=My+Subscriptions",return)
To make sure, I redid the widget path to 
ActivateWindow(Videos,"plugin://plugin.video.youtube/special/my_subscriptions/?category_label=My+Subscriptions",return)
I closed Kodi, cleared the cache & reopened it. It didn't hang. I tried this numerous times & it loaded up fine. I deleted the temp folder, thumbnails & textures.db file in order to give Kodi a little strain when first opening. There were no issues with Youtube loading. It's looking good. If I may ask, what was the issue? Thanks.

**Comment by MoojMidge** [comment]
Thanks for confirming.

> If I may ask, what was the issue?

Still not exactly sure, can't replicate the problem at all, but there seems to be a deadlock occurring somewhere.

An overly simplified explanation is that either database access or low level network access is being requested for exclusive usage by one part of the plugin, and the access is not being granted or is otherwise not being released, so that it can be used by other parts of the plugin. The other parts of the plugin keep waiting for access to be granted, but it never does, and this ends up causing Kodi to freeze up.
