### ISSUE TITLE
Focus on Speed and Stability

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#952]
### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.

The plugin takes a very long time to load compared to a lot of other video playback plugins and has a lot of playback freezing especially during playback of shorts.

------

### Suggest a Solution (optional)

Look at focusing development on efficiency and playback improvements and holding back on new features so usability is sufficiently improved. Perhaps delegating more time or people to developing this plugin as it is one of the most important kodi plugins due to youtube being so vital these days in education and entertainment.

------

**Comment by MoojMidge** [comment]
The plugin has profiling built into it. It is enabled when you enable debug logging.

If you have a problem with the plugin being too slow then post a debug log and it can be looked into.

If you want your enhancement request to be considered you will need to provide some actual details.

Leaving aside the practicality of what you would like, as it stands nothing you have commented on is quantifiable or even identifiable/reproducible, and so there is no action warranted.

**Comment by ghost** [comment]
Generalized requests arent unquantifiable. Asking for more support on the project from say osmc who is dependant on it for the reasons listed per say is a quatifiable action because its either done or its not. Thats one way to enlist more support.

The reality is that there are only 1-2 people commiting on this project regularly compared to osmc proper its not a ton, it seems like it needs concrete steps twords enlisting more support and diversification might do more good than just the task of harvesting data on bugs 

Open source isnt just about the aspect of community insofar as people colaberating on the actual bugs its also important that we give feedback about the experience. If you get a million specific feature request ideas. Why not some broad feedback as well?

**Comment by MoojMidge** [comment]
> Asking for more support

From who? With what? For what purpose? How will the support be provided?


> from say osmc who is dependant on it for the reasons listed per say is a quatifiable action because its either done or its not. Thats one way to enlist more support.

So there is the "who". By all means, you can go ahead and ask for support from anyone. I dont think anything is required at the moment but all contributions are welcome.


> The reality is that there are only 1-2 people commiting on this project regularly compared to osmc proper its not a ton, it seems like it needs concrete steps twords enlisting more support

Concrete steps towards what? What are the steps in the plan for providing support? What are the objectives? How will progress be measured? How will results be evaluated?


> diversification might do more good than just the task of harvesting data on bugs

This is really an odd take. Why do you think asking for a debug log is harvesting of data? What do you expect a diverse team of support providers to do if they have no information to work with?


> its also important that we give feedback about the experience. If you get a million specific feature request ideas. Why not some broad feedback as well?

I see little value in what amounts to a general complaint of no substance. I have identified what you can do that would be useful, but you are free to do as you like.

Edit: Just provide a debug log if you have a problem. It is really as simple as that. No need to dress it up as an enhancement request about nothing.

**Comment by ghost** [comment]
You have a miserly additude tword user feedback. Look any proprietary software has hundreds of 'complaints' and feedback that allows any good buisness to understand what their customers desire. If they take everything personally and attack back at criticisms instead of trying to absorb and adopt feedback into their project they will surely look shady and fail to have success. Open source surely should be no different?

Sure its great if everyone would lend a hand but I think its just as important to have some barometer of what the general public wants?

**Comment by MoojMidge** [comment]
> You have a miserly additude tword user feedback.

Lol... is that because I don't simply agree with you?

I am just a contributor. You are welcome to consider that my opinion is no more valid than yours, in as much as your own opinion is certainly no more valid than anyone else's.

No one is stopping you from doing anything to provide "support", but that is not what you are proposing to do.

What you are "offering" is for _other_ people to do what you want, even though you don't actually have any plan for achieving what you want, or even any concrete thoughts about what you actually want. Like I said it is just a general complaint about nothing.


> If they take everything personally and attack back at criticisms instead of trying to absorb and adopt feedback into their project they will surely look shady and fail to have success

You have a proposal and I am providing you feedback on your proposal. Why don't you try to absorb and adopt that feedback instead of taking things personally?

I have posed a number of questions, and sought greater clarity on your proposal, in addition to advising on what I believe will be a more productive alternative. It looks a little shady that you have ignored this, and I fear that your proposal will fail to have success.

> Sure its great if everyone would lend a hand but I think its just as important to have some barometer of what the general public wants?

It would be great if everyone can lend a hand with your plan, but i think it is just as important to have some barometer of what others think of your plan instead.

Edit: I'm just having a bit of fun at your expense. I hope you don't take it personally, but if you are offended I apologise. But seriously now, it is a lot simpler to just post a log.

**Comment by ghost** [comment]
Look theres actual products being sold around this stuff like osmc's hardware. The idea of asking for support is to ask for support from the people actually profiting off of your work? Its not a criticism of your work its more that theres actual money being put into this and none of it is reaching this project.

**Comment by MoojMidge** [comment]
> Look theres actual products being sold around this stuff like osmc's hardware. The idea of asking for support is to ask for support from the people actually profiting off of your work? Its not a criticism of your work its more that theres actual money being put into this and none of it is reaching this project.

So what?

To put it very simply: 

- I don't think any support is needed at the moment. 
- You think it is, but won't identify any details

So nothing will happen.

**Comment by ghost** [comment]
Ok fine I'll try and levy my complaints twords those benefiting more from the project. I had half thought that you were in fact levied from bigger projects with more resources due to the fact that this does appear to be the official YouTube app.

In my opinion those larger projects should absolutely be contributing some of talents tword this project and I thought that they were however it seems more dire in that regard than what I thought.

Have a good day.

**Comment by MoojMidge** [comment]
I really don't understand.

Lets assume that there is a pool of resource unconstrained, talented people, ready and waiting for the word to jump in and do something, and lets assume that this project is in dire need of their support.

What do you expect these groups and individuals to do if you don't provide any details of what your problem is and instead just complain to various other parties?

Note as well that there is no reason to complain about anything either - this is an open source project that operates within a larger open source Kodi ecosystem.

What is contributed is done so on a voluntary basis. There is nothing wrong with other parties using Kodi or this plugin in any way that is allowed for by open source license that the projects are licensed under.

Please don't antagonise others for whatever perceived shortfalls in contributions you think may exist.
