### ISSUE TITLE
No sound when first playing a video using InputStream.Adaptive

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#989]
Today I reactivated InputStream.Adaptive for testing another issue, and just observed an even worse behavoir. I do not know how much time has it been happening because I do not use InputStream.Adaptive, but I think it may be somehow related to the previous.

**The same thing described for the subtitles is now happening to the audio stream.**

Explanation:

When a video has more than one audio stream choice, the plugin automatically selects the one in my locale language, or the first stream in the list if my locale language is not present (*).

Guess what? Nothing is heard when I first open the video. Completely silent.

Now choose manually another audio stream. It works, it is heard.

Now go manually back to the audio stream that was silent. It works, it is heard.

So both issues, subtitles and audio failing to work, seem to be something that happens only when you first open the video from the beginning. After choosing a stream manually it works, and it continues working unless you stop the playback and start the video playback again from the beginning.

----------

(*) Very unfortunately, there is no option in the plugin or in InputStream.Adaptive to default to the original audio of the video. Same applies for subtitles, where only the locale language can be chosen. This is not related to the issue described in this thread, but in my opinion it is a great lack. Specially regarding Youtube, where translations are mostly automated by AI and provide a horrible experience.

_Originally posted by @malversoft in https://github.com/anxdpanic/plugin.video.youtube/issues/634#issuecomment-2486428438_

**Comment by MoojMidge** [comment]
I can't replicate this, but a couple of other people have mentioned something similar but not provided any details.

> Nothing is heard when I first open the video. Completely silent.

Can you post a full debug log?

> Very unfortunately, there is no option in the plugin or in InputStream.Adaptive to default to the original audio of the video.

The default Kodi settings apply here, but there are some improvements that could be made to this in the addon.
`Settings > Player > Language > Audio > Preferred audio language`


> Same applies for subtitles, where only the locale language can be chosen.

What does this mean? There are a number of different options for subtitle language selection. Can you describe what the available options don't allow for?

**Comment by malversoft** [comment]
> `Settings > Player > Language > Audio > Preferred audio language`

Unfortunately that affects everything I access from Kodi.
Youtube automated audio translations suck, but the rest of Internet is plenty of quality content in my language.

> There are a number of different options for subtitle language selection. Can you describe what the available options don't allow for?

Currently there are five options in the Youtube plugin configuration (whatever you configure in Kodi subtitles). But in practice they are reduced to only one, and in fact it is the bad one.
Let me illustrate that:
- `"Ask"`. This is not suitable to configure for each and every video, in my opinion. It is not practic having to choose from the big list of languages every time you play a video.
- `"None"` is... well, no subtitles at all.
- `"<MY_LANGUAGE> (not autogenerated)"`. This is the ideal option. But very few videos from very few channels offer non-automated (carefully translated) subtitles in other languages. So in practice this option does the same as `"None"`.
- `"<MY_LANGUAGE>"`. This is the option I want to avoid, autogenerated garbage that simply sucks. It confuses more than anything else.
- `"<MY_LANGUAGE>, with original/English as default"`. In practice this option is equivalent to choosing simply `"<MY_LANGUAGE>"` for all english videos, because automated translations from english always use to exist. And if the video is not in english, either the original subtitles do not help a lot, or either the english ones are autogenerated and suck.

So in practice the whole set of options is reduced to `"None"` or `"<MY_LANGUAGE>"` (with automated translation, which sucks).

I really miss the simple option of `"Original"` language for subtitles. No confusion, no crappy automated translation, just a plain transcription of the audio. It would help a lot, specially when the original is a language you know but the audio is a bit difficult to understand (that uses to happen a lot).

**Comment by malversoft** [comment]
> Can you post a full debug log?

[Here it is](https://paste.kodi.tv/iqaduvaxej.kodi). This is the log of a "play pressing" from the start of the video.
When playing the video from the start, the audio is not played at all.

[That video](https://www.youtube.com/watch?v=aSYEgfCl-e8) has 2 audio streams. Both in Spanish (only the codec changes), just to get the language off the equation.

I must note that the issue does not seem to happen with all videos, and I have had no success in characterizing which ones are affected. But it happens in the majority of channels I am subscribed to. And specially with english videos, the ones that use to have multiple audio streams with automated translations.

I was going to post another log to show how changing audio stream selection made the audio start to play (it does), but I have noticed something that seems to make that unnecessary:

If you pause the video and resume it, the audio still does not play.
But if you STOP the video and resume it, then the audio plays normally.
Also, if you jump forward or backward in the video, the audio also starts to play normally.
So it seems the audio stream is picked correctly. It just does not play when the playback was started from the start of the video.

After that, if you play (or fast-forward) the video until the end, a later replay (obviously from the start) makes the audio fail again.

(Just to note, I described a very similar behavior for subtitles in #634. When playing the video from the start, subtitles hotkey activates/deactivates the setting, but subtitles simply are not shown).

**Comment by MoojMidge** [comment]
> [Here it is](https://paste.kodi.tv/iqaduvaxej.kodi). This is the log of a "play pressing" from the start of the video.

An issue like this needs a full debug log. A partial log or a non-debug log does not have sufficient detail to investigate what the problem may be.

> Unfortunately that affects everything I access from Kodi.

Yes the Kodi settings apply to everything played in Kodi, and the addon you are using is a Kodi addon that is playing a video in Kodi. Can't do anything about that and it is not a realistic expectation for addons to circumvent the normal video playback settings of the actual video player that is used.

What do you actually have set for `Settings > Player > Language > Audio > Preferred audio language`? As mentioned previously the following can be done

- Media default will use the language configured in the addon
- Original will use the original language
- User interface will use the Kodi language
- Any other language selected will be used if selected

**Comment by MoojMidge** [comment]
There seems to be a regression in InputStream.Adaptive with handling audio in HLS streams.

If you use the Setup Wizard and/or enable MPEG-DASH the sound should work.

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip implements the following:

> What do you actually have set for `Settings > Player > Language > Audio > Preferred audio language`? As mentioned previously the following can be done
> 
> * Media default will use the language configured in the addon
> * Original will use the original language
> * User interface will use the Kodi language
> * Any other language selected will be used if selected
